namespace PgJsonObjects
{
    public enum OtherRequirementType
    {
        Internal_None,
        IsAdmin,
        IsLycanthrope,
        CurHealth,
        Race,
        HasEffectKeyword,
        FullMoon,
        IsHardcore,
        DruidEventState,
        PetCount,
        RecipeKnown,
        IsNotInCombat,
        IsLongtimeAnimal,
        InHotspot,
        HasInventorySpaceFor,
        IsVegetarian,
        InGraveyard,
        Appearance,
        Or,
        EquippedItemKeyword,
        GardenPlantMax,
        QuestCompleted,
        MinFavorLevel,
        MinSkillLevel,
        GuildQuestCompleted,
        RuntimeBehaviorRuleSet,
        InteractionFlagSet,
    }
}
