namespace PgJsonObjects
{
    public enum OtherRequirementType
    {
        Internal_None,
        IsLycanthrope,
        HasEffectKeyword,
        FullMoon,
        IsHardcore,
        DruidEventState,
        PetCount,
        RecipeKnown,
        IsNotInCombat,
        IsLongtimeAnimal,
        InHotspot,
        HasInventorySpaceFor,
        IsVegetarian,
        InGraveyard,
        Or,
        EquippedItemKeyword,
        QuestCompleted,
        MinFavorLevel,
        MinSkillLevel,
        GuildQuestCompleted,
        RuntimeBehaviorRuleSet,
        InteractionFlagSet,
        IsVolunteerGuide,
        IsNotGuest,
    }
}
