namespace PgBuilder
{
    public enum GameCombatSkill
    {
        None,
        Sword,
        FireMagic,
        Unarmed,
        Psychology,
        Staff,
        Mentalism,
        Archery,
        Shield,
        AnimalHandling,
        Knife,
        Cow,
        Deer,
        Pig,
        Spider,
        Werewolf,
        BattleChemistry,
        Necromancy,
        Hammer,
        Druid,
        IceMagic,
        GiantBat,
        Axe,
        Bard,
        Rabbit,
        Priest,
        Warden,
        FairyMagic,
    }
}
