using System.Collections.Generic;

namespace PgJsonObjects
{
    public static class AdvancementFriendlyNames
    {
        public static Dictionary<string, string> FriendlyNameTable = new Dictionary<string, string>()
        {
            { "Skeleton", "Skeleton" },
            { "Bear", "Bear" },
            { "BrainBug", "Brain Bug" },
            { "Deer", "Deer" },
            { "DarknessAnimal", "Darkness Animal" },
            { "Deinonychus", "Deinonychus" },
            { "ElementalCold", "Cold Elemental" },
            { "ElementalElectricity", "Electricity Elemental" },
            { "Fairy", "Fairy" },
            { "Bovine", "Bovine" },
            { "Spider", "Spider" },
            { "Gnasher", "Gnasher" },
            { "Goblin", "Goblin" },
            { "HookHorror", "Hook Horror" },
            { "Mantis", "Mantis" },
            { "MushroomTurret", "Mushroom Turret" },
            { "Myconian", "Myconian" },
            { "Orc", "Orc" },
            { "Panther", "Panther" },
            { "Pig", "Pig" },
            { "PoisonSlug", "Poison Slug" },
            { "PsiMantis", "Psi Mantis" },
            { "Rat", "Rat" },
            { "Rhino", "Rhino" },
            { "Sheep", "Sheep" },
            { "Wolf", "Wolf" },
            { "Snail", "Snail" },
            { "Tiger", "Tiger" },
            { "Tornado", "Tornado" },
            { "TotalHorror", "Total Horror" },
            { "Urak", "Urak" },
            { "Worg", "Worg" },
            { "ShamblingCorpse", "Shambling Corpse" },
            { "FireConstruct", "Fire Construct" },
            { "Sigil", "Sigil" },
            { "MiniGolem", "Mini Golem" },
            { "Trap", "Trap" },
            { "Werewolf", "Werewolf" },
            { "PlantBeast", "Plant Beast" },
            { "AlienDog", "Alien Dog" },
            { "ElementalNature", "Nature Elemental" },
            { "Slime", "Slime" },
            { "ColdSlime", "Cold Slime" },
            { "SlimeNonRegen", "Non Regen Slime" },
            { "HumanoidWerewolf", "Humanoid Werewolf" },
            { "Yeti", "Yeti" },
            { "Zombie", "Zombie" },
            { "Striga", "Striga" },
            { "Ghost", "Ghost" },
            { "InjectorBug", "Injector Bug" },
            { "FaceOfDeath", "Face Of Death" },
            { "Watcher", "Watcher" },
            { "BitingVine", "Biting Vine" },
            { "Ranalon", "Ranalon" },
            { "Troll", "Troll" },
            { "WinterCourtFae", "Winter Court Fae" },
            { "Ogre", "Ogre" },
            { "FireDroach", "Fire Droach" },
            { "HumanoidNecromancer", "Humanoid Necromancer" },
            { "HumanoidFodder", "Humanoid Fodder" },
            { "Sedgewick", "Sedgewick" },
            { "Basilisk", "Basilisk" },
            { "Lamia", "Lamia" },
            { "Golem", "Golem" },
            { "Ghoul", "Ghoul" },
            { "ElectricityWorm", "Electricity Worm" },
            { "FireWorm", "Fire Worm" },
            { "ColdSphere", "Cold Sphere" },
            { "Manticore", "Manticore" },
            { "Grimalkin", "Grimalkin" },
            { "Rakshasa", "Rakshasa" },
            { "FlapSkull", "Flap Skull" },
            { "Minotaur", "Minotaur" },
            { "Cockatrice", "Cockatrice" },
            { "GiantBeetle", "Giant Beetle" },
            { "GiantBat", "Giant Bat" },
            { "Triffid", "Triffid" },
            { "GiantScorpion", "Giant Scorpion" },
            { "Kraken", "Kraken" },
            { "ElectricityDroach", "Electricity Droach" },
            { "Barghest", "Barghest" },
            { "AlienDogCold", "Cold Alien Dog" },
            { "Ballista", "Ballista" },
            { "Hippogriff", "Hippogriff" },
            { "MagmaGolem", "Magma Golem" },
            { "Gargoyle", "Gargoyle" },
            { "OrcInfiltrator", "Orc Infiltrator" },
            { "OrcSuperSoldier", "Orc Super Soldier" },
            { "OrcTechie", "Orc Techie" },
            { "Mummy", "Mummy" },
            { "MummyBaruti", "Mummy Baruti" },
            { "Scray", "Scray" },
            { "Hippo", "Hippo" },
            { "RanalonGuardian", "Ranalon Guardian" },
            { "FireRat", "Fire Rat" },
            { "GroupLoot0", "Group Loot #0" },
            { "GroupLoot1", "Group Loot #1" },
            { "GroupLoot2", "Group Loot #2" },
            { "GroupLoot3", "Group Loot #3" },
            { "ImprovedSoloLoot", "Improved Solo Loot" },
            { "GoodNpcRewardLoot", "Good Npc Reward Loot" },
            { "GreatNpcRewardLoot", "Great Npc Reward Loot" },
            { "MediocreLootChest", "Mediocre Loot Chest" },
            { "DecentLootChest", "Decent Loot Chest" },
            { "GoodLootChest", "Good Loot Chest" },
            { "GreatLootChest", "Great Loot Chest" },
            { "SpecialEventLootChest", "Special Event Loot Chest" },
            { "DefensesElite0", "Defenses Elite #0" },
            { "DefensesElite1", "Defenses Elite #1" },
            { "DefensesElite2", "Defenses Elite #2" },
            { "DefensesBoss0", "Defenses Boss #0" },
            { "DefensesBoss1", "Defenses Boss #1" },
            { "DefensesBoss2", "Defenses Boss #2" },
            { "DefensesEpicBoss1", "Defenses Epic Boss #1" },
            { "DefensesEpicBoss2", "Defenses Epic Boss #2" },
            { "DefensesEpicBoss3", "Defenses Epic Boss #3" },
            { "GazlukKeepEliteBoost1", "Gazluk Keep Elite Boost #1" },
            { "GazlukKeepEliteBoost2", "Gazluk Keep Elite Boost #2" },
            { "GazlukKeepBossBoost1", "Gazluk Keep Boss Boost #1" },
            { "GazlukKeepBossBoost2", "Gazluk Keep Boss Boost #2" },
            { "PetBear", "Bear Pet" },
            { "PetRat", "Rat Pet" },
            { "PetCat", "Cat Pet" },
            { "Misc", "Misc" },
            { "Health1", "Health #1" },
            { "Health2", "Health #2" },
            { "Health3", "Health #3" },
            { "Health4", "Health #4" },
            { "Health5", "Health #5" },
            { "Health6", "Health #6" },
            { "Health7", "Health #7" },
            { "Health8", "Health #8" },
            { "Health9", "Health #9" },
            { "Health10", "Health #10" },
            { "Health11", "Health #11" },
            { "Health12", "Health #12" },
            { "Health13", "Health #13" },
            { "Health14", "Health #14" },
            { "Health15", "Health #15" },
            { "Health16", "Health #16" },
            { "Armor1", "Armor #1" },
            { "Armor2", "Armor #2" },
            { "Armor3", "Armor #3" },
            { "Armor4", "Armor #4" },
            { "Armor5", "Armor #5" },
            { "Armor6", "Armor #6" },
            { "Armor7", "Armor #7" },
            { "Armor8", "Armor #8" },
            { "Armor9", "Armor #9" },
            { "Armor10", "Armor #10" },
            { "Armor11", "Armor #11" },
            { "Armor12", "Armor #12" },
            { "Armor13", "Armor #13" },
            { "Armor14", "Armor #14" },
            { "Armor15", "Armor #15" },
            { "Armor16", "Armor #16" },
            { "Damage1", "Damage #1" },
            { "Damage2", "Damage #2" },
            { "Damage3", "Damage #3" },
            { "Damage4", "Damage #4" },
            { "Damage5", "Damage #5" },
            { "Damage6", "Damage #6" },
            { "Damage7", "Damage #7" },
            { "Damage8", "Damage #8" },
            { "Damage9", "Damage #9" },
            { "Damage10", "Damage #10" },
            { "Damage11", "Damage #11" },
            { "Damage12", "Damage #12" },
            { "Damage13", "Damage #13" },
            { "Damage14", "Damage #14" },
            { "Damage15", "Damage #15" },
            { "Damage16", "Damage #16" },
            { "Damage17", "Damage #17" },
            { "ExtraXp1", "Extra Xp #1" },
            { "ExtraXp2", "Extra Xp #2" },
            { "Elite0", "Elite #0" },
            { "Elite1", "Elite #1" },
            { "Elite2", "Elite #2" },
            { "Boss0", "Boss #0" },
            { "Boss1", "Boss #1" },
            { "Boss2", "Boss #2" },
            { "EpicBoss1", "Epic Boss #1" },
            { "EpicBoss2", "Epic Boss #2" },
            { "EpicBoss3", "Epic Boss #3" },
            { "HealthRegen1", "Health Regen #1" },
            { "HealthRegen2", "Health Regen #2" },
            { "HealthRegen3", "Health Regen #3" },
            { "HealthRegen4", "Health Regen #4" },
            { "HealthRegen5", "Health Regen #5" },
            { "ArmorRegen1", "Armor Regen #1" },
            { "ArmorRegen2", "Armor Regen #2" },
            { "ArmorRegen3", "Armor Regen #3" },
            { "ArmorRegen4", "Armor Regen #4" },
            { "ArmorRegen5", "Armor Regen #5" },
            { "Evasion1", "Evasion #1" },
            { "Evasion2", "Evasion #2" },
            { "Evasion3", "Evasion #3" },
            { "Evasion4", "Evasion #4" },
            { "Evasion5", "Evasion #5" },
            { "PetHealth1", "Pet Health #1" },
            { "PetHealth2", "Pet Health #2" },
            { "PetHealth3", "Pet Health #3" },
            { "PetHealth4", "Pet Health #4" },
            { "PetHealth5", "Pet Health #5" },
            { "PetHealth6", "Pet Health #6" },
            { "PetHealth7", "Pet Health #7" },
            { "PetHealth8", "Pet Health #8" },
            { "PetHealth9", "Pet Health #9" },
            { "PetHealth10", "Pet Health #10" },
            { "PetHealth11", "Pet Health #11" },
            { "PetHealth12", "Pet Health #12" },
            { "PetHealth13", "Pet Health #13" },
            { "PetHealth14", "Pet Health #14" },
            { "PetHealth15", "Pet Health #15" },
            { "PetHealth16", "Pet Health #16" },
            { "PetArmor1", "Pet Armor #1" },
            { "PetArmor2", "Pet Armor #2" },
            { "PetArmor3", "Pet Armor #3" },
            { "PetArmor4", "Pet Armor #4" },
            { "PetArmor5", "Pet Armor #5" },
            { "PetArmor6", "Pet Armor #6" },
            { "PetArmor7", "Pet Armor #7" },
            { "PetArmor8", "Pet Armor #8" },
            { "PetArmor9", "Pet Armor #9" },
            { "PetArmor10", "Pet Armor #10" },
            { "PetArmor11", "Pet Armor #11" },
            { "PetArmor12", "Pet Armor #12" },
            { "PetArmor13", "Pet Armor #13" },
            { "PetArmor14", "Pet Armor #14" },
            { "PetArmor15", "Pet Armor #15" },
            { "PetArmor16", "Pet Armor #16" },
            { "PetDamage1", "Pet Damage #1" },
            { "PetDamage2", "Pet Damage #2" },
            { "PetDamage3", "Pet Damage #3" },
            { "PetDamage4", "Pet Damage #4" },
            { "PetDamage5", "Pet Damage #5" },
            { "PetDamage6", "Pet Damage #6" },
            { "PetDamage7", "Pet Damage #7" },
            { "PetDamage8", "Pet Damage #8" },
            { "PetDamage9", "Pet Damage #9" },
            { "PetDamage10", "Pet Damage #10" },
            { "PetDamage11", "Pet Damage #11" },
            { "PetDamage12", "Pet Damage #12" },
            { "PetDamage13", "Pet Damage #13" },
            { "PetDamage14", "Pet Damage #14" },
            { "PetDamage15", "Pet Damage #15" },
            { "PetDamage16", "Pet Damage #16" },
            { "PetDamage17", "Pet Damage #17" },
            { "PetDamageBoost", "Pet Damage Boost" },
            { "AnimalHandlingPet", "Animal Handling Pet" },
            { "Pet", "Pet" },
            { "PetRage1", "Pet Rage #1" },
            { "PetRage2", "Pet Rage #2" },
            { "PetRage3", "Pet Rage #3" },
            { "PetRage4", "Pet Rage #4" },
            { "PetRage5", "Pet Rage #5" },
            { "PetRage6", "Pet Rage #6" },
            { "PetRage7", "Pet Rage #7" },
            { "PetRage8", "Pet Rage #8" },
            { "PetRage9", "Pet Rage #9" },
            { "PetRage10", "Pet Rage #10" },
            { "PetRage11", "Pet Rage #11" },
            { "PetRage12", "Pet Rage #12" },
            { "PetRage13", "Pet Rage #13" },
            { "PetRage14", "Pet Rage #14" },
            { "PetRage15", "Pet Rage #15" },
            { "PetRage16", "Pet Rage #16" },
            { "PetLoyaltyBonuses", "Pet Loyalty Bonuses" },
            { "Balanced", "Balanced" },
            { "PlayerWerewolf", "Player Werewolf" },
            { "FireMagic", "Fire Magic" },
            { "PlayerPig", "Player Pig" },
            { "PowerPassive", "Power Passive" },
            { "ModestPassive", "Modest Passive" },
            { "Lore", "Lore" },
            { "Dying", "Dying" },
            { "PlayerCow", "Player Cow" },
            { "PlayerSpider", "Player Spider" },
            { "Endurance", "Endurance" },
            { "Notoriety", "Notoriety" },
            { "PlayerDeer", "Player Deer" },
            { "PlayerElf", "Player Elf" },
            { "PlayerHuman", "Player Human" },
            { "PlayerRakshasa", "Player Rakshasa" },
            { "Hoplology", "Hoplology" },
            { "Surveying", "Surveying" },
            { "Foraging", "Foraging" },
            { "TreasureHunting", "Treasure Hunting" },
            { "WerewolfMetabolism", "Werewolf Metabolism" },
            { "Gourmand", "Gourmand" },
            { "CivicPride", "Civic Pride" },
            { "Industry", "Industry" },
            { "PlayerBat", "Player Bat" },
            { "HolisticWellness", "Holistic Wellness" },
            { "RetailManagement", "Retail Management" },
            { "PlayerFae", "Player Fae" },
            { "AlcoholTolerance", "Alcohol Tolerance" },
            { "BonusInventoryFolderAt25", "Bonus Inventory Folder At 25" },
            { "BonusInventoryFolderAt50", "Bonus Inventory Folder At 50" },
            { "PumpkinMimic", "Pumpkin Mimic" },
        };
    }
}
