namespace PgJsonObjects
{
    interface IPgAIAbilitySet
    {
        AIAbility AnimalBite { get; }
        AIAbility AnimalClaw { get; }
        AIAbility AnimalOmegaBite { get; }
        AIAbility AnimalOmegaBite2 { get; }
        AIAbility AnimalHoofFrontKick { get; }
        AIAbility AnimalHoofRageKick { get; }
        AIAbility AnimalHoofRageKick2 { get; }
        AIAbility AnimalHoofFieryFrontKick { get; }
        AIAbility AnimalHoofFieryFrontKick2 { get; }
        AIAbility ElectricPigHitAndRun { get; }
        AIAbility ElectricPigStun { get; }
        AIAbility ElectricPigAoEStun { get; }
        AIAbility LamiaMindControl { get; }
        AIAbility LamiaRage { get; }
        AIAbility SlimeKick { get; }
        AIAbility SlimeKickB { get; }
        AIAbility SlimeBite { get; }
        AIAbility SlimeBiteB { get; }
        AIAbility Slime_SummonSlime { get; }
        AIAbility SlimeSpit { get; }
        AIAbility SlimeSuperSpit { get; }
        AIAbility IceSlimeKick { get; }
        AIAbility IceSlimeKickB { get; }
        AIAbility IceSlimeBite { get; }
        AIAbility IceSlimeBiteB { get; }
        AIAbility BossSlimeKick { get; }
        AIAbility BossSlimeKickB { get; }
        AIAbility BossSlime_SummonSlime1 { get; }
        AIAbility BossSlimeKick2 { get; }
        AIAbility BossSlimeKick2B { get; }
        AIAbility BossSlime_SummonSlime4Elite { get; }
        AIAbility AnimalHeal { get; }
        AIAbility AnimalHeal2 { get; }
        AIAbility AnimalHeal3 { get; }
        AIAbility IceCockPeck { get; }
        AIAbility IceCockFreeze { get; }
        AIAbility NightmareHoof { get; }
        AIAbility NightmareDarknessBomb { get; }
        AIAbility CiervosNightmareHoof { get; }
        AIAbility CiervosDarknessBomb { get; }
        AIAbility Myconian_Bash { get; }
        AIAbility Myconian_Mindspores { get; }
        AIAbility Myconian_Drain { get; }
        AIAbility Myconian_BossBash { get; }
        AIAbility Myconian_Mindspores_Permanent { get; }
        AIAbility Myconian_TidalCurse { get; }
        AIAbility Myconian_Shock { get; }
        AIAbility AlienDog_Punch { get; }
        AIAbility AlienDog_Punch2 { get; }
        AIAbility AlienDog_RagePunch { get; }
        AIAbility MushroomMonster_Bite { get; }
        AIAbility MushroomMonster_Spit1 { get; }
        AIAbility MushroomMonster_Spit2 { get; }
        AIAbility MushroomMonster_SummonMushroomSpawn1 { get; }
        AIAbility MushroomMonster_SummonMushroomSpawn2 { get; }
        AIAbility MushroomMonster_SummonMushroomSpawn3 { get; }
        AIAbility MushroomMonster_SpawnSpit1 { get; }
        AIAbility MushroomMonster_SpawnSpit2 { get; }
        AIAbility MushroomMonster_SpawnSuperSpit1 { get; }
        AIAbility MushroomMonster_SpawnSuperSpit2 { get; }
        AIAbility MaronesaStomp { get; }
        AIAbility MaronesaInfect { get; }
        AIAbility WormBite1 { get; }
        AIAbility WormSpit1 { get; }
        AIAbility WormShove1 { get; }
        AIAbility WormInfect1 { get; }
        AIAbility WormSpit2 { get; }
        AIAbility WormBossSpit { get; }
        AIAbility WormBossAcidBurst { get; }
        AIAbility GnasherBite { get; }
        AIAbility GnasherRend { get; }
        AIAbility Dinoslash { get; }
        AIAbility Dinoslash2 { get; }
        AIAbility Dinobite { get; }
        AIAbility Dinobite2 { get; }
        AIAbility Dinowhap { get; }
        AIAbility Peck { get; }
        AIAbility AnimalFlee { get; }
        AIAbility HippogriffPeck { get; }
        AIAbility HippogriffSlashes { get; }
        AIAbility HippogriffBossSlashes { get; }
        AIAbility RatBite { get; }
        AIAbility RatClaw { get; }
        AIAbility FireRatBite { get; }
        AIAbility FireRatClaw { get; }
        AIAbility GoblinZapBall { get; }
        AIAbility GoblinHateZapBall { get; }
        AIAbility GoblinHateZapBall2 { get; }
        AIAbility RhinoHorn { get; }
        AIAbility RhinoRage { get; }
        AIAbility RhinoFireball { get; }
        AIAbility RhinoBossRage { get; }
        AIAbility YetiPunch { get; }
        AIAbility YetiEncase { get; }
        AIAbility YetiDebuff { get; }
        AIAbility YetiBoulderThrow { get; }
        AIAbility YetiBarrage { get; }
        AIAbility YetiRoarStun { get; }
        AIAbility YetiFlingAway { get; }
        AIAbility YetiIceBallThrow { get; }
        AIAbility YetiIceSpear { get; }
        AIAbility YetiColdOrb { get; }
        AIAbility YetiFrostRing { get; }
        AIAbility WorgBite { get; }
        AIAbility WorgOmegaBite { get; }
        AIAbility BearBite { get; }
        AIAbility BearCrush { get; }
        AIAbility BrainBite { get; }
        AIAbility BrainDrain { get; }
        AIAbility BrainDrain2 { get; }
        AIAbility BigCatClaw { get; }
        AIAbility BigCatPounce { get; }
        AIAbility BigCatRagePounce { get; }
        AIAbility BigCatDebuff { get; }
        AIAbility SpiderBite { get; }
        AIAbility SpiderFireball { get; }
        AIAbility SpiderBossFreePin { get; }
        AIAbility SpiderKill2 { get; }
        AIAbility SpiderInject { get; }
        AIAbility SpiderKill { get; }
        AIAbility AcidBall1 { get; }
        AIAbility SpiderPin { get; }
        AIAbility SpiderKill3 { get; }
        AIAbility AcidBall2 { get; }
        AIAbility AcidSpew1 { get; }
        AIAbility AcidExplosion1 { get; }
        AIAbility AcidExplosion2 { get; }
        AIAbility SpiderIncubate { get; }
        AIAbility MantisClaw { get; }
        AIAbility MantisRage { get; }
        AIAbility MantisAcidBurst { get; }
        AIAbility SherzatClaw { get; }
        AIAbility SherzatAcidSpit { get; }
        AIAbility SherzatDisintegrate { get; }
        AIAbility MantisSwipe { get; }
        AIAbility MantisBlast { get; }
        AIAbility SnailStrike { get; }
        AIAbility SnailRage { get; }
        AIAbility SnailRageB { get; }
        AIAbility SnailRageC { get; }
        AIAbility HookClaw { get; }
        AIAbility HookAcid { get; }
        AIAbility HookRage { get; }
        AIAbility UndeadSword1 { get; }
        AIAbility UndeadSword2 { get; }
        AIAbility UndeadSwordAngry { get; }
        AIAbility UndeadMegaSword1 { get; }
        AIAbility UndeadMegaSword2 { get; }
        AIAbility UndeadMegaSwordAngry { get; }
        AIAbility UndeadLightningSmite { get; }
        AIAbility UndeadPhysicalShield { get; }
        AIAbility UndeadSword1B { get; }
        AIAbility UndeadFireballA { get; }
        AIAbility UndeadFireballB { get; }
        AIAbility UndeadFireballB2 { get; }
        AIAbility UndeadIceBall1 { get; }
        AIAbility UndeadFreezeBall { get; }
        AIAbility UndeadFireballLongA { get; }
        AIAbility UndeadFireballLongB { get; }
        AIAbility UndeadFireballLongB2 { get; }
        AIAbility KhyrulekCurseBall { get; }
        AIAbility UrsulaFireball1 { get; }
        AIAbility UrsulaFireball1B { get; }
        AIAbility UrsulaFireball2 { get; }
        AIAbility UrsulaIceball1 { get; }
        AIAbility UrsulaIceball1B { get; }
        AIAbility UrsulaIceball2 { get; }
        AIAbility UrsulaSummon { get; }
        AIAbility UrsulaRage { get; }
        AIAbility UndeadFireballA2 { get; }
        AIAbility BigHeadCurseball { get; }
        AIAbility UndeadArrow1 { get; }
        AIAbility UndeadArrow2 { get; }
        AIAbility UndeadOmegaArrow { get; }
        AIAbility PetUndeadArrow1 { get; }
        AIAbility PetUndeadArrow2 { get; }
        AIAbility PetUndeadOmegaArrow { get; }
        AIAbility UndeadGrappleArrow1 { get; }
        AIAbility UndeadSelfDestruct { get; }
        AIAbility UndeadDarknessBall { get; }
        AIAbility UndeadBoneWhirlwind { get; }
        AIAbility PetUndeadSword1 { get; }
        AIAbility PetUndeadSword2 { get; }
        AIAbility PetUndeadSwordAngry { get; }
        AIAbility PetUndeadFireballA { get; }
        AIAbility PetUndeadFireballB { get; }
        AIAbility PetUndeadDefensiveBurst { get; }
        AIAbility PetUndeadPunch1 { get; }
        AIAbility ZombiePunch { get; }
        AIAbility ZombieBite { get; }
        AIAbility GoblinSpear1 { get; }
        AIAbility GoblinSpear2 { get; }
        AIAbility GoblinRageSpear1 { get; }
        AIAbility GoblinRageSpear2 { get; }
        AIAbility GoblinHeal1 { get; }
        AIAbility GoblinHeal2 { get; }
        AIAbility GoblinPunch { get; }
        AIAbility GoblinArrow1 { get; }
        AIAbility GoblinArrow2 { get; }
        AIAbility GoblinRageArrow1 { get; }
        AIAbility GoblinRageArrow2 { get; }
        AIAbility GoblinSpreadZapBall { get; }
        AIAbility GoblinBossLightning { get; }
        AIAbility GoblinArmorBuff { get; }
        AIAbility MummySlamA { get; }
        AIAbility MummySlamB { get; }
        AIAbility MummySlamCombo { get; }
        AIAbility MummyWrapA { get; }
        AIAbility MummyWrapB { get; }
        AIAbility MummyWrapRage { get; }
        AIAbility BarutiWrapA { get; }
        AIAbility BarutiWrapB { get; }
        AIAbility BarutiWrapRage { get; }
        AIAbility FireWallAttack1 { get; }
        AIAbility FireWallDotAttack1 { get; }
        AIAbility FireSnakeExplosion1 { get; }
        AIAbility FireTrapAttack1 { get; }
        AIAbility HealingAura1 { get; }
        AIAbility HealingAura2 { get; }
        AIAbility HealingAura3 { get; }
        AIAbility HealingAura4 { get; }
        AIAbility DruidHealingSanctuaryHeal { get; }
        AIAbility AcidAuraBall1 { get; }
        AIAbility AcidAuraBall2 { get; }
        AIAbility AcidAuraBall3 { get; }
        AIAbility AcidAuraBall4 { get; }
        AIAbility ElectricityAura1 { get; }
        AIAbility ElectricityAuraBolt1 { get; }
        AIAbility ReboundAura1 { get; }
        AIAbility ColdAuraBurst { get; }
        AIAbility WebStick { get; }
        AIAbility IcySlam { get; }
        AIAbility IcyCocoon { get; }
        AIAbility IcyCocoon2 { get; }
        AIAbility ElementalSlam { get; }
        AIAbility ElementalBees { get; }
        AIAbility ElementalBees2 { get; }
        AIAbility FaeLightningSmite { get; }
        AIAbility TotalHorrorAttack { get; }
        AIAbility TotalHorrorStretch { get; }
        AIAbility TotalHorrorHeal { get; }
        AIAbility TotalHorrorHeal2 { get; }
        AIAbility SheepBomb1 { get; }
        AIAbility SlugPoisonBite { get; }
        AIAbility SlugPoisonRage { get; }
        AIAbility SlugPoisonBite2 { get; }
        AIAbility SlugPoisonRage2 { get; }
        AIAbility SlugPoisonBite3 { get; }
        AIAbility SlugPoisonRage3 { get; }
        AIAbility TornadoJolt1 { get; }
        AIAbility TornadoFling { get; }
        AIAbility TornadoToss { get; }
        AIAbility TheFogCurse { get; }
        AIAbility MonsterWerewolfPouncingRake { get; }
        AIAbility MonsterWerewolfPackAttack { get; }
        AIAbility MonsterWerewolfHowl { get; }
        AIAbility Werewolf_Summon_Rage { get; }
        AIAbility Werewolf_Summon_Opener { get; }
        AIAbility BleddynHowl { get; }
        AIAbility OrcSwordSlash { get; }
        AIAbility OrcParry { get; }
        AIAbility OrcFinishingBlow { get; }
        AIAbility OrcHipThrow { get; }
        AIAbility OrcKneeKick { get; }
        AIAbility OrcPunch { get; }
        AIAbility OrcArrow1 { get; }
        AIAbility OrcArrow2 { get; }
        AIAbility OrcStaffSmash { get; }
        AIAbility OrcFireball { get; }
        AIAbility OrcHeal1 { get; }
        AIAbility OrcHeal2 { get; }
        AIAbility OrcEvasionBubble { get; }
        AIAbility OrcElectricStun { get; }
        AIAbility OrcFireBolts { get; }
        AIAbility OrcKnockbackBolt { get; }
        AIAbility OrcSummonUrak2 { get; }
        AIAbility OrcSwordSlashFire { get; }
        AIAbility OrcParryFire { get; }
        AIAbility OrcFinishingBlowFire { get; }
        AIAbility OrcSummonSigil1 { get; }
        AIAbility OrcSpearAttack { get; }
        AIAbility OrcHalberdAttack { get; }
        AIAbility OrcAreaHalberdAttack { get; }
        AIAbility OrcDebuffArrow { get; }
        AIAbility OrcSlice { get; }
        AIAbility OrcVenomstrike1 { get; }
        AIAbility OrcVenomstrike0 { get; }
        AIAbility OrcLieutenantDebuffTaunt { get; }
        AIAbility OrcAreaHalberdBoss { get; }
        AIAbility OrcDeathsHold { get; }
        AIAbility GazlukPriest1Special { get; }
        AIAbility GazlukPriest2Special { get; }
        AIAbility GazlukPriest3Special { get; }
        AIAbility OrcExtinguishLife { get; }
        AIAbility OrcDarknessBall { get; }
        AIAbility OrcWaveOfDarkness { get; }
        AIAbility EnemyMinigolemPunch { get; }
        AIAbility EnemyMinigolemHeal { get; }
        AIAbility EnemyMinigolemExplode { get; }
        AIAbility MinigolemBombToss { get; }
        AIAbility MinigolemBombToss2 { get; }
        AIAbility MinigolemBombToss3 { get; }
        AIAbility MinigolemBombToss4 { get; }
        AIAbility MinigolemBombToss5 { get; }
        AIAbility MinigolemAoEHeal { get; }
        AIAbility MinigolemAoEHeal2 { get; }
        AIAbility MinigolemAoEHeal3 { get; }
        AIAbility MinigolemAoEHeal4 { get; }
        AIAbility MinigolemAoEHeal5 { get; }
        AIAbility MinigolemSelfDestruct { get; }
        AIAbility MinigolemSelfDestruct2 { get; }
        AIAbility MinigolemSelfDestruct3 { get; }
        AIAbility MinigolemSelfDestruct4 { get; }
        AIAbility MinigolemSelfDestruct5 { get; }
        AIAbility MinigolemAoEPower { get; }
        AIAbility MinigolemAoEPower2 { get; }
        AIAbility MinigolemAoEPower3 { get; }
        AIAbility MinigolemAoEPower4 { get; }
        AIAbility MinigolemAoEPower5 { get; }
        AIAbility MinigolemHeal { get; }
        AIAbility MinigolemHeal2 { get; }
        AIAbility MinigolemHeal3 { get; }
        AIAbility MinigolemHeal4 { get; }
        AIAbility MinigolemHeal5 { get; }
        AIAbility MinigolemDoomAdmixture { get; }
        AIAbility MinigolemDoomAdmixture2 { get; }
        AIAbility MinigolemDoomAdmixture3 { get; }
        AIAbility MinigolemDoomAdmixture4 { get; }
        AIAbility MinigolemDoomAdmixture5 { get; }
        AIAbility MinigolemSelfSacrifice { get; }
        AIAbility MinigolemSelfSacrifice2 { get; }
        AIAbility MinigolemSelfSacrifice3 { get; }
        AIAbility MinigolemSelfSacrifice4 { get; }
        AIAbility MinigolemSelfSacrifice5 { get; }
        AIAbility MinigolemPunch { get; }
        AIAbility MinigolemPunch2 { get; }
        AIAbility MinigolemPunch3 { get; }
        AIAbility MinigolemPunch4 { get; }
        AIAbility MinigolemPunch5 { get; }
        AIAbility MinigolemHasteConcoction1 { get; }
        AIAbility MinigolemHasteConcoction2 { get; }
        AIAbility MinigolemHasteConcoction3 { get; }
        AIAbility MinigolemFireBalm1 { get; }
        AIAbility MinigolemFireBalm2 { get; }
        AIAbility MinigolemFireBalm3 { get; }
        AIAbility MinigolemFireBalm4 { get; }
        AIAbility MinigolemFireBalm5 { get; }
        AIAbility MinigolemRageAoEHeal1 { get; }
        AIAbility MinigolemRageAoEHeal2 { get; }
        AIAbility MinigolemRageAoEHeal3 { get; }
        AIAbility MinigolemRageAoEHeal4 { get; }
        AIAbility MinigolemRageAoEHeal5 { get; }
        AIAbility MinigolemRageAcidToss1 { get; }
        AIAbility MinigolemRageAcidToss2 { get; }
        AIAbility MinigolemRageAcidToss3 { get; }
        AIAbility MinigolemRageAcidToss4 { get; }
        AIAbility MinigolemRageAcidToss5 { get; }
        AIAbility TrainingGolemPunch { get; }
        AIAbility TrainingGolemStun { get; }
        AIAbility TrainingGolemHeal { get; }
        AIAbility TrainingGolemHealB { get; }
        AIAbility TrainingGolemFireBreath { get; }
        AIAbility TrainingGolemFireBurst { get; }
        AIAbility GrimalkinClaw { get; }
        AIAbility GrimalkinBite { get; }
        AIAbility GrimalkinPuncture { get; }
        AIAbility WerewolfSword1 { get; }
        AIAbility WerewolfSword2 { get; }
        AIAbility WerewolfSwordStun { get; }
        AIAbility WerewolfArrow1 { get; }
        AIAbility WerewolfArrow2 { get; }
        AIAbility WerewolfOmegaArrow { get; }
        AIAbility NpcSmash { get; }
        AIAbility NpcDoubleHitCurse { get; }
        AIAbility NpcBlockingStance { get; }
        AIAbility NpcHeadcracker { get; }
        AIAbility StrigaClawA { get; }
        AIAbility StrigaClawB { get; }
        AIAbility StrigaReap { get; }
        AIAbility StrigaReap2 { get; }
        AIAbility StrigaFireBreath { get; }
        AIAbility StrigaBuff { get; }
        AIAbility GhostlyPunchA { get; }
        AIAbility GhostlyPunchB { get; }
        AIAbility GhostlyBurst { get; }
        AIAbility GhostlyBossPunchA { get; }
        AIAbility GhostlyBossPunchB { get; }
        AIAbility GhostlyBossBurst { get; }
        AIAbility GhostlyBolt { get; }
        AIAbility InjectorBugBite { get; }
        AIAbility InjectorBugInject { get; }
        AIAbility InjectorBugInject2 { get; }
        AIAbility FaceOfDeathKill { get; }
        AIAbility WatcherFireball { get; }
        AIAbility WatcherSlap { get; }
        AIAbility WatcherAcidball { get; }
        AIAbility RedCrystalBlast { get; }
        AIAbility RedCrystalBurst { get; }
        AIAbility TurretCrystalZap { get; }
        AIAbility TurretCrystalZap2 { get; }
        AIAbility TurretCrystalZapLongRange { get; }
        AIAbility TurretCrystalZapLongRange2 { get; }
        AIAbility DeathRay { get; }
        AIAbility SpyPortalZap { get; }
        AIAbility SpyPortalZap2 { get; }
        AIAbility BitingVineBite { get; }
        AIAbility BitingVineSpit { get; }
        AIAbility BitingVineSpitB { get; }
        AIAbility BitingVineCast { get; }
        AIAbility BitingVineAppear { get; }
        AIAbility BitingVineDisappear { get; }
        AIAbility TrollClubA { get; }
        AIAbility TrollClubB { get; }
        AIAbility TrollKnockdown { get; }
        AIAbility OgreClubA { get; }
        AIAbility OgreClubB { get; }
        AIAbility OgreThrow { get; }
        AIAbility OgreStun { get; }
        AIAbility FaeSwordA { get; }
        AIAbility FaeSwordB { get; }
        AIAbility FaeSwordKill { get; }
        AIAbility DementiaPuckCurse { get; }
        AIAbility FaeLightningSmiteHidden { get; }
        AIAbility NecroSpark { get; }
        AIAbility NecroDarknessWave { get; }
        AIAbility NecroPainBubble { get; }
        AIAbility NecroSparkPerching { get; }
        AIAbility NecroDeathsHold { get; }
        AIAbility DroachBiteA { get; }
        AIAbility DroachBiteB { get; }
        AIAbility DroachFireball { get; }
        AIAbility DroachFireballPerching { get; }
        AIAbility DroachBreatheFire { get; }
        AIAbility DroachLightning { get; }
        AIAbility DroachLightningPerching { get; }
        AIAbility DroachShockingKnockback { get; }
        AIAbility BasiliskClawA { get; }
        AIAbility BasiliskClawB { get; }
        AIAbility BasiliskToxicBite { get; }
        AIAbility BasiliskDebuff { get; }
        AIAbility BasiliskCastPerching { get; }
        AIAbility CultistArrow1 { get; }
        AIAbility CultistArrow2 { get; }
        AIAbility CultistOmegaArrow { get; }
        AIAbility CultistSword1 { get; }
        AIAbility CultistSword2 { get; }
        AIAbility CultistSwordStun { get; }
        AIAbility BossMegaSword1 { get; }
        AIAbility BossMegaSword2 { get; }
        AIAbility SedgewickMegaSwordAngry { get; }
        AIAbility BossMegaHammer { get; }
        AIAbility BossMegaHammer2 { get; }
        AIAbility BossMegaRageHammer { get; }
        AIAbility ClaudiaTundraSpikes { get; }
        AIAbility ClaudiaIceSpear { get; }
        AIAbility ClaudiaBlizzard { get; }
        AIAbility BigGolemHitA { get; }
        AIAbility BigGolemHitB { get; }
        AIAbility BigGolemFlingBoss { get; }
        AIAbility BigGolemPerchFix { get; }
        AIAbility BigGolemFlingBoss2 { get; }
        AIAbility BigGolemSummonFireSnake { get; }
        AIAbility BigGolemHitB_NoDisable { get; }
        AIAbility BigGolemHitA_NoDisable { get; }
        AIAbility BigGolemFling { get; }
        AIAbility GhoulClawA { get; }
        AIAbility GhoulClawB { get; }
        AIAbility GhoulSelfBuff { get; }
        AIAbility GhoulHammerA { get; }
        AIAbility GhoulHammerB { get; }
        AIAbility DragonWormSpitElectricity { get; }
        AIAbility DragonWormBite { get; }
        AIAbility DragonWormSmack { get; }
        AIAbility DragonWormRage { get; }
        AIAbility DragonWormEscape { get; }
        AIAbility DragonWormSpitFire { get; }
        AIAbility ColdSphereBurst { get; }
        AIAbility ColdSphereFreezeBurst { get; }
        AIAbility ManticoreBite { get; }
        AIAbility ManticoreClaw { get; }
        AIAbility ManticoreSting1 { get; }
        AIAbility Manticoresting2 { get; }
        AIAbility RakStaffHit { get; }
        AIAbility RakStaffPin { get; }
        AIAbility RakStaffBlock { get; }
        AIAbility RakStaffHeavy { get; }
        AIAbility RakSlash { get; }
        AIAbility RakKnee { get; }
        AIAbility RakKick { get; }
        AIAbility RakBarrage { get; }
        AIAbility RakSwordSlash { get; }
        AIAbility RakHackingBlade { get; }
        AIAbility RakDecapitate { get; }
        AIAbility RakFireball { get; }
        AIAbility RakBreatheFire { get; }
        AIAbility RakRingOfFire { get; }
        AIAbility RakToxinBomb { get; }
        AIAbility RakAcidBomb { get; }
        AIAbility RakHealingMist { get; }
        AIAbility RakBasicShot { get; }
        AIAbility RakHookShot { get; }
        AIAbility RakBowBash { get; }
        AIAbility RakAimedShot { get; }
        AIAbility RakPoisonArrow { get; }
        AIAbility RakMindreave { get; }
        AIAbility RakPainBubble { get; }
        AIAbility RakPanicCharge { get; }
        AIAbility RakRevitalize { get; }
        AIAbility RakReconstruct { get; }
        AIAbility RakBossSlow { get; }
        AIAbility RakBossPerchSlow { get; }
        AIAbility FlapSkullBite { get; }
        AIAbility FlapSkullBigBite { get; }
        AIAbility MinotaurClub { get; }
        AIAbility MinotaurRageClub { get; }
        AIAbility MinotaurBoulder { get; }
        AIAbility MinotaurBossRageClub { get; }
        AIAbility CockatricePeck { get; }
        AIAbility CockatriceTailWhip { get; }
        AIAbility CockatriceParalyze { get; }
        AIAbility GiantBeetleBite { get; }
        AIAbility GiantBeetleInject { get; }
        AIAbility GiantBeetleBoulderSpit { get; }
        AIAbility BatIllusionSlashA { get; }
        AIAbility BatIllusionSlashB { get; }
        AIAbility BatIllusionBite { get; }
        AIAbility GiantBatSlashA { get; }
        AIAbility GiantBatSlashB { get; }
        AIAbility GiantBatBite { get; }
        AIAbility HagAgingTouch { get; }
        AIAbility HagAgingScream { get; }
        AIAbility TriffidClawA { get; }
        AIAbility TriffidClawB { get; }
        AIAbility TriffidTongue { get; }
        AIAbility TriffidSpore { get; }
        AIAbility TriffidShot { get; }
        AIAbility TriffidTongueElite { get; }
        AIAbility GiantScorpionClawA { get; }
        AIAbility GiantScorpionClawB { get; }
        AIAbility GiantScorpionSting { get; }
        AIAbility KrakenBeak { get; }
        AIAbility KrakenSlam { get; }
        AIAbility KrakenRage { get; }
        AIAbility KrakenBabyBeak { get; }
        AIAbility KrakenBabySlam { get; }
        AIAbility KrakenBabyRage { get; }
        AIAbility RanalonHit { get; }
        AIAbility RanalonHitB { get; }
        AIAbility RanalonKick { get; }
        AIAbility RanalonTongue { get; }
        AIAbility RanalonZap { get; }
        AIAbility RanalonZapB { get; }
        AIAbility RanalonHeal { get; }
        AIAbility RanalonRoot { get; }
        AIAbility RanalonSelfBuff { get; }
        AIAbility RanalonSelfBuffElite { get; }
        AIAbility RanalonGuardianStab { get; }
        AIAbility RanalonGuardianStabB { get; }
        AIAbility RanalonGuardianBite { get; }
        AIAbility RanalonGuardianBlind { get; }
        AIAbility RanalonDoctrineKeeperStab { get; }
        AIAbility RanalonDoctrineKeeperBlind { get; }
        AIAbility BarghestBiteA { get; }
        AIAbility BarghestBiteB { get; }
        AIAbility BarghestDebuff { get; }
        AIAbility WorghestDebuff { get; }
        AIAbility BallistaFire { get; }
        AIAbility BallistaFire_Long { get; }
        AIAbility GargoyleSlamA { get; }
        AIAbility GargoyleSlamB { get; }
        AIAbility GargoyleStun { get; }
        AIAbility GargoyleBossStun { get; }
        AIAbility ScrayBite { get; }
        AIAbility ScrayStab { get; }
        AIAbility HippoBite { get; }
        AIAbility HippoBiteAndHeal1 { get; }
        AIAbility BigCatClaw_Pet { get; }
        AIAbility BigCatPounce_Pet { get; }
        AIAbility BigCatKill_Pet1 { get; }
        AIAbility BigCatKill_Pet2 { get; }
        AIAbility BigCatKill_Pet3 { get; }
        AIAbility BigCatKill_Pet4 { get; }
        AIAbility BigCatKill_Pet5 { get; }
        AIAbility BigCatKill_Pet6 { get; }
        AIAbility BigCatUltraKill_Pet1 { get; }
        AIAbility BigCatUltraKill_Pet2 { get; }
        AIAbility BigCatUltraKill_Pet3 { get; }
        AIAbility BigCatUltraKill_Pet4 { get; }
        AIAbility BigCatUltraKill_Pet5 { get; }
        AIAbility BigCatUltraKill_Pet6 { get; }
        AIAbility BigCatRoot_Pet1 { get; }
        AIAbility BigCatRoot_Pet2 { get; }
        AIAbility BigCatRoot_Pet3 { get; }
        AIAbility BigCatRoot_Pet4 { get; }
        AIAbility BigCatVuln_Pet1 { get; }
        AIAbility BigCatVuln_Pet2 { get; }
        AIAbility BigCatVuln_Pet3 { get; }
        AIAbility BigCatVuln_Pet4 { get; }
        AIAbility BigCatHeal_Pet1 { get; }
        AIAbility BigCatHeal_Pet2 { get; }
        AIAbility BigCatHeal_Pet3 { get; }
        AIAbility BigCatHeal_Pet4 { get; }
        AIAbility BigCatHeal_Pet5 { get; }
        AIAbility BigCatHeal_Pet6 { get; }
        AIAbility GrimalkinPuncture_Pet1 { get; }
        AIAbility GrimalkinPuncture_Pet2 { get; }
        AIAbility GrimalkinPuncture_Pet3 { get; }
        AIAbility GrimalkinPuncture_Pet4 { get; }
        AIAbility GrimalkinPuncture_Pet5 { get; }
        AIAbility GrimalkinPuncture_Pet6 { get; }
        AIAbility GrimalkinFlee_Pet1 { get; }
        AIAbility GrimalkinFlee_Pet2 { get; }
        AIAbility GrimalkinFlee_Pet3 { get; }
        AIAbility RatBite_Pet { get; }
        AIAbility RatClaw_Pet { get; }
        AIAbility RatDeRage_Pet1 { get; }
        AIAbility RatDeRage_Pet2 { get; }
        AIAbility RatDeRage_Pet3 { get; }
        AIAbility RatDeRage_Pet4 { get; }
        AIAbility RatDeRage_Pet5 { get; }
        AIAbility RatDeRage_Pet6 { get; }
        AIAbility RatHeal_Pet1 { get; }
        AIAbility RatHeal_Pet2 { get; }
        AIAbility RatHeal_Pet3 { get; }
        AIAbility RatHeal_Pet4 { get; }
        AIAbility RatHeal_Pet5 { get; }
        AIAbility RatHeal_Pet6 { get; }
        AIAbility RatVuln_Pet1 { get; }
        AIAbility RatVuln_Pet2 { get; }
        AIAbility RatVuln_Pet3 { get; }
        AIAbility RatVuln_Pet4 { get; }
        AIAbility FireRatBite_Pet { get; }
        AIAbility FireRatClaw_Pet { get; }
        AIAbility RatBurn_Pet1 { get; }
        AIAbility RatBurn_Pet2 { get; }
        AIAbility RatBurn_Pet3 { get; }
        AIAbility RatBurn_Pet4 { get; }
        AIAbility RatBurn_Pet5 { get; }
        AIAbility RatBurn_Pet6 { get; }
        AIAbility BearBite_Pet { get; }
        AIAbility BearClaw_Pet { get; }
        AIAbility BearTaunt_Pet1 { get; }
        AIAbility BearTaunt_Pet2 { get; }
        AIAbility BearTaunt_Pet3 { get; }
        AIAbility BearTaunt_Pet4 { get; }
        AIAbility BearTaunt_Pet5 { get; }
        AIAbility BearTaunt_Pet6 { get; }
        AIAbility BearStun_Pet1 { get; }
        AIAbility BearStun_Pet2 { get; }
        AIAbility BearStun_Pet3 { get; }
        AIAbility BearStun_Pet4 { get; }
        AIAbility BearWarmth_Pet1 { get; }
        AIAbility BearWarmth_Pet2 { get; }
        AIAbility BearWarmth_Pet3 { get; }
        AIAbility BearWarmth_Pet4 { get; }
        AIAbility BearWarmth_Pet5 { get; }
        AIAbility BearWarmth_Pet6 { get; }
        AIAbility BearSelfHeal_Pet1 { get; }
        AIAbility BearSelfHeal_Pet2 { get; }
        AIAbility BearSelfHeal_Pet3 { get; }
        AIAbility BearSelfHeal_Pet4 { get; }
        AIAbility BearSelfHeal_Pet5 { get; }
        AIAbility BearSelfHeal_Pet6 { get; }
        AIAbility BearUltra_Pet1 { get; }
        AIAbility BearUltra_Pet2 { get; }
        AIAbility BearUltra_Pet3 { get; }
        AIAbility BearUltra_Pet4 { get; }
        AIAbility BearUltra_Pet5 { get; }
        AIAbility BearUltra_Pet6 { get; }
    }
}
