namespace PgJsonObjects
{
    public interface IPgAIAbilitySet
    {
        IPgAIAbility AnimalBite { get; }
        IPgAIAbility AnimalClaw { get; }
        IPgAIAbility AnimalOmegaBite { get; }
        IPgAIAbility AnimalOmegaBite2 { get; }
        IPgAIAbility AnimalHoofFrontKick { get; }
        IPgAIAbility AnimalHoofRageKick { get; }
        IPgAIAbility AnimalHoofRageKick2 { get; }
        IPgAIAbility AnimalHoofFieryFrontKick { get; }
        IPgAIAbility AnimalHoofFieryFrontKick2 { get; }
        IPgAIAbility ElectricPigHitAndRun { get; }
        IPgAIAbility ElectricPigStun { get; }
        IPgAIAbility ElectricPigAoEStun { get; }
        IPgAIAbility LamiaMindControl { get; }
        IPgAIAbility LamiaRage { get; }
        IPgAIAbility SlimeKick { get; }
        IPgAIAbility SlimeKickB { get; }
        IPgAIAbility SlimeBite { get; }
        IPgAIAbility SlimeBiteB { get; }
        IPgAIAbility Slime_SummonSlime { get; }
        IPgAIAbility SlimeSpit { get; }
        IPgAIAbility SlimeSuperSpit { get; }
        IPgAIAbility IceSlimeKick { get; }
        IPgAIAbility IceSlimeKickB { get; }
        IPgAIAbility IceSlimeBite { get; }
        IPgAIAbility IceSlimeBiteB { get; }
        IPgAIAbility BossSlimeKick { get; }
        IPgAIAbility BossSlimeKickB { get; }
        IPgAIAbility BossSlime_SummonSlime1 { get; }
        IPgAIAbility BossSlimeKick2 { get; }
        IPgAIAbility BossSlimeKick2B { get; }
        IPgAIAbility BossSlime_SummonSlime4Elite { get; }
        IPgAIAbility AnimalHeal { get; }
        IPgAIAbility AnimalHeal2 { get; }
        IPgAIAbility AnimalHeal3 { get; }
        IPgAIAbility IceCockPeck { get; }
        IPgAIAbility IceCockFreeze { get; }
        IPgAIAbility NightmareHoof { get; }
        IPgAIAbility NightmareDarknessBomb { get; }
        IPgAIAbility CiervosNightmareHoof { get; }
        IPgAIAbility CiervosDarknessBomb { get; }
        IPgAIAbility Myconian_Bash { get; }
        IPgAIAbility Myconian_Mindspores { get; }
        IPgAIAbility Myconian_Drain { get; }
        IPgAIAbility Myconian_BossBash { get; }
        IPgAIAbility Myconian_Mindspores_Permanent { get; }
        IPgAIAbility Myconian_TidalCurse { get; }
        IPgAIAbility Myconian_Shock { get; }
        IPgAIAbility AlienDog_Punch { get; }
        IPgAIAbility AlienDog_Punch2 { get; }
        IPgAIAbility AlienDog_RagePunch { get; }
        IPgAIAbility MushroomMonster_Bite { get; }
        IPgAIAbility MushroomMonster_Spit1 { get; }
        IPgAIAbility MushroomMonster_Spit2 { get; }
        IPgAIAbility MushroomMonster_SummonMushroomSpawn1 { get; }
        IPgAIAbility MushroomMonster_SummonMushroomSpawn2 { get; }
        IPgAIAbility MushroomMonster_SummonMushroomSpawn3 { get; }
        IPgAIAbility MushroomMonster_SpawnSpit1 { get; }
        IPgAIAbility MushroomMonster_SpawnSpit2 { get; }
        IPgAIAbility MushroomMonster_SpawnSuperSpit1 { get; }
        IPgAIAbility MushroomMonster_SpawnSuperSpit2 { get; }
        IPgAIAbility MaronesaStomp { get; }
        IPgAIAbility MaronesaInfect { get; }
        IPgAIAbility WormBite1 { get; }
        IPgAIAbility WormSpit1 { get; }
        IPgAIAbility WormShove1 { get; }
        IPgAIAbility WormInfect1 { get; }
        IPgAIAbility WormSpit2 { get; }
        IPgAIAbility WormBossSpit { get; }
        IPgAIAbility WormBossAcidBurst { get; }
        IPgAIAbility GnasherBite { get; }
        IPgAIAbility GnasherRend { get; }
        IPgAIAbility Dinoslash { get; }
        IPgAIAbility Dinoslash2 { get; }
        IPgAIAbility Dinobite { get; }
        IPgAIAbility Dinobite2 { get; }
        IPgAIAbility Dinowhap { get; }
        IPgAIAbility Peck { get; }
        IPgAIAbility AnimalFlee { get; }
        IPgAIAbility HippogriffPeck { get; }
        IPgAIAbility HippogriffSlashes { get; }
        IPgAIAbility HippogriffBossSlashes { get; }
        IPgAIAbility RatBite { get; }
        IPgAIAbility RatClaw { get; }
        IPgAIAbility FireRatBite { get; }
        IPgAIAbility FireRatClaw { get; }
        IPgAIAbility GoblinZapBall { get; }
        IPgAIAbility GoblinHateZapBall { get; }
        IPgAIAbility GoblinHateZapBall2 { get; }
        IPgAIAbility RhinoHorn { get; }
        IPgAIAbility RhinoRage { get; }
        IPgAIAbility RhinoFireball { get; }
        IPgAIAbility RhinoBossRage { get; }
        IPgAIAbility YetiPunch { get; }
        IPgAIAbility YetiEncase { get; }
        IPgAIAbility YetiDebuff { get; }
        IPgAIAbility YetiBoulderThrow { get; }
        IPgAIAbility YetiBarrage { get; }
        IPgAIAbility YetiRoarStun { get; }
        IPgAIAbility YetiFlingAway { get; }
        IPgAIAbility YetiIceBallThrow { get; }
        IPgAIAbility YetiIceSpear { get; }
        IPgAIAbility YetiColdOrb { get; }
        IPgAIAbility YetiFrostRing { get; }
        IPgAIAbility WorgBite { get; }
        IPgAIAbility WorgOmegaBite { get; }
        IPgAIAbility BearBite { get; }
        IPgAIAbility BearCrush { get; }
        IPgAIAbility BrainBite { get; }
        IPgAIAbility BrainDrain { get; }
        IPgAIAbility BrainDrain2 { get; }
        IPgAIAbility BigCatClaw { get; }
        IPgAIAbility BigCatPounce { get; }
        IPgAIAbility BigCatRagePounce { get; }
        IPgAIAbility BigCatDebuff { get; }
        IPgAIAbility SpiderBite { get; }
        IPgAIAbility SpiderFireball { get; }
        IPgAIAbility SpiderBossFreePin { get; }
        IPgAIAbility SpiderKill2 { get; }
        IPgAIAbility SpiderInject { get; }
        IPgAIAbility SpiderKill { get; }
        IPgAIAbility AcidBall1 { get; }
        IPgAIAbility SpiderPin { get; }
        IPgAIAbility SpiderKill3 { get; }
        IPgAIAbility AcidBall2 { get; }
        IPgAIAbility AcidSpew1 { get; }
        IPgAIAbility AcidExplosion1 { get; }
        IPgAIAbility AcidExplosion2 { get; }
        IPgAIAbility SpiderIncubate { get; }
        IPgAIAbility MantisClaw { get; }
        IPgAIAbility MantisRage { get; }
        IPgAIAbility MantisAcidBurst { get; }
        IPgAIAbility SherzatClaw { get; }
        IPgAIAbility SherzatAcidSpit { get; }
        IPgAIAbility SherzatDisintegrate { get; }
        IPgAIAbility MantisSwipe { get; }
        IPgAIAbility MantisBlast { get; }
        IPgAIAbility SnailStrike { get; }
        IPgAIAbility SnailRage { get; }
        IPgAIAbility SnailRageB { get; }
        IPgAIAbility SnailRageC { get; }
        IPgAIAbility HookClaw { get; }
        IPgAIAbility HookAcid { get; }
        IPgAIAbility HookRage { get; }
        IPgAIAbility UndeadSword1 { get; }
        IPgAIAbility UndeadSword2 { get; }
        IPgAIAbility UndeadSwordAngry { get; }
        IPgAIAbility UndeadMegaSword1 { get; }
        IPgAIAbility UndeadMegaSword2 { get; }
        IPgAIAbility UndeadMegaSwordAngry { get; }
        IPgAIAbility UndeadLightningSmite { get; }
        IPgAIAbility UndeadPhysicalShield { get; }
        IPgAIAbility UndeadSword1B { get; }
        IPgAIAbility UndeadFireballA { get; }
        IPgAIAbility UndeadFireballB { get; }
        IPgAIAbility UndeadFireballB2 { get; }
        IPgAIAbility UndeadIceBall1 { get; }
        IPgAIAbility UndeadFreezeBall { get; }
        IPgAIAbility UndeadFireballLongA { get; }
        IPgAIAbility UndeadFireballLongB { get; }
        IPgAIAbility UndeadFireballLongB2 { get; }
        IPgAIAbility KhyrulekCurseBall { get; }
        IPgAIAbility UrsulaFireball1 { get; }
        IPgAIAbility UrsulaFireball1B { get; }
        IPgAIAbility UrsulaFireball2 { get; }
        IPgAIAbility UrsulaIceball1 { get; }
        IPgAIAbility UrsulaIceball1B { get; }
        IPgAIAbility UrsulaIceball2 { get; }
        IPgAIAbility UrsulaSummon { get; }
        IPgAIAbility UrsulaRage { get; }
        IPgAIAbility UndeadFireballA2 { get; }
        IPgAIAbility BigHeadCurseball { get; }
        IPgAIAbility UndeadArrow1 { get; }
        IPgAIAbility UndeadArrow2 { get; }
        IPgAIAbility UndeadOmegaArrow { get; }
        IPgAIAbility PetUndeadArrow1 { get; }
        IPgAIAbility PetUndeadArrow2 { get; }
        IPgAIAbility PetUndeadOmegaArrow { get; }
        IPgAIAbility UndeadGrappleArrow1 { get; }
        IPgAIAbility UndeadSelfDestruct { get; }
        IPgAIAbility UndeadDarknessBall { get; }
        IPgAIAbility UndeadBoneWhirlwind { get; }
        IPgAIAbility PetUndeadSword1 { get; }
        IPgAIAbility PetUndeadSword2 { get; }
        IPgAIAbility PetUndeadSwordAngry { get; }
        IPgAIAbility PetUndeadFireballA { get; }
        IPgAIAbility PetUndeadFireballB { get; }
        IPgAIAbility PetUndeadDefensiveBurst { get; }
        IPgAIAbility PetUndeadPunch1 { get; }
        IPgAIAbility ZombiePunch { get; }
        IPgAIAbility ZombieBite { get; }
        IPgAIAbility GoblinSpear1 { get; }
        IPgAIAbility GoblinSpear2 { get; }
        IPgAIAbility GoblinRageSpear1 { get; }
        IPgAIAbility GoblinRageSpear2 { get; }
        IPgAIAbility GoblinHeal1 { get; }
        IPgAIAbility GoblinHeal2 { get; }
        IPgAIAbility GoblinPunch { get; }
        IPgAIAbility GoblinArrow1 { get; }
        IPgAIAbility GoblinArrow2 { get; }
        IPgAIAbility GoblinRageArrow1 { get; }
        IPgAIAbility GoblinRageArrow2 { get; }
        IPgAIAbility GoblinSpreadZapBall { get; }
        IPgAIAbility GoblinBossLightning { get; }
        IPgAIAbility GoblinArmorBuff { get; }
        IPgAIAbility MummySlamA { get; }
        IPgAIAbility MummySlamB { get; }
        IPgAIAbility MummySlamCombo { get; }
        IPgAIAbility MummyWrapA { get; }
        IPgAIAbility MummyWrapB { get; }
        IPgAIAbility MummyWrapRage { get; }
        IPgAIAbility BarutiWrapA { get; }
        IPgAIAbility BarutiWrapB { get; }
        IPgAIAbility BarutiWrapRage { get; }
        IPgAIAbility FireWallAttack1 { get; }
        IPgAIAbility FireWallDotAttack1 { get; }
        IPgAIAbility FireSnakeExplosion1 { get; }
        IPgAIAbility FireTrapAttack1 { get; }
        IPgAIAbility HealingAura1 { get; }
        IPgAIAbility HealingAura2 { get; }
        IPgAIAbility HealingAura3 { get; }
        IPgAIAbility HealingAura4 { get; }
        IPgAIAbility DruidHealingSanctuaryHeal { get; }
        IPgAIAbility AcidAuraBall1 { get; }
        IPgAIAbility AcidAuraBall2 { get; }
        IPgAIAbility AcidAuraBall3 { get; }
        IPgAIAbility AcidAuraBall4 { get; }
        IPgAIAbility ElectricityAura1 { get; }
        IPgAIAbility ElectricityAuraBolt1 { get; }
        IPgAIAbility ReboundAura1 { get; }
        IPgAIAbility ColdAuraBurst { get; }
        IPgAIAbility WebStick { get; }
        IPgAIAbility IcySlam { get; }
        IPgAIAbility IcyCocoon { get; }
        IPgAIAbility IcyCocoon2 { get; }
        IPgAIAbility ElementalSlam { get; }
        IPgAIAbility ElementalBees { get; }
        IPgAIAbility ElementalBees2 { get; }
        IPgAIAbility FaeLightningSmite { get; }
        IPgAIAbility TotalHorrorAttack { get; }
        IPgAIAbility TotalHorrorStretch { get; }
        IPgAIAbility TotalHorrorHeal { get; }
        IPgAIAbility TotalHorrorHeal2 { get; }
        IPgAIAbility SheepBomb1 { get; }
        IPgAIAbility SlugPoisonBite { get; }
        IPgAIAbility SlugPoisonRage { get; }
        IPgAIAbility SlugPoisonBite2 { get; }
        IPgAIAbility SlugPoisonRage2 { get; }
        IPgAIAbility SlugPoisonBite3 { get; }
        IPgAIAbility SlugPoisonRage3 { get; }
        IPgAIAbility TornadoJolt1 { get; }
        IPgAIAbility TornadoFling { get; }
        IPgAIAbility TornadoToss { get; }
        IPgAIAbility TheFogCurse { get; }
        IPgAIAbility MonsterWerewolfPouncingRake { get; }
        IPgAIAbility MonsterWerewolfPackAttack { get; }
        IPgAIAbility MonsterWerewolfHowl { get; }
        IPgAIAbility Werewolf_Summon_Rage { get; }
        IPgAIAbility Werewolf_Summon_Opener { get; }
        IPgAIAbility BleddynHowl { get; }
        IPgAIAbility OrcSwordSlash { get; }
        IPgAIAbility OrcParry { get; }
        IPgAIAbility OrcFinishingBlow { get; }
        IPgAIAbility OrcHipThrow { get; }
        IPgAIAbility OrcKneeKick { get; }
        IPgAIAbility OrcPunch { get; }
        IPgAIAbility OrcArrow1 { get; }
        IPgAIAbility OrcArrow2 { get; }
        IPgAIAbility OrcStaffSmash { get; }
        IPgAIAbility OrcFireball { get; }
        IPgAIAbility OrcHeal1 { get; }
        IPgAIAbility OrcHeal2 { get; }
        IPgAIAbility OrcEvasionBubble { get; }
        IPgAIAbility OrcElectricStun { get; }
        IPgAIAbility OrcFireBolts { get; }
        IPgAIAbility OrcKnockbackBolt { get; }
        IPgAIAbility OrcSummonUrak2 { get; }
        IPgAIAbility OrcSwordSlashFire { get; }
        IPgAIAbility OrcParryFire { get; }
        IPgAIAbility OrcFinishingBlowFire { get; }
        IPgAIAbility OrcSummonSigil1 { get; }
        IPgAIAbility OrcSpearAttack { get; }
        IPgAIAbility OrcHalberdAttack { get; }
        IPgAIAbility OrcAreaHalberdAttack { get; }
        IPgAIAbility OrcDebuffArrow { get; }
        IPgAIAbility OrcSlice { get; }
        IPgAIAbility OrcVenomstrike1 { get; }
        IPgAIAbility OrcVenomstrike0 { get; }
        IPgAIAbility OrcLieutenantDebuffTaunt { get; }
        IPgAIAbility OrcAreaHalberdBoss { get; }
        IPgAIAbility OrcDeathsHold { get; }
        IPgAIAbility GazlukPriest1Special { get; }
        IPgAIAbility GazlukPriest2Special { get; }
        IPgAIAbility GazlukPriest3Special { get; }
        IPgAIAbility OrcExtinguishLife { get; }
        IPgAIAbility OrcDarknessBall { get; }
        IPgAIAbility OrcWaveOfDarkness { get; }
        IPgAIAbility EnemyMinigolemPunch { get; }
        IPgAIAbility EnemyMinigolemHeal { get; }
        IPgAIAbility EnemyMinigolemExplode { get; }
        IPgAIAbility MinigolemBombToss { get; }
        IPgAIAbility MinigolemBombToss2 { get; }
        IPgAIAbility MinigolemBombToss3 { get; }
        IPgAIAbility MinigolemBombToss4 { get; }
        IPgAIAbility MinigolemBombToss5 { get; }
        IPgAIAbility MinigolemAoEHeal { get; }
        IPgAIAbility MinigolemAoEHeal2 { get; }
        IPgAIAbility MinigolemAoEHeal3 { get; }
        IPgAIAbility MinigolemAoEHeal4 { get; }
        IPgAIAbility MinigolemAoEHeal5 { get; }
        IPgAIAbility MinigolemSelfDestruct { get; }
        IPgAIAbility MinigolemSelfDestruct2 { get; }
        IPgAIAbility MinigolemSelfDestruct3 { get; }
        IPgAIAbility MinigolemSelfDestruct4 { get; }
        IPgAIAbility MinigolemSelfDestruct5 { get; }
        IPgAIAbility MinigolemAoEPower { get; }
        IPgAIAbility MinigolemAoEPower2 { get; }
        IPgAIAbility MinigolemAoEPower3 { get; }
        IPgAIAbility MinigolemAoEPower4 { get; }
        IPgAIAbility MinigolemAoEPower5 { get; }
        IPgAIAbility MinigolemHeal { get; }
        IPgAIAbility MinigolemHeal2 { get; }
        IPgAIAbility MinigolemHeal3 { get; }
        IPgAIAbility MinigolemHeal4 { get; }
        IPgAIAbility MinigolemHeal5 { get; }
        IPgAIAbility MinigolemDoomAdmixture { get; }
        IPgAIAbility MinigolemDoomAdmixture2 { get; }
        IPgAIAbility MinigolemDoomAdmixture3 { get; }
        IPgAIAbility MinigolemDoomAdmixture4 { get; }
        IPgAIAbility MinigolemDoomAdmixture5 { get; }
        IPgAIAbility MinigolemSelfSacrifice { get; }
        IPgAIAbility MinigolemSelfSacrifice2 { get; }
        IPgAIAbility MinigolemSelfSacrifice3 { get; }
        IPgAIAbility MinigolemSelfSacrifice4 { get; }
        IPgAIAbility MinigolemSelfSacrifice5 { get; }
        IPgAIAbility MinigolemPunch { get; }
        IPgAIAbility MinigolemPunch2 { get; }
        IPgAIAbility MinigolemPunch3 { get; }
        IPgAIAbility MinigolemPunch4 { get; }
        IPgAIAbility MinigolemPunch5 { get; }
        IPgAIAbility MinigolemHasteConcoction1 { get; }
        IPgAIAbility MinigolemHasteConcoction2 { get; }
        IPgAIAbility MinigolemHasteConcoction3 { get; }
        IPgAIAbility MinigolemFireBalm1 { get; }
        IPgAIAbility MinigolemFireBalm2 { get; }
        IPgAIAbility MinigolemFireBalm3 { get; }
        IPgAIAbility MinigolemFireBalm4 { get; }
        IPgAIAbility MinigolemFireBalm5 { get; }
        IPgAIAbility MinigolemRageAoEHeal1 { get; }
        IPgAIAbility MinigolemRageAoEHeal2 { get; }
        IPgAIAbility MinigolemRageAoEHeal3 { get; }
        IPgAIAbility MinigolemRageAoEHeal4 { get; }
        IPgAIAbility MinigolemRageAoEHeal5 { get; }
        IPgAIAbility MinigolemRageAcidToss1 { get; }
        IPgAIAbility MinigolemRageAcidToss2 { get; }
        IPgAIAbility MinigolemRageAcidToss3 { get; }
        IPgAIAbility MinigolemRageAcidToss4 { get; }
        IPgAIAbility MinigolemRageAcidToss5 { get; }
        IPgAIAbility TrainingGolemPunch { get; }
        IPgAIAbility TrainingGolemStun { get; }
        IPgAIAbility TrainingGolemHeal { get; }
        IPgAIAbility TrainingGolemHealB { get; }
        IPgAIAbility TrainingGolemFireBreath { get; }
        IPgAIAbility TrainingGolemFireBurst { get; }
        IPgAIAbility GrimalkinClaw { get; }
        IPgAIAbility GrimalkinBite { get; }
        IPgAIAbility GrimalkinPuncture { get; }
        IPgAIAbility WerewolfSword1 { get; }
        IPgAIAbility WerewolfSword2 { get; }
        IPgAIAbility WerewolfSwordStun { get; }
        IPgAIAbility WerewolfArrow1 { get; }
        IPgAIAbility WerewolfArrow2 { get; }
        IPgAIAbility WerewolfOmegaArrow { get; }
        IPgAIAbility NpcSmash { get; }
        IPgAIAbility NpcDoubleHitCurse { get; }
        IPgAIAbility NpcBlockingStance { get; }
        IPgAIAbility NpcHeadcracker { get; }
        IPgAIAbility StrigaClawA { get; }
        IPgAIAbility StrigaClawB { get; }
        IPgAIAbility StrigaReap { get; }
        IPgAIAbility StrigaReap2 { get; }
        IPgAIAbility StrigaFireBreath { get; }
        IPgAIAbility StrigaBuff { get; }
        IPgAIAbility GhostlyPunchA { get; }
        IPgAIAbility GhostlyPunchB { get; }
        IPgAIAbility GhostlyBurst { get; }
        IPgAIAbility GhostlyBossPunchA { get; }
        IPgAIAbility GhostlyBossPunchB { get; }
        IPgAIAbility GhostlyBossBurst { get; }
        IPgAIAbility GhostlyBolt { get; }
        IPgAIAbility InjectorBugBite { get; }
        IPgAIAbility InjectorBugInject { get; }
        IPgAIAbility InjectorBugInject2 { get; }
        IPgAIAbility FaceOfDeathKill { get; }
        IPgAIAbility WatcherFireball { get; }
        IPgAIAbility WatcherSlap { get; }
        IPgAIAbility WatcherAcidball { get; }
        IPgAIAbility RedCrystalBlast { get; }
        IPgAIAbility RedCrystalBurst { get; }
        IPgAIAbility TurretCrystalZap { get; }
        IPgAIAbility TurretCrystalZap2 { get; }
        IPgAIAbility TurretCrystalZapLongRange { get; }
        IPgAIAbility TurretCrystalZapLongRange2 { get; }
        IPgAIAbility DeathRay { get; }
        IPgAIAbility SpyPortalZap { get; }
        IPgAIAbility SpyPortalZap2 { get; }
        IPgAIAbility BitingVineBite { get; }
        IPgAIAbility BitingVineSpit { get; }
        IPgAIAbility BitingVineSpitB { get; }
        IPgAIAbility BitingVineCast { get; }
        IPgAIAbility BitingVineAppear { get; }
        IPgAIAbility BitingVineDisappear { get; }
        IPgAIAbility TrollClubA { get; }
        IPgAIAbility TrollClubB { get; }
        IPgAIAbility TrollKnockdown { get; }
        IPgAIAbility OgreClubA { get; }
        IPgAIAbility OgreClubB { get; }
        IPgAIAbility OgreThrow { get; }
        IPgAIAbility OgreStun { get; }
        IPgAIAbility FaeSwordA { get; }
        IPgAIAbility FaeSwordB { get; }
        IPgAIAbility FaeSwordKill { get; }
        IPgAIAbility DementiaPuckCurse { get; }
        IPgAIAbility FaeLightningSmiteHidden { get; }
        IPgAIAbility NecroSpark { get; }
        IPgAIAbility NecroDarknessWave { get; }
        IPgAIAbility NecroPainBubble { get; }
        IPgAIAbility NecroSparkPerching { get; }
        IPgAIAbility NecroDeathsHold { get; }
        IPgAIAbility DroachBiteA { get; }
        IPgAIAbility DroachBiteB { get; }
        IPgAIAbility DroachFireball { get; }
        IPgAIAbility DroachFireballPerching { get; }
        IPgAIAbility DroachBreatheFire { get; }
        IPgAIAbility DroachLightning { get; }
        IPgAIAbility DroachLightningPerching { get; }
        IPgAIAbility DroachShockingKnockback { get; }
        IPgAIAbility BasiliskClawA { get; }
        IPgAIAbility BasiliskClawB { get; }
        IPgAIAbility BasiliskToxicBite { get; }
        IPgAIAbility BasiliskDebuff { get; }
        IPgAIAbility BasiliskCastPerching { get; }
        IPgAIAbility CultistArrow1 { get; }
        IPgAIAbility CultistArrow2 { get; }
        IPgAIAbility CultistOmegaArrow { get; }
        IPgAIAbility CultistSword1 { get; }
        IPgAIAbility CultistSword2 { get; }
        IPgAIAbility CultistSwordStun { get; }
        IPgAIAbility BossMegaSword1 { get; }
        IPgAIAbility BossMegaSword2 { get; }
        IPgAIAbility SedgewickMegaSwordAngry { get; }
        IPgAIAbility BossMegaHammer { get; }
        IPgAIAbility BossMegaHammer2 { get; }
        IPgAIAbility BossMegaRageHammer { get; }
        IPgAIAbility ClaudiaTundraSpikes { get; }
        IPgAIAbility ClaudiaIceSpear { get; }
        IPgAIAbility ClaudiaBlizzard { get; }
        IPgAIAbility BigGolemHitA { get; }
        IPgAIAbility BigGolemHitB { get; }
        IPgAIAbility BigGolemFlingBoss { get; }
        IPgAIAbility BigGolemPerchFix { get; }
        IPgAIAbility BigGolemFlingBoss2 { get; }
        IPgAIAbility BigGolemSummonFireSnake { get; }
        IPgAIAbility BigGolemHitB_NoDisable { get; }
        IPgAIAbility BigGolemHitA_NoDisable { get; }
        IPgAIAbility BigGolemFling { get; }
        IPgAIAbility GhoulClawA { get; }
        IPgAIAbility GhoulClawB { get; }
        IPgAIAbility GhoulSelfBuff { get; }
        IPgAIAbility GhoulHammerA { get; }
        IPgAIAbility GhoulHammerB { get; }
        IPgAIAbility DragonWormSpitElectricity { get; }
        IPgAIAbility DragonWormBite { get; }
        IPgAIAbility DragonWormSmack { get; }
        IPgAIAbility DragonWormRage { get; }
        IPgAIAbility DragonWormEscape { get; }
        IPgAIAbility DragonWormSpitFire { get; }
        IPgAIAbility ColdSphereBurst { get; }
        IPgAIAbility ColdSphereFreezeBurst { get; }
        IPgAIAbility ManticoreBite { get; }
        IPgAIAbility ManticoreClaw { get; }
        IPgAIAbility ManticoreSting1 { get; }
        IPgAIAbility Manticoresting2 { get; }
        IPgAIAbility RakStaffHit { get; }
        IPgAIAbility RakStaffPin { get; }
        IPgAIAbility RakStaffBlock { get; }
        IPgAIAbility RakStaffHeavy { get; }
        IPgAIAbility RakSlash { get; }
        IPgAIAbility RakKnee { get; }
        IPgAIAbility RakKick { get; }
        IPgAIAbility RakBarrage { get; }
        IPgAIAbility RakSwordSlash { get; }
        IPgAIAbility RakHackingBlade { get; }
        IPgAIAbility RakDecapitate { get; }
        IPgAIAbility RakFireball { get; }
        IPgAIAbility RakBreatheFire { get; }
        IPgAIAbility RakRingOfFire { get; }
        IPgAIAbility RakToxinBomb { get; }
        IPgAIAbility RakAcidBomb { get; }
        IPgAIAbility RakHealingMist { get; }
        IPgAIAbility RakBasicShot { get; }
        IPgAIAbility RakHookShot { get; }
        IPgAIAbility RakBowBash { get; }
        IPgAIAbility RakAimedShot { get; }
        IPgAIAbility RakPoisonArrow { get; }
        IPgAIAbility RakMindreave { get; }
        IPgAIAbility RakPainBubble { get; }
        IPgAIAbility RakPanicCharge { get; }
        IPgAIAbility RakRevitalize { get; }
        IPgAIAbility RakReconstruct { get; }
        IPgAIAbility RakBossSlow { get; }
        IPgAIAbility RakBossPerchSlow { get; }
        IPgAIAbility FlapSkullBite { get; }
        IPgAIAbility FlapSkullBigBite { get; }
        IPgAIAbility MinotaurClub { get; }
        IPgAIAbility MinotaurRageClub { get; }
        IPgAIAbility MinotaurBoulder { get; }
        IPgAIAbility MinotaurBossRageClub { get; }
        IPgAIAbility CockatricePeck { get; }
        IPgAIAbility CockatriceTailWhip { get; }
        IPgAIAbility CockatriceParalyze { get; }
        IPgAIAbility GiantBeetleBite { get; }
        IPgAIAbility GiantBeetleInject { get; }
        IPgAIAbility GiantBeetleBoulderSpit { get; }
        IPgAIAbility BatIllusionSlashA { get; }
        IPgAIAbility BatIllusionSlashB { get; }
        IPgAIAbility BatIllusionBite { get; }
        IPgAIAbility GiantBatSlashA { get; }
        IPgAIAbility GiantBatSlashB { get; }
        IPgAIAbility GiantBatBite { get; }
        IPgAIAbility HagAgingTouch { get; }
        IPgAIAbility HagAgingScream { get; }
        IPgAIAbility TriffidClawA { get; }
        IPgAIAbility TriffidClawB { get; }
        IPgAIAbility TriffidTongue { get; }
        IPgAIAbility TriffidSpore { get; }
        IPgAIAbility TriffidShot { get; }
        IPgAIAbility TriffidTongueElite { get; }
        IPgAIAbility GiantScorpionClawA { get; }
        IPgAIAbility GiantScorpionClawB { get; }
        IPgAIAbility GiantScorpionSting { get; }
        IPgAIAbility KrakenBeak { get; }
        IPgAIAbility KrakenSlam { get; }
        IPgAIAbility KrakenRage { get; }
        IPgAIAbility KrakenBabyBeak { get; }
        IPgAIAbility KrakenBabySlam { get; }
        IPgAIAbility KrakenBabyRage { get; }
        IPgAIAbility RanalonHit { get; }
        IPgAIAbility RanalonHitB { get; }
        IPgAIAbility RanalonKick { get; }
        IPgAIAbility RanalonTongue { get; }
        IPgAIAbility RanalonZap { get; }
        IPgAIAbility RanalonZapB { get; }
        IPgAIAbility RanalonHeal { get; }
        IPgAIAbility RanalonRoot { get; }
        IPgAIAbility RanalonSelfBuff { get; }
        IPgAIAbility RanalonSelfBuffElite { get; }
        IPgAIAbility RanalonGuardianStab { get; }
        IPgAIAbility RanalonGuardianStabB { get; }
        IPgAIAbility RanalonGuardianBite { get; }
        IPgAIAbility RanalonGuardianBlind { get; }
        IPgAIAbility RanalonDoctrineKeeperStab { get; }
        IPgAIAbility RanalonDoctrineKeeperBlind { get; }
        IPgAIAbility BarghestBiteA { get; }
        IPgAIAbility BarghestBiteB { get; }
        IPgAIAbility BarghestDebuff { get; }
        IPgAIAbility WorghestDebuff { get; }
        IPgAIAbility BallistaFire { get; }
        IPgAIAbility BallistaFire_Long { get; }
        IPgAIAbility GargoyleSlamA { get; }
        IPgAIAbility GargoyleSlamB { get; }
        IPgAIAbility GargoyleStun { get; }
        IPgAIAbility GargoyleBossStun { get; }
        IPgAIAbility ScrayBite { get; }
        IPgAIAbility ScrayStab { get; }
        IPgAIAbility HippoBite { get; }
        IPgAIAbility HippoBiteAndHeal1 { get; }
        IPgAIAbility BigCatClaw_Pet { get; }
        IPgAIAbility BigCatPounce_Pet { get; }
        IPgAIAbility BigCatKill_Pet1 { get; }
        IPgAIAbility BigCatKill_Pet2 { get; }
        IPgAIAbility BigCatKill_Pet3 { get; }
        IPgAIAbility BigCatKill_Pet4 { get; }
        IPgAIAbility BigCatKill_Pet5 { get; }
        IPgAIAbility BigCatKill_Pet6 { get; }
        IPgAIAbility BigCatUltraKill_Pet1 { get; }
        IPgAIAbility BigCatUltraKill_Pet2 { get; }
        IPgAIAbility BigCatUltraKill_Pet3 { get; }
        IPgAIAbility BigCatUltraKill_Pet4 { get; }
        IPgAIAbility BigCatUltraKill_Pet5 { get; }
        IPgAIAbility BigCatUltraKill_Pet6 { get; }
        IPgAIAbility BigCatRoot_Pet1 { get; }
        IPgAIAbility BigCatRoot_Pet2 { get; }
        IPgAIAbility BigCatRoot_Pet3 { get; }
        IPgAIAbility BigCatRoot_Pet4 { get; }
        IPgAIAbility BigCatVuln_Pet1 { get; }
        IPgAIAbility BigCatVuln_Pet2 { get; }
        IPgAIAbility BigCatVuln_Pet3 { get; }
        IPgAIAbility BigCatVuln_Pet4 { get; }
        IPgAIAbility BigCatHeal_Pet1 { get; }
        IPgAIAbility BigCatHeal_Pet2 { get; }
        IPgAIAbility BigCatHeal_Pet3 { get; }
        IPgAIAbility BigCatHeal_Pet4 { get; }
        IPgAIAbility BigCatHeal_Pet5 { get; }
        IPgAIAbility BigCatHeal_Pet6 { get; }
        IPgAIAbility GrimalkinPuncture_Pet1 { get; }
        IPgAIAbility GrimalkinPuncture_Pet2 { get; }
        IPgAIAbility GrimalkinPuncture_Pet3 { get; }
        IPgAIAbility GrimalkinPuncture_Pet4 { get; }
        IPgAIAbility GrimalkinPuncture_Pet5 { get; }
        IPgAIAbility GrimalkinPuncture_Pet6 { get; }
        IPgAIAbility GrimalkinFlee_Pet1 { get; }
        IPgAIAbility GrimalkinFlee_Pet2 { get; }
        IPgAIAbility GrimalkinFlee_Pet3 { get; }
        IPgAIAbility RatBite_Pet { get; }
        IPgAIAbility RatClaw_Pet { get; }
        IPgAIAbility RatDeRage_Pet1 { get; }
        IPgAIAbility RatDeRage_Pet2 { get; }
        IPgAIAbility RatDeRage_Pet3 { get; }
        IPgAIAbility RatDeRage_Pet4 { get; }
        IPgAIAbility RatDeRage_Pet5 { get; }
        IPgAIAbility RatDeRage_Pet6 { get; }
        IPgAIAbility RatHeal_Pet1 { get; }
        IPgAIAbility RatHeal_Pet2 { get; }
        IPgAIAbility RatHeal_Pet3 { get; }
        IPgAIAbility RatHeal_Pet4 { get; }
        IPgAIAbility RatHeal_Pet5 { get; }
        IPgAIAbility RatHeal_Pet6 { get; }
        IPgAIAbility RatVuln_Pet1 { get; }
        IPgAIAbility RatVuln_Pet2 { get; }
        IPgAIAbility RatVuln_Pet3 { get; }
        IPgAIAbility RatVuln_Pet4 { get; }
        IPgAIAbility FireRatBite_Pet { get; }
        IPgAIAbility FireRatClaw_Pet { get; }
        IPgAIAbility RatBurn_Pet1 { get; }
        IPgAIAbility RatBurn_Pet2 { get; }
        IPgAIAbility RatBurn_Pet3 { get; }
        IPgAIAbility RatBurn_Pet4 { get; }
        IPgAIAbility RatBurn_Pet5 { get; }
        IPgAIAbility RatBurn_Pet6 { get; }
        IPgAIAbility BearBite_Pet { get; }
        IPgAIAbility BearClaw_Pet { get; }
        IPgAIAbility BearTaunt_Pet1 { get; }
        IPgAIAbility BearTaunt_Pet2 { get; }
        IPgAIAbility BearTaunt_Pet3 { get; }
        IPgAIAbility BearTaunt_Pet4 { get; }
        IPgAIAbility BearTaunt_Pet5 { get; }
        IPgAIAbility BearTaunt_Pet6 { get; }
        IPgAIAbility BearStun_Pet1 { get; }
        IPgAIAbility BearStun_Pet2 { get; }
        IPgAIAbility BearStun_Pet3 { get; }
        IPgAIAbility BearStun_Pet4 { get; }
        IPgAIAbility BearWarmth_Pet1 { get; }
        IPgAIAbility BearWarmth_Pet2 { get; }
        IPgAIAbility BearWarmth_Pet3 { get; }
        IPgAIAbility BearWarmth_Pet4 { get; }
        IPgAIAbility BearWarmth_Pet5 { get; }
        IPgAIAbility BearWarmth_Pet6 { get; }
        IPgAIAbility BearSelfHeal_Pet1 { get; }
        IPgAIAbility BearSelfHeal_Pet2 { get; }
        IPgAIAbility BearSelfHeal_Pet3 { get; }
        IPgAIAbility BearSelfHeal_Pet4 { get; }
        IPgAIAbility BearSelfHeal_Pet5 { get; }
        IPgAIAbility BearSelfHeal_Pet6 { get; }
        IPgAIAbility BearUltra_Pet1 { get; }
        IPgAIAbility BearUltra_Pet2 { get; }
        IPgAIAbility BearUltra_Pet3 { get; }
        IPgAIAbility BearUltra_Pet4 { get; }
        IPgAIAbility BearUltra_Pet5 { get; }
        IPgAIAbility BearUltra_Pet6 { get; }
    }
}
