namespace PgJsonObjects
{
    public enum AdvancementTableEnum
    {
        Internal_None,
        Balanced,
        PowerPassive,
        ModestPassive,
        Lore,
        Dying,
        FireMagic,
        Gourmand,
        PlayerWerewolf,
        WerewolfMetabolism,
        Foraging,
        PlayerPig,
        PlayerDeer,
        PlayerCow,
        PlayerSpider,
        Endurance,
        Surveying,
        Notoriety,
        Hoplology,
        TreasureHunting,
        CivicPride,
        Industry,
        PlayerBat,
        HolisticWellness,
        RetailManagement,
    }
}
