using System.Collections.Generic;

namespace PgJsonObjects
{
    public static class TextMaps
    {
        public static readonly Dictionary<object, string> GenericStringMap = new Dictionary<object, string>();

        public static readonly Dictionary<AbilityItemKeyword, string> AbilityItemKeywordStringMap = new Dictionary<AbilityItemKeyword, string>()
        {
            { AbilityItemKeyword.form_Deer, "form:Deer" },
            { AbilityItemKeyword.form_PotbellyPig, "form:PotbellyPig" },
            { AbilityItemKeyword.form_Cow, "form:Cow" },
            { AbilityItemKeyword.form_Spider, "form:Spider" },
            { AbilityItemKeyword.form_GiantBat, "form:GiantBat" },
        };

        public static readonly Dictionary<AbilityAnimation, string> AbilityAnimationTextMap = new Dictionary<AbilityAnimation, string>()
        {
            { AbilityAnimation.Internal_None, "None" },
            { AbilityAnimation.Attack_Unarmed_Punch, "Unarmed Punch" },
            { AbilityAnimation.Attack_Kick, "Kick" },
            { AbilityAnimation.Attack_Unarmed_Barrage, "Unarmed Barrage" },
            { AbilityAnimation.Attack_Unarmed_CobraStrike, "Unarmed Cobra Strike" },
            { AbilityAnimation.Attack_Unarmed_HipThrow, "Unarmed Hip Throw" },
            { AbilityAnimation.Attack_BattleChemistry_ToxinBomb_Fungus, "Fungus Toxin Bomb" },
            { AbilityAnimation.Attack_FireMagic_WeakFireball, "Fire Magic Weak Fireball" },
            { AbilityAnimation.Attack_FireMagic_Fireball, "Fire Magic Fireball" },
            { AbilityAnimation.Attack_FireMagic_Missile, "Fire Magic Missile" },
            { AbilityAnimation.Attack_FireMagic_DefensiveFlames, "Fire Magic Defensive Flames" },
            { AbilityAnimation.Attack_FireMagic_FireWall_Summon, "Fire Magic Summon Fire Wall" },
            { AbilityAnimation.Attack_Sword_Slash, "Sword Slash" },
            { AbilityAnimation.Attack_Sword_ManyCuts, "Sword Many Cuts" },
            { AbilityAnimation.Attack_Sword_Parry, "Sword Parry" },
            { AbilityAnimation.Attack_Sword_WindStrike, "Sword Wind Strike" },
            { AbilityAnimation.Attack_Sword_FinishingBlow, "Sword Finishing Blow" },
            { AbilityAnimation.Attack_Sword_Riposte, "Sword Riposte" },
            { AbilityAnimation.Attack_Sword_PrecisionPierce, "Sword Precision Pierce" },
            { AbilityAnimation.Attack_Psychology_PsychoAnalyze, "Psychology Psychoanalyze" },
            { AbilityAnimation.Attack_Psychology_TellMeAboutYourMother, "Psychology Tell Me About Your Mother" },
            { AbilityAnimation.Attack_Psychology_StrikeANerve, "Psychology Strike A Nerve" },
            { AbilityAnimation.Attack_Psychology_CauseTerror, "Psychology Cause Terror" },
            { AbilityAnimation.Attack_Psychology_PepTalk, "Psychology Pep Talk" },
            { AbilityAnimation.Attack_Magic_Summon1, "Magic Summon (1)" },
            { AbilityAnimation.Attack_Knife_Slash, "Knife Slash" },
            { AbilityAnimation.Attack_Bite, "Bite Attack" },
            { AbilityAnimation.Attack_Claw, "Claw Attack" },
            { AbilityAnimation.Attack_BecomeWolf, "Become Wolf" },
            { AbilityAnimation.Attack_PackAttack, "Pack Attack" },
            { AbilityAnimation.Attack_PouncingRake, "Pouncing Rake" },
            { AbilityAnimation.Howl, "Howl" },
            { AbilityAnimation.Unset, "Unset" },
            { AbilityAnimation.Attack_FirstAid, "First Aid" },
            { AbilityAnimation.Attack_Repair, "Repair" },
            { AbilityAnimation.Attack, "Attack (1)" },
            { AbilityAnimation.Attack_Magic_FastCast1, "Magic Fast Cast (1)" },
            { AbilityAnimation.Attack_Magic_FastCast2, "Magic Fast Cast (2)" },
            { AbilityAnimation.Attack_Magic_Summon2, "Magic Summon (2)" },
            { AbilityAnimation.Attack2, "Attack (2)" },
            { AbilityAnimation.Attack_QuickTame, "Quick Tame" },
            { AbilityAnimation.Attack_Magic_Buff1, "Magic Buff (1)" },
            { AbilityAnimation.Attack_Magic_Buff2, "Magic Buff (2)" },
            { AbilityAnimation.Attack_BattleChemistry_ToxinBomb_Generic, "Generic Toxin Bomb" },
            { AbilityAnimation.Attack_BattleChemistry_ToxinBomb_Seafood, "Seafood Toxin Bomb" },
            { AbilityAnimation.Attack_BattleChemistry_HasteBomb, "Haste Bomb" },
            { AbilityAnimation.Attack_BattleChemistry_HealingMist, "Healing Mist" },
            { AbilityAnimation.Attack_BattleChemistry_ToxinBomb_Ice, "Ice Toxin Bomb" },
            { AbilityAnimation.Attack_BattleChemistry_Inject_Mutation, "Inject Mutation" },
            { AbilityAnimation.Attack_BattleChemistry_Summon_Golem, "Summon Golem" },
            { AbilityAnimation.SearchArea, "Search Area" },
            { AbilityAnimation.Attack_Knife_Thrust, "Thrust" },
            { AbilityAnimation.Attack_SummonPet, "Summon Pet" },
            { AbilityAnimation.Attack_SickEm, "Sick'Em" },
            { AbilityAnimation.Attack_RequestPetAid, "Request Pet Aid" },
            { AbilityAnimation.Attack_BuffPet, "Buff Pet" },
            { AbilityAnimation.Attack_BefriendAnimal, "Befriend Animal" },
            { AbilityAnimation.Attack_Mentalism_MindBlast, "Mind Blast" },
            { AbilityAnimation.Attack_Staff_Smash, "Staff Smash" },
            { AbilityAnimation.Attack_Staff_DoubleHit, "Staff Double Hit" },
            { AbilityAnimation.Attack_Staff_Lunge, "Staff Lunge" },
            { AbilityAnimation.Attack_Staff_Deflect, "Staff Deflect" },
            { AbilityAnimation.Attack_Staff_Block, "Staff Block" },
            { AbilityAnimation.Attack_Staff_Redirect, "Staff Redirect" },
            { AbilityAnimation.Attack_Necromancy_RaiseSkeleton, "Raise Skeleton" },
            { AbilityAnimation.Attack_Necromancy_RaiseZombie, "Raise Zombie" },
            { AbilityAnimation.Attack_Necromancy_RaiseSuperZombie, "Raise Super Zombie" },
            { AbilityAnimation.Attack_Necromancy_LifeCrush, "Life Crush" },
            { AbilityAnimation.Attack_Necromancy_LifeSteal, "Life Steal" },
            { AbilityAnimation.Attack_Necromancy_HealUndead, "Heal Undead" },
            { AbilityAnimation.Attack_Necromancy_HeartsPower, "Heart's Power" },
            { AbilityAnimation.Attack_Necromancy_SpleensPower, "Spleen's Power" },
            { AbilityAnimation.Attack_Necromancy_Necroform, "Necroform" },
            { AbilityAnimation.Attack_Mentalism_Wave, "Wave" },
            { AbilityAnimation.Attack_Mentalism_CauseHeadache, "Cause Headache" },
            { AbilityAnimation.Attack_Mentalism_Heal, "Mentalism Heal" },
            { AbilityAnimation.Attack_Mentalism_PainBubble, "Pain Bubble" },
            { AbilityAnimation.Attack_Archery_Shoot, "Archery Shoot" },
            { AbilityAnimation.Attack_Archery_MultiShot, "Multi Shot" },
            { AbilityAnimation.Attack_Archery_Bash, "Archery Bash" },
            { AbilityAnimation.Attack_Archery_CastShoot, "Archery Cast Shoot" },
            { AbilityAnimation.Attack_Archery_FastShoot, "Archery Fast Shoot" },
            { AbilityAnimation.Attack_ToughItOut, "Tough It Out" },
            { AbilityAnimation.Attack_Shield_BasicBash, "Shield Basic Bash" },
            { AbilityAnimation.Attack_Shield_FancyBash, "Shield Fancy Bash" },
            { AbilityAnimation.Attack_Shield_Buff, "Shield Buff" },
            { AbilityAnimation.Attack_Shield_Ward, "Shield Ward" },
            { AbilityAnimation.Attack_Shield_Heal, "Shield Heal" },
            { AbilityAnimation.Attack_Shield_EpicBash, "Shield Epic Bash" },
            { AbilityAnimation.Attack_Druid_TransformA, "Druid Transform (A)" },
            { AbilityAnimation.Attack_Hammer_Club, "Hammer Club" },
            { AbilityAnimation.Attack_Hammer_Pound, "Hammer Pound" },
            { AbilityAnimation.Attack_Hammer_Buff, "Hammer Buff" },
            { AbilityAnimation.Attack_Hammer_Leap, "Hammer Leap" },
            { AbilityAnimation.Attack_Hammer_Zap, "Hammer Zap" },
            { AbilityAnimation.Attack_Hammer_Reckless, "Hammer Reckless" },
            { AbilityAnimation.Attack_Druid_TransformB, "Druid Transform (B)" },
            { AbilityAnimation.Attack_Druid_DebuffA, "Druid Debuff (A)" },
            { AbilityAnimation.Attack_Druid_DebuffB, "Druid Debuff (B)" },
            { AbilityAnimation.Attack_Druid_Buff, "Druid Buff" },
            { AbilityAnimation.Attack_Druid_Zap, "Druid Zap" },
            { AbilityAnimation.Attack_Druid_Heal, "Druid Heal" },
            { AbilityAnimation.Attack_Druid_Blast, "Druid Blast" },
            { AbilityAnimation.Attack_FireMagic_Flare, "FireMagic Flare" },
            { AbilityAnimation.BlowOcarina, "Blow Ocarina" },
            { AbilityAnimation.PlayLute, "Play Lute" },
            { AbilityAnimation.PluckLute, "Pluck Lute" },
            { AbilityAnimation.HandDrumFast, "Hand Drum Fast" },
            { AbilityAnimation.HandDrumSlow, "Hand Drum Slow" },
            { AbilityAnimation.BlowHorn, "Blow Horn" },
            { AbilityAnimation.PlayDulcimer, "Play Dulcimer" },
            { AbilityAnimation.PlayHarp, "Play Harp" },
            { AbilityAnimation.Dance1, "Dance (1)" },
            { AbilityAnimation.Dance2, "Dance (2)" },
            { AbilityAnimation.Dance3, "Dance (3)" },
            { AbilityAnimation.Dance4, "Dance (4)" },
            { AbilityAnimation.Dance5, "Dance (5)" },
            { AbilityAnimation.Dance6, "Dance (6)" },
            { AbilityAnimation.Attack_Knife_DoubleSlash, "Knife Double Slash" },
            { AbilityAnimation.Attack_Knife_Throw, "Knife Throw" },
            { AbilityAnimation.Attack_Knife_Finisher, "Knife Finisher" },
            { AbilityAnimation.Concerned, "Concerned" },
            { AbilityAnimation.Attack_BattleChemistry_ToxinBomb_Poison, "Poison Toxin Bomb" },
            { AbilityAnimation.YawnStretch, "Yawn Stretch" },
            { AbilityAnimation.Sit, "Sit" },
            { AbilityAnimation.Attack_Taunt1, "Taunt Attack (1)" },
            { AbilityAnimation.Attack_BecomeNormal, "Become Normal" },
            { AbilityAnimation.Attack_Hammer_HitWeakness, "Hammer Hit Weakness" },
            { AbilityAnimation.Attack_Bard_SongOfResurgence, "Song Of Resurgence" },
            { AbilityAnimation.Attack_Bard_SongOfBravery, "Song Of Bravery" },
            { AbilityAnimation.Attack_Bard_SongOfDiscord, "Song Of Discord" },
            { AbilityAnimation.Attack_Bard_Rally, "Bard Rally" },
            { AbilityAnimation.Attack_Bard_AnthemOfAvoidance, "Anthem Of Avoidance" },
            { AbilityAnimation.Attack_Bard_EntrancingLullaby, "Entrancing Lullaby" },
            { AbilityAnimation.Attack_Bard_VirtuososBallad, "Virtuoso's Ballad" },
            { AbilityAnimation.Attack_Bard_HymnOfResurrection, "Hymn Of Resurrection" },
            { AbilityAnimation.Attack_Bard_MomentOfResolve, "Moment Of Resolve" },
            { AbilityAnimation.Attack_Bard_BlastOfFury, "Blast Of Fury" },
            { AbilityAnimation.Attack_Bard_BlastOfDefiance, "Blast Of Defiance" },
            { AbilityAnimation.Attack_Bard_BlastOfDespair, "Blast Of Despair" },
            { AbilityAnimation.Attack_Bard_ThunderousNote, "Thunderous Note" },
            { AbilityAnimation.Attack_Bard_Disharmony, "Disharmony" },
        };

        public static readonly Dictionary<Deaths, string> CauseOfDeathTextMap = new Dictionary<Deaths, string>()
        {
            { Deaths.Internal_None, "None" },
            { Deaths.PunchingDamage, "Punching Damage" },
            { Deaths.KickingDamage, "Kicking Damage" },
            { Deaths.ThrowingDamage, "Throwing Damage" },
            { Deaths.Bodyslam, "Bodyslam" },
            { Deaths.Headbutt, "Headbutt" },
            { Deaths.SlashingDamage, "Slashing Damage" },
            { Deaths.FungusDamage, "Fungus Damage" },
            { Deaths.FireDamage, "Fire Damage" },
            { Deaths.ColdDamage, "Cold Damage" },
            { Deaths.HitByRock, "Hit By Rock" },
            { Deaths.PiercingDamage, "Piercing Damage" },
            { Deaths.Shame, "Shame" },
            { Deaths.Terror, "Terror" },
            { Deaths.Healed, "Healed" },
            { Deaths.HeartAttack, "Heart Attack" },
            { Deaths.MagicalSuicide, "Magical Suicide" },
            { Deaths.SeafoodDamage, "Seafood Damage" },
            { Deaths.AttackWildAnimal, "Wild Animal Attack" },
            { Deaths.Screaming, "Screaming" },
            { Deaths.AttackCattle, "Cattle Attack" },
            { Deaths.ChemicalBomb, "Chemical Bomb" },
            { Deaths.OverAcceleration, "Over Acceleration" },
            { Deaths.SuddenFreeze, "Sudden Freeze" },
            { Deaths.PoisonedBlade, "Poisoned Blade" },
            { Deaths.PetAbuse, "Pet Abuse" },
            { Deaths.BashedWithStick, "Bashed With Stick" },
            { Deaths.DarknessBlast, "Darkness Blast" },
            { Deaths.DarknessReap, "Darkness Reap" },
            { Deaths.ZombieHands, "Zombie Hands" },
            { Deaths.Deathgaze, "Deathgaze" },
            { Deaths.ElectricityDamage, "Electricity Damage" },
            { Deaths.PsychicDamage, "Psychic Damage" },
            { Deaths.Mindwiped, "Mindwiped" },
            { Deaths.ArrowDamage, "Arrow Damage" },
            { Deaths.AcidDamage, "Acid Damage" },
            { Deaths.PanicWhileSnared, "Panic While Snared" },
            { Deaths.RestorativeArrow, "Restorative Arrow" },
            { Deaths.NatureDamage, "Nature Damage" },
            { Deaths.PoisonDamage, "Poison Damage" },
            { Deaths.TeleportedIntoSea, "Teleported Into Sea" },
            { Deaths.TeleportedIntoEarth, "Teleported Into Earth" },
            { Deaths.TeleportedIntoSky, "Teleported Into Sky" },
            { Deaths.StakeThroughTheHeart, "Stake Through The Heart" },
            { Deaths.ShieldBash, "Shield Bash" },
            { Deaths.CrushingDamage, "Crushing Damage" },
            { Deaths.Wind, "Wind" },
            { Deaths.DiseasedBite, "Diseased Bite" },
            { Deaths.Clubbed, "Clubbed" },
            { Deaths.BonesShattered, "Bones Shattered" },
            { Deaths.HeartThorn, "Heart Thorn" },
            { Deaths.Rot, "Rot" },
            { Deaths.Fever, "Fever" },
            { Deaths.ChillTrauma, "Chill Trauma" },
            { Deaths.KnifeStab, "Knife Stab" },
            { Deaths.ThrownKnife, "Thrown Knife" },
            { Deaths.AttackEnragedWildAnimal, "Enraged Wild Animal Attack" },
            { Deaths.AttackSpider, "Spider Attack" },
            { Deaths.AttackUndead, "Undead Attack" },
            { Deaths.AttackEnragedUndead, "Enraged Undead Attack" },
            { Deaths.AttackExplodingSkeleton, "Exploding Skeleton Attack" },
            { Deaths.AttackGiantSkeleton, "Giant Skeleton Attack" },
            { Deaths.BoneWhirlwind, "Bone Whirlwind" },
            { Deaths.AttackHaunting, "Haunting Attack" },
            { Deaths.DarknessHeartAttack, "Darkness Heart Attack" },
            { Deaths.AttackHumanoid, "Humanoid Attack" },
            { Deaths.AttackEnragedHumanoid, "Enraged Humanoid Attack" },
            { Deaths.AttackFireWall, "FireWall Attack" },
            { Deaths.AttackRune, "Rune Attack" },
            { Deaths.AttackAberration, "Aberration Attack" },
            { Deaths.AttackDinosaurSlash, "Dinosaur Slash Attack" },
            { Deaths.AttackDinosaurBite, "Dinosaur Bite Attack" },
            { Deaths.AttackTailWhip, "Tail Whip Attack" },
            { Deaths.AttackInsect, "Insect Attack" },
            { Deaths.AttackEnragedInsect, "Enraged Insect Attack" },
            { Deaths.AttackMollusc, "Mollusc Attack" },
            { Deaths.AttackEnragedMollusc, "Enraged Mollusc Attack" },
            { Deaths.AttackWorm, "Worm Attack" },
            { Deaths.InsectsUnderSkin, "Insects Under Skin" },
            { Deaths.AttackSelfDestructGolem, "Self Destruct Golem Attack" },
            { Deaths.AttackExplodingAnimal, "Exploding Animal Attack" },
            { Deaths.AttackWeatherCreature, "Weather Creature Attack" },
            { Deaths.AttackDarknessBeast, "Darkness Beast Attack" },
            { Deaths.DarknessBomb, "Darkness Bomb" },
            { Deaths.PlantClaw, "Plant Claw" },
            { Deaths.TriffidTongue, "Triffid Tongue" },
            { Deaths.Spores, "Spores" },
            { Deaths.Pincer, "Pincer" },
            { Deaths.SuperPoison, "Super Poison" },
            { Deaths.Orc, "Orc" },
            { Deaths.Hooked, "Hooked" },
            { Deaths.Slime, "Slime" },
            { Deaths.IceSlime, "Ice Slime" },
            { Deaths.InsaneSwordsman, "Swordsman Insane" },
            { Deaths.ExplodingZombie, "Exploding Zombie" },
            { Deaths.StrigaDrain, "Striga Drain" },
            { Deaths.GhostTrauma, "Ghost Trauma" },
            { Deaths.TraumaDamage, "Trauma Damage" },
            { Deaths.FaceOfDeathTouch, "Face Of Death Touch" },
            { Deaths.SpyPortal, "Spy Portal" },
            { Deaths.AttackDroach, "Droach Attack" },
            { Deaths.AttackInsaneCultist, "Insane Cultist Attack" },
            { Deaths.AttackClass4Spirit, "Class 4 Spirit Attack" },
            { Deaths.LamiaCharm, "Lamia Charm" },
            { Deaths.GolemCrush, "Golem Crush" },
            { Deaths.DragonElectricProjectile, "Dragon Electric Projectile" },
            { Deaths.WormEngulf, "Worm Engulf" },
            { Deaths.RangedSword, "Ranged Sword" },
            { Deaths.FlapSkullBite, "Flap Skull Bite" },
            { Deaths.PeckedToDeath, "Pecked To Death" },
            { Deaths.Paralyzed, "Paralyzed" },
            { Deaths.IllusionBat, "Illusion Bat" },
            { Deaths.AgingTouch, "Aging Touch" },
            { Deaths.Kraken, "Kraken" },
            { Deaths.ToxicGrease, "Toxic Grease" },
            { Deaths.CrossbowDamage, "Crossbow Damage" },
            { Deaths.BallistaDamage, "Ballista Damage" },
            { Deaths.Irrelevance, "Irrelevance" },
            { Deaths.PsychicGhost, "Psychic Ghost" },
            { Deaths.HippogriffPeck, "Hippogriff Peck" },
            { Deaths.Hypnotized, "Hypnotized" },
            { Deaths.SonicDamage, "Sonic Damage" },
            { Deaths.BadMusic, "Bad Music" },
            { Deaths.LoudMusic, "Loud Music" },
        };

        public static readonly Dictionary<PowerSkill, string> PowerSkillTextMap = new Dictionary<PowerSkill, string>()
        {
            { PowerSkill.Internal_None, "None" },
            { PowerSkill.AnySkill, "Any Skill" },
            { PowerSkill.Sword, "Sword" },
            { PowerSkill.FireMagic, "Fire Magic" },
            { PowerSkill.Unarmed, "Unarmed" },
            { PowerSkill.Psychology, "Psychology" },
            { PowerSkill.Staff, "Staff" },
            { PowerSkill.Mentalism, "Mentalism" },
            { PowerSkill.Archery, "Archery" },
            { PowerSkill.Shield, "Shield" },
            { PowerSkill.AnimalHandling, "Animal Handling" },
            { PowerSkill.Knife, "Knife Fighting" },
            { PowerSkill.Cow, "Cow" },
            { PowerSkill.Deer, "Deer" },
            { PowerSkill.Pig, "Pig" },
            { PowerSkill.Spider, "Spider" },
            { PowerSkill.ArmorPatching, "Armor Patching" },
            { PowerSkill.Endurance, "Endurance" },
            { PowerSkill.Unknown, "Unknown" },
            { PowerSkill.Werewolf, "Werewolf" },
            { PowerSkill.BattleChemistry, "Battle Chemistry" },
            { PowerSkill.Necromancy, "Necromancy" },
            { PowerSkill.Hammer, "Hammer" },
            { PowerSkill.Druid, "Druid" },
            { PowerSkill.IceMagic, "Ice Magic" },
            { PowerSkill.GiantBat, "Giant Bat" },
            { PowerSkill.Axe, "Axe" },
            { PowerSkill.ChargedPig, "Charged Pig" },
            { PowerSkill.Mycology, "Mycology" },
            { PowerSkill.Anatomy, "Anatomy" },
            { PowerSkill.Phrenology, "Phrenology" },
            { PowerSkill.Performance, "Performance" },
            { PowerSkill.Augmentation, "Augmentation" },
            { PowerSkill.Alchemy, "Alchemy" },
            { PowerSkill.Artistry, "Artistry" },
            { PowerSkill.Fishing, "Fishing" },
            { PowerSkill.Mining, "Mining" },
            { PowerSkill.Gardening, "Gardening" },
            { PowerSkill.Cooking, "Cooking" },
            { PowerSkill.Pathology, "Pathology" },
            { PowerSkill.Calligraphy, "Calligraphy" },
            { PowerSkill.Carpentry, "Carpentry" },
            { PowerSkill.Foraging, "Foraging" },
            { PowerSkill.Meditation, "Meditation" },
            { PowerSkill.Skinning, "Skinning" },
            { PowerSkill.Tanning, "Tanning" },
            { PowerSkill.Leatherworking, "Leatherworking" },
            { PowerSkill.SigilScripting, "Sigil Scripting" },
            { PowerSkill.Blacksmithing, "Blacksmithing" },
            { PowerSkill.Surveying, "Surveying" },
            { PowerSkill.Geology, "Geology" },
            { PowerSkill.Butchering, "Butchering" },
            { PowerSkill.Tailoring, "Tailoring" },
            { PowerSkill.Toolcrafting, "Toolcrafting" },
            { PowerSkill.Performance_Strings, "Stringed Intruments" },
            { PowerSkill.Performance_Percussion, "Percussion Intruments" },
            { PowerSkill.Performance_Wind, "Wind Intrument" },
            { PowerSkill.Industry, "Industry" },
            { PowerSkill.FlowerArrangement, "Flower Arrangement" },
            { PowerSkill.NatureAppreciation, "Nature Appreciation" },
            { PowerSkill.RetailManagement, "Retail Management" },
            { PowerSkill.SurvivalInstincts, "Survival Instincts" },
            { PowerSkill.Performance_Dance, "Interpretive Dance" },
            { PowerSkill.Cheesemaking, "Cheesemaking" },
            { PowerSkill.Lore, "Lore" },
            { PowerSkill.Textiles, "Textiles" },
            { PowerSkill.Teleportation, "Teleportation" },
            { PowerSkill.Fletching, "Fletching" },
            { PowerSkill.WeaponAugmentBrewing, "Weapon Augmentation" },
            { PowerSkill.ArmorAugmentBrewing, "Armor Augmentation" },
            { PowerSkill.AncillaryArmorAugmentBrewing, "Ancillary-Armor Augmentation" },
            { PowerSkill.JewelryAugmentBrewing, "Jewelry Augmentation" },
            { PowerSkill.Transmutation, "Transmutation" },
            { PowerSkill.BuckleArtistry, "Buckle Artistry" },
            { PowerSkill.TreasureCartography, "Treasure Cartography" },
            { PowerSkill.Gadgeteering, "Gadgeteering" },
            { PowerSkill.Phrenology_Humans, "Human Phrenology" },
            { PowerSkill.Phrenology_Elves, "Elf Phrenology" },
            { PowerSkill.Phrenology_Rakshasa, "Rakshasa Phrenology" },
            { PowerSkill.Phrenology_Fae, "Fae Phrenology" },
            { PowerSkill.Phrenology_Goblins, "Goblin Phrenology" },
            { PowerSkill.Phrenology_Orcs, "Orc Phrenology" },
            { PowerSkill.Phrenology_Giants, "Giant Phrenology" },
            { PowerSkill.Hoplology, "Hoplology" },
            { PowerSkill.DyeMaking, "Dye Making" },
            { PowerSkill.FirstAid, "FirstAid" },
            { PowerSkill.ShamanicInfusion, "Shamanic Infusion" },
            { PowerSkill.IceConjuration, "Ice Conjuration" },
            { PowerSkill.SushiPreparation, "Sushi Preparation" },
            { PowerSkill.Anatomy_Fish, "Fish and Snail Anatomy" },
            { PowerSkill.HolisticWellness, "Holistic Wellness" },
            { PowerSkill.Gourmand, "Gourmand" },
            { PowerSkill.Vocabulary, "Vocabulary" },
            { PowerSkill.Anatomy_Humans, "Human Anatomy" },
            { PowerSkill.Anatomy_Elves, "Elf Anatomy" },
            { PowerSkill.Anatomy_Rakshasa, "Rakshasa Anatomy" },
            { PowerSkill.Compassion, "Compassion" },
            { PowerSkill.Dying, "Dying" },
            { PowerSkill.Anatomy_Goblins, "Goblin Anatomy" },
            { PowerSkill.Anatomy_Plants, "Plant Anatomy" },
            { PowerSkill.PoetryAppreciation, "Poetry Appreciation" },
            { PowerSkill.GenderStudies, "Gender Studies" },
            { PowerSkill.Crossbow, "Crossbow" },
            { PowerSkill.Anatomy_Orcs, "Orc Anatomy" },
            { PowerSkill.Bard, "Bard" },
            { PowerSkill.Myconic, "Myconic" },
            { PowerSkill.Anatomy_Ungulates, "Non-Ruminant Ungulate Anatomy" },
            { PowerSkill.Anatomy_Ruminants, "Ruminant Anatomy" },
            { PowerSkill.Anatomy_Cats, "Cat Anatomy" },
            { PowerSkill.Anatomy_Rodents, "Rodent Anatomy" },
            { PowerSkill.Anatomy_Arthropods, "Arthropod Anatomy" },
            { PowerSkill.Anatomy_Canines, "Canine Anatomy" },
            { PowerSkill.Anatomy_Dinosaurs, "Dinosaur Anatomy" },
            { PowerSkill.Anatomy_Bears, "Bear Anatomy" },
            { PowerSkill.BeastSpeech, "Beast Speech" },
            { PowerSkill.ArtHistory, "Art History" },
            { PowerSkill.Brewing, "Brewing" },
            { PowerSkill.Anatomy_Fey, "Fey Anatomy" },
            { PowerSkill.Anatomy_Dwarves, "Dwarves Anatomy" },
            { PowerSkill.IocaineResistance, "Iocaine Resistance" },
        };

        public static readonly Dictionary<ConsumedItems, string> ConsumedItemsTextMap = new Dictionary<ConsumedItems, string>()
        {
            { ConsumedItems.Internal_None, "None" },
            { ConsumedItems.Cheese, "Any cheese" },
            { ConsumedItems.HumanoidSkull, "Any humanoid skull" },
            { ConsumedItems.ImpressiveHumanoidSkull, "Any impressive humanoid skull" },
        };

        public static readonly Dictionary<DamageType, string> DamageTypeTextMap = new Dictionary<DamageType, string>()
        {
            { DamageType.Internal_None, "None" },
            { DamageType.Internal_Empty, "" },
            { DamageType.Crushing, "Crushing" },
            { DamageType.Slashing, "Slashing" },
            { DamageType.Nature, "Nature" },
            { DamageType.Fire, "Fire" },
            { DamageType.Cold, "Cold" },
            { DamageType.Smiting, "None" },
            { DamageType.Piercing, "Piercing" },
            { DamageType.Psychic, "Psychic" },
            { DamageType.Trauma, "Trauma" },
            { DamageType.Nothingness, "Nothingness" },
            { DamageType.Potion, "None" },
            { DamageType.Electricity, "Electricity" },
            { DamageType.Poison, "Poison" },
            { DamageType.Acid, "Acid" },
            { DamageType.Darkness, "Darkness" },
            { DamageType.Regeneration, "None" },
            { DamageType.Sonic, "Sonic" },
            { DamageType.Poison_direct, "Poison (direct)" },
            { DamageType.Trauma_direct, "Trauma (direct)" },
            { DamageType.Poison_indirect, "Poison (indirect)" },
            { DamageType.Trauma_indirect, "Trauma (indirect)" },
        };

        public static readonly Dictionary<AbilityIndicatingEnabled, string> AbilityIndicatingEnabledTextMap = new Dictionary<AbilityIndicatingEnabled, string>()
        {
            { AbilityIndicatingEnabled.Internal_None, "Never" },
            { AbilityIndicatingEnabled.WerewolfForm, "When in wolf form" },
            { AbilityIndicatingEnabled.WerewolfHowlMode, "When in full-moon wolf form" },
            { AbilityIndicatingEnabled.TriggeredAlchemyGolem, "When golem triggered" },
            { AbilityIndicatingEnabled.Echolocation, "When echolocating" },
            { AbilityIndicatingEnabled.RavenForm, "When in raven form" },
            { AbilityIndicatingEnabled.DeerForm, "When in deer form" },
            { AbilityIndicatingEnabled.PlayingSongOfResurgence, "When playing (Song of Resurgence)" },
            { AbilityIndicatingEnabled.PlayingSongOfBravery, "When playing (Song of Bravery)" },
            { AbilityIndicatingEnabled.PlayingSongOfDiscord, "When playing (Song of Discord)" },
        };

        public static readonly Dictionary<AbilityItemKeyword, string> AbilityItemKeywordTextMap = new Dictionary<AbilityItemKeyword, string>()
        {
            { AbilityItemKeyword.Internal_None, "None" },
            { AbilityItemKeyword.Sword, "Wield a sword" },
            { AbilityItemKeyword.EmptyHand, "At least one open hand" },
            { AbilityItemKeyword.Unarmed, "Hands must be empty" },
            { AbilityItemKeyword.UnarmedClaw, "Wield a claw weapon" },
            { AbilityItemKeyword.UnarmedMainHandWeapon, "Wielding two unarmed weapons" },
            { AbilityItemKeyword.FireStaff, "Wield a fire staff" },
            { AbilityItemKeyword.form_Deer, "Be in deer form" },
            { AbilityItemKeyword.Werewolf, "Be in wolf form" },
            { AbilityItemKeyword.Beast, "Be in beast form" },
            { AbilityItemKeyword.HasHands, "Be in a form with hands" },
            { AbilityItemKeyword.ClothArmor, "Wear at least some cloth armor" },
            { AbilityItemKeyword.form_PotbellyPig, "Pig only" },
            { AbilityItemKeyword.form_Cow, "Cow only" },
            { AbilityItemKeyword.ChemistryEquipment, "Wield chemistry equipment" },
            { AbilityItemKeyword.Staff, "Wield a staff" },
            { AbilityItemKeyword.NecromancyGem, "Necromancy-enabling gear" },
            { AbilityItemKeyword.Bow, "Wield a bow" },
            { AbilityItemKeyword.form_Spider, "Spider only" },
            { AbilityItemKeyword.Shield, "Wield a shield" },
            { AbilityItemKeyword.form_GiantBat, "Giant Bat only" },
            { AbilityItemKeyword.Hammer, "Wield a hammer" },
            { AbilityItemKeyword.Wooden, "Wield wooden weapon" },
            { AbilityItemKeyword.Ocarina, "Wield an ocarina" },
            { AbilityItemKeyword.Lute, "Wield a lute" },
            { AbilityItemKeyword.Drum, "Wield a drum" },
            { AbilityItemKeyword.Tuba, "Wield a tuba" },
            { AbilityItemKeyword.Dulcimer, "Wield a dulcimer" },
            { AbilityItemKeyword.Harp, "Wield a harp" },
            { AbilityItemKeyword.Knife, "Wield a knife or dagger" },
            { AbilityItemKeyword.Crossbow, "Wield a crossbow" },
            { AbilityItemKeyword.BardLute, "Wield a bard lute" },
            { AbilityItemKeyword.BardInstrument, "Wield a bard instrument" },
            { AbilityItemKeyword.BardHorn, "Wield a bard horn" },
        };

        public static readonly Dictionary<AbilityKeyword, string> AbilityKeywordTextMap = new Dictionary<AbilityKeyword, string>()
        {
            { AbilityKeyword.Internal_None, "None" },
            { AbilityKeyword.Attack, "Attack" },
            { AbilityKeyword.Unarmed, "Unarmed" },
            { AbilityKeyword.Punch, "Punch" },
            { AbilityKeyword.Melee, "Melee" },
            { AbilityKeyword.BasicAttack, "Basic Attack" },
            { AbilityKeyword.CombatRefresh, "Combat Refresh" },
            { AbilityKeyword.FistAttack, "Fist Attack" },
            { AbilityKeyword.Lint_NotLearnable, "Not Learnable" },
            { AbilityKeyword.Kick, "Kick" },
            { AbilityKeyword.FrontKick, "Front Kick" },
            { AbilityKeyword.BodypartAttack, "Bodypart Attack" },
            { AbilityKeyword.Barrage, "Barrage" },
            { AbilityKeyword.BarrageOnly, "Barrage Only" },
            { AbilityKeyword.NiceAttack, "Nice Attack" },
            { AbilityKeyword.CobraStrike, "Cobra Strike" },
            { AbilityKeyword.SerpentStrike, "Serpent Strike" },
            { AbilityKeyword.CoreAttack, "Core Attack" },
            { AbilityKeyword.HipThrow, "Hip Throw" },
            { AbilityKeyword.HipSlam, "Hip Slam" },
            { AbilityKeyword.Jab, "Jab" },
            { AbilityKeyword.KneeKick, "Knee Kick" },
            { AbilityKeyword.EpicAttack, "Epic Attack" },
            { AbilityKeyword.Bodyslam, "Bodyslam" },
            { AbilityKeyword.Headbutt, "Headbutt" },
            { AbilityKeyword.MambaStrike, "Mamba Strike" },
            { AbilityKeyword.BruisingBlow, "Bruising Blow" },
            { AbilityKeyword.SignatureDebuff, "Signature Debuff" },
            { AbilityKeyword.SlashingStrike, "Slashing Strike" },
            { AbilityKeyword.BarrageOfBlades, "Barrage Of Blades" },
            { AbilityKeyword.ClawBarrage, "Claw Barrage" },
            { AbilityKeyword.InfuriatingFist, "Infuriating Fist" },
            { AbilityKeyword.Bomb, "Bomb" },
            { AbilityKeyword.SporeBomb, "Spore Bomb" },
            { AbilityKeyword.Burst, "Burst" },
            { AbilityKeyword.FireMagic, "Fire Magic" },
            { AbilityKeyword.Fireball, "Fireball" },
            { AbilityKeyword.FireMagicAttack, "Fire Magic Attack" },
            { AbilityKeyword.Ranged, "Ranged" },
            { AbilityKeyword.FireSpell, "Fire Spell" },
            { AbilityKeyword.SuperFireball, "Super Fireball" },
            { AbilityKeyword.Firebolts, "Firebolts" },
            { AbilityKeyword.ScintillatingFlame, "Scintillating Flame" },
            { AbilityKeyword.Scintillating, "Scintillating" },
            { AbilityKeyword.Calefaction, "Calefaction" },
            { AbilityKeyword.FireBurst, "Fire Burst" },
            { AbilityKeyword.DefensiveBurst, "Defensive Burst" },
            { AbilityKeyword.RingOfFire, "Ring Of Fire" },
            { AbilityKeyword.FireBreath, "Fire Breath" },
            { AbilityKeyword.SelfImmolation, "Self Immolation" },
            { AbilityKeyword.FleshToFuel, "Flesh To Fuel" },
            { AbilityKeyword.SurvivalUtility, "Survival Utility" },
            { AbilityKeyword.SpontaneousCast, "Spontaneous Cast" },
            { AbilityKeyword.Frostball, "Frostball" },
            { AbilityKeyword.ScintillatingFrost, "Scintillating Frost" },
            { AbilityKeyword.DefensiveChill, "Defensive Chill" },
            { AbilityKeyword.ColdProtection, "Cold Protection" },
            { AbilityKeyword.FireWall, "Fire Wall" },
            { AbilityKeyword.CrushingBall, "Crushing Ball" },
            { AbilityKeyword.Sword, "Sword" },
            { AbilityKeyword.SwordSlash, "Sword Slash" },
            { AbilityKeyword.ManyCuts, "Many Cuts" },
            { AbilityKeyword.Parry, "Parry" },
            { AbilityKeyword.OnlyParry, "Only Parry" },
            { AbilityKeyword.WindStrike, "Wind Strike" },
            { AbilityKeyword.FinishingBlow, "Finishing Blow" },
            { AbilityKeyword.Riposte, "Riposte" },
            { AbilityKeyword.PrecisionPierce, "Precision Pierce" },
            { AbilityKeyword.HackingBlade, "Hacking Blade" },
            { AbilityKeyword.DebilitatingBlow, "Debilitating Blow" },
            { AbilityKeyword.Decapitate, "Decapitate" },
            { AbilityKeyword.FlashingStrike, "Flashing Strike" },
            { AbilityKeyword.ThrustingBlade, "Thrusting Blade" },
            { AbilityKeyword.HeartPiercer, "Heart Piercer" },
            { AbilityKeyword.Psychology, "Psychology" },
            { AbilityKeyword.Psychoanalyze, "Psychoanalyze" },
            { AbilityKeyword.PsychologyAttack, "Psychology Attack" },
            { AbilityKeyword.PhrenologyCriticals, "Phrenology Criticals" },
            { AbilityKeyword.TellMeAboutYourMother, "Tell Me About Your Mother" },
            { AbilityKeyword.StrikeANerve, "Strike A Nerve" },
            { AbilityKeyword.CauseTerror, "Cause Terror" },
            { AbilityKeyword.PepTalk, "Pep Talk" },
            { AbilityKeyword.PsychologyHeal, "Psychology Heal" },
            { AbilityKeyword.MajorHeal, "Major Heal" },
            { AbilityKeyword.FastTalk, "Fast Talk" },
            { AbilityKeyword.Ridicule, "Ridicule" },
            { AbilityKeyword.Soothe, "Soothe" },
            { AbilityKeyword.PositiveAttitude, "Positive Attitude" },
            { AbilityKeyword.InspireConfidence, "Inspire Confidence" },
            { AbilityKeyword.SignatureSupport, "Signature Support" },
            { AbilityKeyword.YouWereAdopted, "You Were Adopted" },
            { AbilityKeyword.ButILoveYou, "But I Love You" },
            { AbilityKeyword.Mock, "Mock" },
            { AbilityKeyword.Werewolf, "Werewolf" },
            { AbilityKeyword.WerewolfAttack, "Werewolf Attack" },
            { AbilityKeyword.WerewolfBite, "Werewolf Bite" },
            { AbilityKeyword.Bite, "Bite" },
            { AbilityKeyword.WerewolfClaw, "Werewolf Claw" },
            { AbilityKeyword.Claw, "Claw" },
            { AbilityKeyword.PackAttack, "Pack Attack" },
            { AbilityKeyword.PouncingRake, "Pouncing Rake" },
            { AbilityKeyword.ShadowFeint, "Shadow Feint" },
            { AbilityKeyword.SanguineFangs, "Sanguine Fangs" },
            { AbilityKeyword.SeeRed, "See Red" },
            { AbilityKeyword.SmellFear, "Smell Fear" },
            { AbilityKeyword.DoubleClaw, "Double Claw" },
            { AbilityKeyword.HuntingSpeed, "Hunting Speed" },
            { AbilityKeyword.Skulk, "Skulk" },
            { AbilityKeyword.BloodOfThePack, "Blood Of The Pack" },
            { AbilityKeyword.HowlMode, "Howl Mode" },
            { AbilityKeyword.ShadowFeintActivation, "Shadow Feint Activation" },
            { AbilityKeyword.FirstAid, "First Aid" },
            { AbilityKeyword.Pig, "Pig" },
            { AbilityKeyword.PigAttack, "Pig Attack" },
            { AbilityKeyword.PigBite, "Pig Bite" },
            { AbilityKeyword.TruffleSniff, "Truffle Sniff" },
            { AbilityKeyword.TerrorDash, "Terror Dash" },
            { AbilityKeyword.GruntOfAbeyance, "Grunt Of Abeyance" },
            { AbilityKeyword.PigRend, "Pig Rend" },
            { AbilityKeyword.Frenzy, "Frenzy" },
            { AbilityKeyword.PigChomp, "Pig Chomp" },
            { AbilityKeyword.PigPunt, "Pig Punt" },
            { AbilityKeyword.Squeal, "Squeal" },
            { AbilityKeyword.Mudbath, "Mudbath" },
            { AbilityKeyword.Harmlessness, "Harmlessness" },
            { AbilityKeyword.PorcineAlertness, "Porcine Alertness" },
            { AbilityKeyword.Deer, "Deer" },
            { AbilityKeyword.DeerKick, "Deer Kick" },
            { AbilityKeyword.DeerAttack, "Deer Attack" },
            { AbilityKeyword.DeerBash, "Deer Bash" },
            { AbilityKeyword.DoeEyes, "Doe Eyes" },
            { AbilityKeyword.BoundingEscape, "Bounding Escape" },
            { AbilityKeyword.CutenessOverload, "Cuteness Overload" },
            { AbilityKeyword.AntlerSlash, "Antler Slash" },
            { AbilityKeyword.PummelingHooves, "Pummeling Hooves" },
            { AbilityKeyword.KingOfTheForest, "King Of The Forest" },
            { AbilityKeyword.Cow, "Cow" },
            { AbilityKeyword.CowFrontKick, "Cow Front Kick" },
            { AbilityKeyword.CowAttack, "Cow Attack" },
            { AbilityKeyword.CowStampede, "Cow Stampede" },
            { AbilityKeyword.MooOfCalm, "Moo Of Calm" },
            { AbilityKeyword.ChewCud, "Chew Cud" },
            { AbilityKeyword.Graze, "Graze" },
            { AbilityKeyword.CollectMilk, "Collect Milk" },
            { AbilityKeyword.MooOfDetermination, "Moo Of Determination" },
            { AbilityKeyword.CowBash, "Cow Bash" },
            { AbilityKeyword.ClobberingHoof, "Clobbering Hoof" },
            { AbilityKeyword.ToughHoof, "Tough Hoof" },
            { AbilityKeyword.BattleChemistry, "Battle Chemistry" },
            { AbilityKeyword.ChemistryBomb, "Chemistry Bomb" },
            { AbilityKeyword.BattleChemistryAttack, "Battle Chemistry Attack" },
            { AbilityKeyword.ToxinBomb, "Toxin Bomb" },
            { AbilityKeyword.MycotoxinBomb, "Mycotoxin Bomb" },
            { AbilityKeyword.AcidBomb, "Acid Bomb" },
            { AbilityKeyword.HasteConcoction, "Haste Concoction" },
            { AbilityKeyword.HealingMist, "Healing Mist" },
            { AbilityKeyword.FreezingMist, "Freezing Mist" },
            { AbilityKeyword.HealingInjection, "Healing Injection" },
            { AbilityKeyword.MinorHeal, "Minor Heal" },
            { AbilityKeyword.SicEm, "Sic'Em" },
            { AbilityKeyword.GetItOffMe, "Get It Off Me" },
            { AbilityKeyword.MonstrousRage, "Monstrous Rage" },
            { AbilityKeyword.FeedPet, "Feed Pet" },
            { AbilityKeyword.ThatllDo, "That'll Do" },
            { AbilityKeyword.WildEndurance, "Wild Endurance" },
            { AbilityKeyword.NimbleLimbs, "Nimble Limbs" },
            { AbilityKeyword.ShrillCommand, "Shrill Command" },
            { AbilityKeyword.UnnaturalWrath, "Unnatural Wrath" },
            { AbilityKeyword.CleverTrick, "Clever Trick" },
            { AbilityKeyword.Staff, "Staff" },
            { AbilityKeyword.Smash, "Smash" },
            { AbilityKeyword.StaffAttack, "Staff Attack" },
            { AbilityKeyword.DoubleHit, "Double Hit" },
            { AbilityKeyword.Lunge, "Lunge" },
            { AbilityKeyword.DeflectiveSpin, "Deflective Spin" },
            { AbilityKeyword.BlockingStance, "Blocking Stance" },
            { AbilityKeyword.Redirect, "Redirect" },
            { AbilityKeyword.Suppress, "Suppress" },
            { AbilityKeyword.StrategicThrust, "Strategic Thrust" },
            { AbilityKeyword.SafeFall, "Safe Fall" },
            { AbilityKeyword.StaffPin, "Staff Pin" },
            { AbilityKeyword.Headcracker, "Headcracker" },
            { AbilityKeyword.HeedTheStick, "Heed The Stick" },
            { AbilityKeyword.PhoenixStrike, "Phoenix Strike" },
            { AbilityKeyword.Necromancy, "Necromancy" },
            { AbilityKeyword.RaiseSkeleton, "Raise Skeleton" },
            { AbilityKeyword.RaiseSkeletalArcher, "Raise Skeletal Archer" },
            { AbilityKeyword.RaiseSkeletalSwordsman, "Raise Skeletal Swordsman" },
            { AbilityKeyword.RaiseSkeletalMage, "Raise Skeletal Mage" },
            { AbilityKeyword.RaiseZombie, "Raise Zombie" },
            { AbilityKeyword.CreateSuperZombie, "Create Super Zombie" },
            { AbilityKeyword.LifeCrush, "Life Crush" },
            { AbilityKeyword.LifeSteal, "Life Steal" },
            { AbilityKeyword.HealUndead, "Heal Undead" },
            { AbilityKeyword.HeartsPower, "Heart's Power" },
            { AbilityKeyword.SpleensPower, "Spleen's Power" },
            { AbilityKeyword.DeathsHold, "Death's Hold" },
            { AbilityKeyword.ProvokeUndead, "Provoke Undead" },
            { AbilityKeyword.RebuildUndead, "Rebuild Undead" },
            { AbilityKeyword.Deathgaze, "Deathgaze" },
            { AbilityKeyword.WaveOfDarkness, "Wave Of Darkness" },
            { AbilityKeyword.SparkOfDeath, "Spark Of Death" },
            { AbilityKeyword.Mentalism, "Mentalism" },
            { AbilityKeyword.PsiWave, "Psi Wave" },
            { AbilityKeyword.PsiHealthWave, "Psi Health Wave" },
            { AbilityKeyword.PsiArmorWave, "Psi Armor Wave" },
            { AbilityKeyword.PsiPowerWave, "Psi Power Wave" },
            { AbilityKeyword.PsiAdrenalineWave, "Psi Adrenaline Wave" },
            { AbilityKeyword.Mindreave, "Mindreave" },
            { AbilityKeyword.MentalismAttack, "Mentalism Attack" },
            { AbilityKeyword.SystemShock, "System Shock" },
            { AbilityKeyword.Reconstruct, "Reconstruct" },
            { AbilityKeyword.RevitalizeOrReconstruct, "Revitalize Or Reconstruct" },
            { AbilityKeyword.PanicCharge, "Panic Charge" },
            { AbilityKeyword.Agonize, "Agonize" },
            { AbilityKeyword.Electrify, "Electrify" },
            { AbilityKeyword.Revitalize, "Revitalize" },
            { AbilityKeyword.PainBubble, "Pain Bubble" },
            { AbilityKeyword.Archery, "Archery" },
            { AbilityKeyword.BasicShot, "Basic Shot" },
            { AbilityKeyword.AnatomyCriticals, "Anatomy Criticals" },
            { AbilityKeyword.HookShot, "Hook Shot" },
            { AbilityKeyword.MultiShot, "Multi Shot" },
            { AbilityKeyword.AimedShot, "Aimed Shot" },
            { AbilityKeyword.BowBash, "Bow Bash" },
            { AbilityKeyword.LongShot, "Long Shot" },
            { AbilityKeyword.PoisonArrow, "Poison Arrow" },
            { AbilityKeyword.ElementalArchery, "Elemental Archery" },
            { AbilityKeyword.AcidArrow, "Acid Arrow" },
            { AbilityKeyword.SnareArrow, "Snare Arrow" },
            { AbilityKeyword.FireArrow, "Fire Arrow" },
            { AbilityKeyword.HeavyShot, "Heavy Shot" },
            { AbilityKeyword.HeavyArchery, "Heavy Archery" },
            { AbilityKeyword.HeavyMultiShot, "Heavy Multi Shot" },
            { AbilityKeyword.BlitzShot, "Blitz Shot" },
            { AbilityKeyword.RestorativeArrow, "Restorative Arrow" },
            { AbilityKeyword.Lint_HarmlessWithDamageBoosts, "Harmless With Damage Boosts" },
            { AbilityKeyword.ManglingShot, "Mangling Shot" },
            { AbilityKeyword.SigilScripting, "Sigil Scripting" },
            { AbilityKeyword.ExplosionSigil, "Explosion Sigil" },
            { AbilityKeyword.RestorativeSigil, "Restorative Sigil" },
            { AbilityKeyword.RepulsionBarrier, "Repulsion Barrier" },
            { AbilityKeyword.ElectricitySigil, "Electricity Sigil" },
            { AbilityKeyword.TeleportationSigil, "Teleportation Sigil" },
            { AbilityKeyword.Glyph, "Glyph" },
            { AbilityKeyword.RepairGlyph, "Repair Glyph" },
            { AbilityKeyword.Spider, "Spider" },
            { AbilityKeyword.SpiderBite, "Spider Bite" },
            { AbilityKeyword.SpiderAttack, "Spider Attack" },
            { AbilityKeyword.InjectVenom, "Inject Venom" },
            { AbilityKeyword.Gripjaw, "Gripjaw" },
            { AbilityKeyword.PremeditatedDoom, "Premeditated Doom" },
            { AbilityKeyword.WebTrap, "Web Trap" },
            { AbilityKeyword.SpiderFear, "Spider Fear" },
            { AbilityKeyword.GrapplingWeb, "Grappling Web" },
            { AbilityKeyword.SpiderAcid, "Spider Acid" },
            { AbilityKeyword.SpiderIncubate, "Spider Incubate" },
            { AbilityKeyword.SpiderIllusion, "Spider Illusion" },
            { AbilityKeyword.InfiniteLegs, "Infinite Legs" },
            { AbilityKeyword.StakeTheHeart, "Stake The Heart" },
            { AbilityKeyword.Shield, "Shield" },
            { AbilityKeyword.StunningBash, "Stunning Bash" },
            { AbilityKeyword.Bash, "Bash" },
            { AbilityKeyword.DisruptingBash, "Disrupting Bash" },
            { AbilityKeyword.InfuriatingBash, "Infuriating Bash" },
            { AbilityKeyword.EmergencyBash, "Emergency Bash" },
            { AbilityKeyword.StrategicPreparation, "Strategic Preparation" },
            { AbilityKeyword.ElementalWard, "Elemental Ward" },
            { AbilityKeyword.Reinforce, "Reinforce" },
            { AbilityKeyword.VigorousDefense, "Vigorous Defense" },
            { AbilityKeyword.DeflectArrows, "Deflect Arrows" },
            { AbilityKeyword.TakeTheLead, "Take The Lead" },
            { AbilityKeyword.FireShield, "Fire Shield" },
            { AbilityKeyword.FightMeYouFools, "Fight Me You Fools" },
            { AbilityKeyword.ShieldTeam, "Shield Team" },
            { AbilityKeyword.FinishIt, "Finish It" },
            { AbilityKeyword.Perseverance, "Perseverance" },
            { AbilityKeyword.GiantBat, "Giant Bat" },
            { AbilityKeyword.Rip, "Rip" },
            { AbilityKeyword.Tear, "Tear" },
            { AbilityKeyword.WingVortex, "Wing Vortex" },
            { AbilityKeyword.DrinkBlood, "Drink Blood" },
            { AbilityKeyword.VirulentBite, "Virulent Bite" },
            { AbilityKeyword.BatStability, "Bat Stability" },
            { AbilityKeyword.Screech, "Screech" },
            { AbilityKeyword.Sonic, "Sonic" },
            { AbilityKeyword.SonicBurst, "Sonic Burst" },
            { AbilityKeyword.ConfusingDouble, "Confusing Double" },
            { AbilityKeyword.SmoulderingGaze, "Smouldering Gaze" },
            { AbilityKeyword.Hammer, "Hammer" },
            { AbilityKeyword.Pound, "Pound" },
            { AbilityKeyword.HammerAttack, "Hammer Attack" },
            { AbilityKeyword.PoundToSlag, "Pound To Slag" },
            { AbilityKeyword.HammerNonBasic, "Hammer Non Basic" },
            { AbilityKeyword.LookAtMyHammer, "Look At My Hammer" },
            { AbilityKeyword.LeapingSmash, "Leaping Smash" },
            { AbilityKeyword.RibShatter, "Rib Shatter" },
            { AbilityKeyword.Thunderstrike, "Thunderstrike" },
            { AbilityKeyword.DischargingStrike, "Discharging Strike" },
            { AbilityKeyword.RecklessSlam, "Reckless Slam" },
            { AbilityKeyword.ReverberatingStrike, "Reverberating Strike" },
            { AbilityKeyword.SeismicImpact, "Seismic Impact" },
            { AbilityKeyword.HurlLightning, "Hurl Lightning" },
            { AbilityKeyword.LatentCharge, "Latent Charge" },
            { AbilityKeyword.WayOfTheHammer, "Way Of The Hammer" },
            { AbilityKeyword.Druid, "Druid" },
            { AbilityKeyword.HeartThorn, "Heart Thorn" },
            { AbilityKeyword.Rotskin, "Rotskin" },
            { AbilityKeyword.Delerium, "Delerium" },
            { AbilityKeyword.Brambleskin, "Brambleskin" },
            { AbilityKeyword.CosmicStrike, "Cosmic Strike" },
            { AbilityKeyword.FillWithBile, "Fill With Bile" },
            { AbilityKeyword.HealingSanctuary, "Healing Sanctuary" },
            { AbilityKeyword.DruidHeal, "Druid Heal" },
            { AbilityKeyword.Regrowth, "Regrowth" },
            { AbilityKeyword.Energize, "Energize" },
            { AbilityKeyword.TracklessSteps, "Trackless Steps" },
            { AbilityKeyword.HuntersStride, "Hunter's Stride" },
            { AbilityKeyword.Toxinball, "Toxinball" },
            { AbilityKeyword.Shillelagh, "Shillelagh" },
            { AbilityKeyword.CloudSight, "Cloud Sight" },
            { AbilityKeyword.PulseOfLife, "Pulse Of Life" },
            { AbilityKeyword.IceMagic, "Ice Magic" },
            { AbilityKeyword.IceNova, "Ice Nova" },
            { AbilityKeyword.IceMagicAoE, "Ice Magic AoE" },
            { AbilityKeyword.IceArmor, "Ice Armor" },
            { AbilityKeyword.FreezeSolid, "Freeze Solid" },
            { AbilityKeyword.IceMagicSingleTarget, "Ice Magic Single Target" },
            { AbilityKeyword.IceSpear, "IceSpear" },
            { AbilityKeyword.Frostbite, "Frostbite" },
            { AbilityKeyword.ColdSphere, "ColdSphere" },
            { AbilityKeyword.TundraSpikes, "Tundra Spikes" },
            { AbilityKeyword.Blizzard, "Blizzard" },
            { AbilityKeyword.IceLightning, "Ice Lightning" },
            { AbilityKeyword.CryogenicFreeze, "Cryogenic Freeze" },
            { AbilityKeyword.Shardblast, "Shardblast" },
            { AbilityKeyword.IceVeins, "Ice Veins" },
            { AbilityKeyword.Chill, "Chill" },
            { AbilityKeyword.Performance, "Performance" },
            { AbilityKeyword.Dance1, "Dance (1)" },
            { AbilityKeyword.Dance2, "Dance (2)" },
            { AbilityKeyword.Dance3, "Dance (3)" },
            { AbilityKeyword.Dance4, "Dance (4)" },
            { AbilityKeyword.Dance5, "Dance (5)" },
            { AbilityKeyword.Dance6, "Dance (6)" },
            { AbilityKeyword.Knife, "Knife" },
            { AbilityKeyword.OpeningThrust, "Opening Thrust" },
            { AbilityKeyword.KnifeNonCut, "Knife Non Cut" },
            { AbilityKeyword.MarkingCut, "Marking Cut" },
            { AbilityKeyword.KnifeCut, "Knife Cut" },
            { AbilityKeyword.BlurCut, "Blur Cut" },
            { AbilityKeyword.PoisonersCut, "Poisoner's Cut" },
            { AbilityKeyword.FendingBlade, "Fending Blade" },
            { AbilityKeyword.Slice, "Slice" },
            { AbilityKeyword.Venomstrike, "Venomstrike" },
            { AbilityKeyword.Gut, "Gut" },
            { AbilityKeyword.HamstringThrow, "Hamstring Throw" },
            { AbilityKeyword.SurpriseThrow, "Surprise Throw" },
            { AbilityKeyword.Special_NoAggro_HalfDamage, "Special: Half Damage with no aggro" },
            { AbilityKeyword.Backstab, "Backstab" },
            { AbilityKeyword.SurgeCut, "Surge Cut" },
            { AbilityKeyword.FanOfBlades, "Fan Of Blades" },
            { AbilityKeyword.ToughenUp, "Toughen Up" },
            { AbilityKeyword.SurvivalInstincts, "Survival Instincts" },
            { AbilityKeyword.IndomitableGrace, "Indomitable Grace" },
            { AbilityKeyword.ToxicFlesh, "Toxic Flesh" },
            { AbilityKeyword.Howl, "Howl" },
            { AbilityKeyword.PoisonBombToss, "Poison Bomb Toss" },
            { AbilityKeyword.GolemHealingMist, "Golem Healing Mist" },
            { AbilityKeyword.GolemSelfDestruct, "Golem Self Destruct" },
            { AbilityKeyword.GolemInvigoratingMist, "Golem Invigorating Mist" },
            { AbilityKeyword.GolemHealingInjection, "Golem Healing Injection" },
            { AbilityKeyword.GolemDoomAdmixture, "Golem Doom Admixture" },
            { AbilityKeyword.GolemSelfSacrifice, "Golem Self Sacrifice" },
            { AbilityKeyword.GolemTauntingPunch, "Golem Taunting Punch" },
            { AbilityKeyword.GolemHasteConcoction, "Golem Haste Concoction" },
            { AbilityKeyword.GolemFireBalm, "Golem Fire Balm" },
            { AbilityKeyword.GolemRageMist, "Golem Rage Mist" },
            { AbilityKeyword.GolemRageAcidToss, "Golem Rage Acid Toss" },
            { AbilityKeyword.Crush, "Crush" },
            { AbilityKeyword.Debuff, "Debuff" },
            { AbilityKeyword.ColdSphereFreezeBurst, "Cold Sphere Freeze Burst" },
            { AbilityKeyword.PetA, "Pet (A)" },
            { AbilityKeyword.PetHeal, "Pet Heal" },
            { AbilityKeyword.PetB, "Pet (B)" },
            { AbilityKeyword.QuickBash, "Quick Bash" },
            { AbilityKeyword.Special_WIthAggro_HalfDamage, "Special: Half damage with aggro" },
            { AbilityKeyword.Special_WithAggro_HalfDamage, "Special: Half damage with aggro" },
            { AbilityKeyword.NoralaGift_HuntingSpeed1, "Norala Gift Hunting Speed (1)" },
            { AbilityKeyword.NoralaGift_HuntingSpeed2, "Norala Gift Hunting Speed (2)" },
            { AbilityKeyword.NoralaGift_HuntingSpeed3, "Norala Gift Hunting Speed (3)" },
            { AbilityKeyword.PatchArmor, "Patch Armor" },
            { AbilityKeyword.Mutation, "Mutation" },
            { AbilityKeyword.Mutation_KneeSpikes, "Mutation (Knee Spikes)" },
            { AbilityKeyword.Mutation_ExtraSkin, "Mutation (Extra Skin)" },
            { AbilityKeyword.Mutation_ExtraHeart, "Mutation (Extra Heart)" },
            { AbilityKeyword.Mutation_ExtraToes, "Mutation (Extra Toes)" },
            { AbilityKeyword.Mutation_StretchySpine, "Mutation (Stretchy Spine)" },
            { AbilityKeyword.ToxicIrritant, "Toxic Irritant" },
            { AbilityKeyword.Crossbow, "Crossbow" },
            { AbilityKeyword.DeathTrooper, "Death Trooper" },
            { AbilityKeyword.MiseryTrooper, "Misery Trooper" },
            { AbilityKeyword.TreacheryTrooper, "Treachery Trooper" },
            { AbilityKeyword.GazlukOfficer, "Gazluk Officer" },
            { AbilityKeyword.GazlukWarWizard, "Gazluk War Wizard" },
            { AbilityKeyword.MuttererNecromancer, "Mutterer Necromancer" },
            { AbilityKeyword.MuttererCabalist, "Mutterer Cabalist" },
            { AbilityKeyword.BardSong, "Bard Song" },
            { AbilityKeyword.SongOfResurgence, "Song Of Resurgence" },
            { AbilityKeyword.SongOfBravery, "Song Of Bravery" },
            { AbilityKeyword.SongOfDiscord, "Song Of Discord" },
            { AbilityKeyword.Rally, "Rally" },
            { AbilityKeyword.Bard, "Bard" },
            { AbilityKeyword.AnthemOfAvoidance, "Anthem Of Avoidance" },
            { AbilityKeyword.EntrancingLullaby, "Entrancing Lullaby" },
            { AbilityKeyword.VirtuososBallad, "Virtuoso's Ballad" },
            { AbilityKeyword.HymnOfResurrection, "Hymn Of Resurrection" },
            { AbilityKeyword.HymnOfResurrection1Enabled, "Hymn Of Resurrection Enabled" },
            { AbilityKeyword.MomentOfResolve, "Moment Of Resolve" },
            { AbilityKeyword.BardBlast, "Bard Blast" },
            { AbilityKeyword.BlastOfFury, "Blast Of Fury" },
            { AbilityKeyword.BlastOfDefiance, "Blast Of Defiance" },
            { AbilityKeyword.BlastOfDespair, "Blast Of Despair" },
            { AbilityKeyword.ThunderousNote, "Thunderous Note" },
            { AbilityKeyword.Disharmony, "Disharmony" },
            { AbilityKeyword.SongOfDiscordActivation, "Song Of Discord Activation" },
            { AbilityKeyword.FireBolts, "Fire Bolts" },
        };

        public static readonly Dictionary<AbilityPetType, string> AbilityPetTypeTextMap = new Dictionary<AbilityPetType, string>()
        {
            { AbilityPetType.Internal_None, "None" },
            { AbilityPetType.SummonedFireWall, "Summoned Fire Wall" },
            { AbilityPetType.SummonedDeer, "Summoned Deer" },
            { AbilityPetType.Mushroom, "Mushroom" },
            { AbilityPetType.Rat, "Rat" },
            { AbilityPetType.Minigolem_Pet, "Minigolem Pet" },
            { AbilityPetType.StabledPet, "Stabled Pet" },
            { AbilityPetType.SummonedSkeleton, "Summoned Skeleton" },
            { AbilityPetType.SummonedCorpse, "Summoned Corpse" },
            { AbilityPetType.SummonedWebTrap, "Summoned Web Trap" },
            { AbilityPetType.SummonedSpider, "Summoned Spider" },
        };

        public static readonly Dictionary<AbilityProjectile, string> AbilityProjectileTextMap = new Dictionary<AbilityProjectile, string>()
        {
            { AbilityProjectile.Internal_None, "None" },
            { AbilityProjectile.Internal_Empty, "None" },
            { AbilityProjectile.Projectile_Warmthball, "Warmthball" },
            { AbilityProjectile.Projectile_Fireball, "Fireball" },
            { AbilityProjectile.Projectile_HotFireball, "Hot Fireball" },
            { AbilityProjectile.Projectile_SparklyFireball, "Sparkly Fireball" },
            { AbilityProjectile.Projectile_Arcaneball, "Arcane Ball" },
            { AbilityProjectile.Projectile_Frostball, "Frostball" },
            { AbilityProjectile.Projectile_BludgeoningBall, "Bludgeoning Ball" },
            { AbilityProjectile.Projectile_Darkness, "Darkness" },
            { AbilityProjectile.Projectile_Electricity, "Electricity" },
            { AbilityProjectile.Projectile_Arrow, "Arrow" },
            { AbilityProjectile.Projectile_AcidBall, "Acid Ball" },
            { AbilityProjectile.Projectile_WhirlDisk, "Whirl Disk" },
            { AbilityProjectile.Projectile_FrostMeteor, "Frost Meteor" },
            { AbilityProjectile.Projectile_IceDagger, "Ice Dagger" },
            { AbilityProjectile.Projectile_Fireball_NoLight, "Fireball No Light" },
            { AbilityProjectile.Projectile_ArcaneBall, "Arcane Ball" },
            { AbilityProjectile.Projectile_AcidBallFast, "Fast Acid Ball" },
            { AbilityProjectile.Projectile_Spit_Electricity, "Spit Electricity" },
            { AbilityProjectile.Projectile_Spit_Fireball, "Spit Fireball" },
            { AbilityProjectile.Projectile_Sword20, "Swords" },
            { AbilityProjectile.Projectile_Lightning, "Lightning" },
            { AbilityProjectile.Projectile_ElectricSpell, "Electric Spell" },
        };

        public static readonly Dictionary<Race, string> RaceTextMap = new Dictionary<Race, string>()
        {
            { Race.Internal_None, "None" },
            { Race.Rakshasa, "Rakshasa" },
            { Race.Human, "Human" },
            { Race.Elf, "Elf" },
            { Race.Fae, "Fae" },
        };

        public static readonly Dictionary<RecipeKeyword, string> RecipeKeywordTextMap = new Dictionary<RecipeKeyword, string>()
        {
            { RecipeKeyword.Internal_None, "None" },
            { RecipeKeyword.Lint_NotLearnable, "Not Learnable" },
            { RecipeKeyword.NoValueGeneration, "No Value Generation" },
            { RecipeKeyword.HighValueGeneration, "High Value Generation" },
            { RecipeKeyword.Teleport, "Teleport" },
            { RecipeKeyword.EatsBottle, "Eats Bottle" },
            { RecipeKeyword.Lint_NotObtainable, "Not Obtainable" },
            { RecipeKeyword.Lint_NoXP, "No XP" },
            { RecipeKeyword.Dye, "Dye" },
            { RecipeKeyword.Lint_NoResult, "No Result" },
            { RecipeKeyword.StorageCrateDruid, "Druid Storage Crate" },
            { RecipeKeyword.ShamanicInfusion, "Shamanic Infusion" },
        };

        public static readonly Dictionary<Appearance, string> AppearanceTextMap = new Dictionary<Appearance, string>()
        {
            { Appearance.Internal_None, "None" },
            { Appearance.Spider, "Spider" },
            { Appearance.Cow, "Cow" },
            { Appearance.PotbellyPig, "Pig" },
            { Appearance.Deer, "Deer" },
            { Appearance.Werewolf, "Werewolf" },
            { Appearance.GiantBat, "Giant Bat" },
        };

        public static readonly Dictionary<AbilityTarget, string> AbilityTargetTextMap = new Dictionary<AbilityTarget, string>()
        {
            { AbilityTarget.Internal_None, "None" },
            { AbilityTarget.Enemy, "Enemy" },
            { AbilityTarget.EnemiesAroundSelf, "Enemies around self" },
            { AbilityTarget.Self, "Self" },
            { AbilityTarget.AllyOrSelf, "Ally or self" },
            { AbilityTarget.DeadAlly, "Dead ally" },
            { AbilityTarget.PermanentPet, "Permanent pet" },
            { AbilityTarget.Corpse, "Corpse" },
            { AbilityTarget.Ally, "Ally" },
        };

        public static readonly Dictionary<TargetEffectKeyword, string> TargetEffectKeywordTextMap = new Dictionary<TargetEffectKeyword, string>()
        {
            { TargetEffectKeyword.Internal_None, "None" },
            { TargetEffectKeyword.MindRevealed, "Must have been recent victims of Psychoanalyze or Tell Me About Your Mother." },
            { TargetEffectKeyword.HasRecentlyHeardBardSong, "Must have heard your Song of Resurgence or Song of Bravery during the last 90 seconds." },
        };

        public static readonly Dictionary<AbilityTargetParticle, string> AbilityTargetParticleTextMap = new Dictionary<AbilityTargetParticle, string>()
        {
            { AbilityTargetParticle.Internal_None, "None" },
            { AbilityTargetParticle.WeaponHit, "Weapon Hit" },
            { AbilityTargetParticle.ComboHit, "Combo Hit" },
            { AbilityTargetParticle.BigHit, "Big Hit" },
            { AbilityTargetParticle.FireHit, "Fire Hit" },
            { AbilityTargetParticle.SlashHit, "Slash Hit" },
            { AbilityTargetParticle.Bite, "Bite" },
            { AbilityTargetParticle.ClawMarks, "Claw Marks" },
            { AbilityTargetParticle.ClawCombo, "Claw Combo" },
            { AbilityTargetParticle.SmallBuff, "Small Buff" },
            { AbilityTargetParticle.SpeedUp, "Speed Up" },
            { AbilityTargetParticle.Agitate, "Agitate" },
            { AbilityTargetParticle.DeathExplosion, "Death Explosion" },
            { AbilityTargetParticle.LightningStrike, "Lightning Strike" },
            { AbilityTargetParticle.HitVoid, "Hit Void" },
            { AbilityTargetParticle.ElectricityBurst, "Electricity Burst" },
            { AbilityTargetParticle.SpiritBreak, "Spirit Break" },
            { AbilityTargetParticle.HolyFireStrike, "Holy Fire Strike" },
            { AbilityTargetParticle.PsionicDebuff, "Psionic Debuff" },
            { AbilityTargetParticle.AcidBomb, "Acid Bomb" },
            { AbilityTargetParticle.GroundImpact, "Ground Impact" },
            { AbilityTargetParticle.ElectricityHit, "Electricity Hit" },
        };

        public static readonly Dictionary<TooltipsExtraKeywords, string> TooltipsExtraKeywordsTextMap = new Dictionary<TooltipsExtraKeywords, string>()
        {
            { TooltipsExtraKeywords.Internal_None, "None" },
            { TooltipsExtraKeywords.SongOfDiscordActivation, "Song of Discord Activation" },
        };
    }
}
