namespace PgObjects
{
#pragma warning disable SA1300 // Element should begin with upper-case letter
    public enum AbilityItemKeyword
    {
        Internal_None,
        Sword,
        EmptyHand,
        Unarmed,
        UnarmedClaw,
        UnarmedMainHandWeapon,
        FireStaff,
        Werewolf,
        Beast,
        HasHands,
        ClothArmor,
        ChemistryEquipment,
        Staff,
        NecromancyGem,
        Bow,
        Shield,
        Hammer,
        Wooden,
        Ocarina,
        Lute,
        Drum,
        Tuba,
        Dulcimer,
        Harp,
        Knife,
        Crossbow,
        BardLute,
        BardInstrument,
        BardHorn,
        IceStaff,
        Dirk,
        Dagger,
        HolySymbol,
        FairyChime,
        EnergyBow,
        Darkcaster,
        WeatherStaff,
        AnglingPole,
    }
#pragma warning restore SA1300 // Element should begin with upper-case letter
}
