namespace PgObjects
{
    public enum AbilityProjectile
    {
        Internal_None,
        Projectile_Warmthball,
        Projectile_Fireball,
        Projectile_HotFireball,
        Projectile_SparklyFireball,
        Projectile_Arcaneball,
        Projectile_Frostball,
        Projectile_BludgeoningBall,
        Projectile_Darkness,
        Projectile_Electricity,
        Projectile_Arrow,
        Projectile_AcidBall,
        // Projectile_WhirlDisk,
        Projectile_FrostMeteor,
        Projectile_IceDagger,
        Projectile_Fireball_NoLight,
        Projectile_ArcaneBall,
        Projectile_AcidBallFast,
        Projectile_Spit_Electricity,
        Projectile_Spit_Fireball,
        Projectile_Sword20,
        Projectile_Lightning,
        Projectile_ElectricSpell,
        Projectile_ChaosMissile,
        Attack_Taunt1,
        Projectile_Poison,
        Projectile_Sonic,
        Projectile_Fireball_Offhand,
        Projectile_WaterBall,
        Projectile_Dagger,
        Projectile_PlasmaBlastRed,
        Projectile_PlasmaBlastBlue,
    }
}
