namespace PgObjects;

public enum CombatCondition
{
    Internal_None,
    WieldingTwoKnives,
    WithoutFocus,
    WhilePlayingSong,
    WhileInBloodMistForm,
    SpecificTarget,
    TargetOfAbility,
    DirectDamageKillShot,
    TargetHasLowRage,
    TargetIsKilled,
    TargetIsVulnerable,
    AttackAbility,
    PetAttackType,
    TargetIsElite,
    TargetKilled,
    MinimumDistance,
    AbilityNotTriggered,
    AbilityTriggered,
    OnHit,
    DoingDamageOverTime,
    SpecificDamageType,
    SpecificDirectDamageType,
    TargetAnatomyIsAberration,
    BelowMaxArmor,
    BelowMaxRage,
}
