namespace PgObjects;

public enum CombatTarget
{
    Internal_None,
    Self,
    Allies,
    AnyPet,
    PetOfTarget,
    CharmedPet,
    ConjuredAndPet,
    AnimalHandlingPet,
    NecromancyPet,
    NecromancyZombie,
    NecromancySkeleton,
    NecromancySkeletonSwordsman,
    NecromancySkeletonArcherOrMage,
    IceMagicColdSphere,
    SummonedDeer,
    FireMagicFirewall,
    SummonedSpider,
    SummonedTrickFox,
    WeatherWitchingTornado,
    DruidHealingSanctuary,
    SpiritFoxPowerGlyph,
    FairyFaeConduit,
    BattleChemistryGolem,
    GiantBatDouble,
    WardenStunTrap,
}
