namespace PgJsonObjects
{
    public enum DamageType
    {
        Internal_None,
        Internal_Empty,
        Crushing,
        Slashing,
        Nature,
        Fire,
        Cold,
        Smiting,
        Piercing,
        Psychic,
        Trauma,
        Nothingness,
        Potion,
        Electricity,
        Poison,
        Acid,
        Darkness,
        Regeneration,
        Poison_direct,
        Trauma_direct,
        Poison_indirect,
        Trauma_indirect,
        Burst,
    }
}
