namespace PgObjects
{
    public enum PreEffect
    {
        Internal_None,
        CastigateUndeadDmgMod20,
        CastigateUndeadDmgMod40,
        CastigateUndeadDmgMod60,
        CastigateUndeadDmgMod80,
        CastigateUndeadDmgMod100,
        FlamestrikeUndeadDmgMod33,
        ResetTetheredSoul,
        FishGutFishMod100,
        SpadeAssaultPlantMod100,
        SuperZombie1,
        SuperZombie2,
        SuperZombie3,
        SuperZombie4,
        SuperZombie5,
        SuperZombie6,
        SuperZombie7,
        EndBardSong,
        MambaStrikeLowArmorDmgMod,
        SuperZombie8,
        LethalForceAnimalDmgMod,
        WeatherExtraDamageAgainstWeakenedA,
        WeatherExtraDamageAgainstWeakenedB,
        DampenToggleEveryOtherUse,
        TsunamiToggleEveryOtherUse,
        ShockingGraspToggleEveryOtherUse,
    }
}
