namespace PgObjects
{
    public enum Profile
    {
        Internal_None,
        Newb,
        All,
        CowFeet,
        DeerFeet,
        Shield,
        Dagger,
        Dirk,
        NewbSword,
        Sword,
        Lute,
        Horn,
        Staff,
        FireStaff,
        MeleeStaff,
        Beaker,
        Flask,
        Bow,
        Crossbow,
        FistWeapon,
        Claw,
        Belt,
        Orb,
        Club,
        Hammer,
    }
}
