namespace PgObjects
{
    public enum RecipeResultEffectType
    {
        Internal_None,
        Special,
        AddItemTSysPower,
        ExtractTSysPower,
        RepairItemDurability,
        CraftSimpleTSysItem,
        ConsumeItemUses,
        TSysCraftedEquipment,
        CraftingEnhanceItem,
        GiveTSysItem,
        CreateMiningSurvey,
        CreateGeologySurvey,
        Tiered,
        PermanentlyRaiseMaxTempestEnergy,
        SpawnPremonition,
        BrewItem,
        PolymorphRabbitPermanent,
        AddItemTSysPowerWax,
        DeltaCurFairyEnergy,
        Teleport,
        AdjustRecipeReuseTime,
        CraftingResetItem,
        SendItemToSaddlebag,
        TransmogItemAppearance,
    }
}
