namespace Pipeline.Test;

using System.Collections.Generic;
using Preprocessor;

public partial class PreprocessorTest
{
    private static List<JsonFile> JsonFileList = new()
    {
        new JsonFile("abilities",
                     true,
                     Preprocessor.PreprocessDictionary<AbilityDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<AbilityDictionary, Ability>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Ability>)(((AbilityDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Ability>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("abilitydynamicdots",
                     true,
                     Preprocessor.PreprocessArray<AbilityDynamicDotArray>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedList<AbilityDynamicDotArray, AbilityDynamicDot>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<AbilityDynamicDot>)content).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<AbilityDynamicDot>().WithLock().ToList()),
        new JsonFile("abilitydynamicspecialvalues",
                     true,
                     Preprocessor.PreprocessArray<AbilityDynamicSpecialValueArray>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedList<AbilityDynamicSpecialValueArray, AbilityDynamicSpecialValue>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<AbilityDynamicSpecialValue>)content).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<AbilityDynamicSpecialValue>().WithLock().ToList()),
        new JsonFile("abilitykeywords",
                     true,
                     Preprocessor.PreprocessArray<AbilityKeywordArray>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedList<AbilityKeywordArray, AbilityKeyword>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<AbilityKeyword>)content).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<AbilityKeyword>().WithLock().ToList()),
        new JsonFile("advancementtables",
                     true,
                     Preprocessor.PreprocessDictionary<AdvancementTableDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<AdvancementTableDictionary, AdvancementTable>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<AdvancementTable>)(((AdvancementTableDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<AdvancementTable>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("ai",
                     true,
                     Preprocessor.PreprocessDictionary<AIDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<AIDictionary, AI>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<AI>)(((AIDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<AI>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("areas",
                     true,
                     Preprocessor.PreprocessDictionary<AreaDictionary>, Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<AreaDictionary, Area>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Area>)(((AreaDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Area>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("attributes",
                     true,
                     Preprocessor.PreprocessDictionary<AttributeDictionary>,
                     Fixer.FixAttributes,
                     Preprocessor.SaveSerializedDictionary<AttributeDictionary, Attribute>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Attribute>)(((AttributeDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Attribute>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("directedgoals",
                     true,
                     Preprocessor.PreprocessDictionary<DirectedGoalDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<DirectedGoalDictionary, DirectedGoal>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<DirectedGoal>)(((DirectedGoalDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<DirectedGoal>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("effects",
                     true,
                     Preprocessor.PreprocessDictionary<EffectDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<EffectDictionary, Effect>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Effect>)(((EffectDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Effect>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("items",
                     true,
                     Preprocessor.PreprocessDictionary<ItemDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<ItemDictionary, Item>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Item>)(((ItemDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Item>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("itemuses",
                     true,
                     Preprocessor.PreprocessDictionary<ItemUseDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<ItemUseDictionary, ItemUse>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<ItemUse>)(((ItemUseDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<ItemUse>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("lorebookinfo",
                     true,
                     Preprocessor.PreprocessSingle<LoreBookInfo>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedSingle<LoreBookInfo>,
                     (IFreeSql fsql, object content) => fsql.Insert((LoreBookInfo)content).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<LoreBookInfo>().WithLock().First()),
        new JsonFile("lorebooks",
                     true,
                     Preprocessor.PreprocessDictionary<LoreBookDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<LoreBookDictionary, LoreBook>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<LoreBook>)(((LoreBookDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<LoreBook>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("npcs",
                     true,
                     Preprocessor.PreprocessDictionary<NpcDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<NpcDictionary, Npc>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Npc>)(((NpcDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Npc>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("playertitles",
                     true,
                     Preprocessor.PreprocessDictionary<PlayerTitleDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<PlayerTitleDictionary, PlayerTitle>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<PlayerTitle>)(((PlayerTitleDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<PlayerTitle>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("quests",
                     true,
                     Preprocessor.PreprocessDictionary<QuestDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<QuestDictionary, Quest>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Quest>)(((QuestDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Quest>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("recipes",
                     true,
                     Preprocessor.PreprocessDictionary<RecipeDictionary>,
                     Fixer.FixRecipes,
                     Preprocessor.SaveSerializedDictionary<RecipeDictionary, Recipe>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Recipe>)(((RecipeDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Recipe>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("skills",
                     true,
                     Preprocessor.PreprocessDictionary<SkillDictionary>,
                     Fixer.FixSkills,
                     Preprocessor.SaveSerializedDictionary<SkillDictionary, Skill>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Skill>)(((SkillDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Skill>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("sources_abilities",
                     true,
                     Preprocessor.PreprocessDictionary<SourceAbilityDictionary>,
                     Fixer.FixSourceAbilities,
                     Preprocessor.SaveSerializedDictionary<SourceAbilityDictionary, SourceAbility>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<SourceAbility>)(((SourceAbilityDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<SourceAbility>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("sources_items",
                     true,
                     Preprocessor.PreprocessDictionary<SourceItemDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<SourceItemDictionary, SourceItem>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<SourceItem>)(((SourceItemDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<SourceItem>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("sources_recipes",
                     true,
                     Preprocessor.PreprocessDictionary<SourceRecipeDictionary>,
                     Fixer.FixSourceRecipes,
                     Preprocessor.SaveSerializedDictionary<SourceRecipeDictionary, SourceRecipe>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<SourceRecipe>)(((SourceRecipeDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<SourceRecipe>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("storagevaults",
                     true,
                     Preprocessor.PreprocessDictionary<StorageVaultDictionary>,
                     Fixer.FixStorageVaults,
                     Preprocessor.SaveSerializedDictionary<StorageVaultDictionary, StorageVault>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<StorageVault>)(((StorageVaultDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<StorageVault>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("tsysclientinfo",
                     true,
                     Preprocessor.PreprocessDictionary<PowerDictionary>,
                     Fixer.FixPowers,
                     Preprocessor.SaveSerializedDictionary<PowerDictionary, Power>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Power>)(((PowerDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Power>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("tsysprofiles",
                     true,
                     Preprocessor.PreprocessDictionary<ProfileDictionary>,
                     Fixer.NoFix,
                     Preprocessor.SaveSerializedDictionary<ProfileDictionary, Profile>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<Profile>)(((ProfileDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<Profile>().WithLock().ToDictionary(item => item.Key)),
        new JsonFile("xptables",
                     true,
                     Preprocessor.PreprocessDictionary<XpTableDictionary>,
                     Fixer.FixXpTables,
                     Preprocessor.SaveSerializedDictionary<XpTableDictionary, XpTable>,
                     (IFreeSql fsql, object content) => fsql.Insert((IEnumerable<XpTable>)(((XpTableDictionary)content).Values)).ExecuteAffrows(),
                     (IFreeSql fsql) => fsql.Select<XpTable>().WithLock().ToDictionary(item => item.Key)),
    };
}
