namespace PgJsonObjects
{
    public class PgAIAbilitySet : GenericPgObject<PgAIAbilitySet>, IPgAIAbilitySet
    {
        public PgAIAbilitySet(byte[] data, int offset)
            : base(data, offset)
        {
        }

        protected override PgAIAbilitySet CreateItem(byte[] data, int offset)
        {
            return new PgAIAbilitySet(data, offset);
        }

        private AIAbility[] Abilities = new AIAbility[100];
        private AIAbility GetAbilityObject(int index) { return GetObject(index * 4, ref Abilities[index]); }

        public AIAbility AnimalBite { get { return GetAbilityObject(0); } }
        public AIAbility AnimalClaw { get { return GetAbilityObject(1); } }
        public AIAbility AnimalOmegaBite { get { return GetAbilityObject(2); } }
        public AIAbility AnimalOmegaBite2 { get { return GetAbilityObject(3); } }
        public AIAbility AnimalHoofFrontKick { get { return GetAbilityObject(4); } }
        public AIAbility AnimalHoofRageKick { get { return GetAbilityObject(5); } }
        public AIAbility AnimalHoofRageKick2 { get { return GetAbilityObject(6); } }
        public AIAbility AnimalHoofFieryFrontKick { get { return GetAbilityObject(7); } }
        public AIAbility AnimalHoofFieryFrontKick2 { get { return GetAbilityObject(8); } }
        public AIAbility ElectricPigHitAndRun { get { return GetAbilityObject(9); } }
        public AIAbility ElectricPigStun { get { return GetAbilityObject(10); } }
        public AIAbility ElectricPigAoEStun { get { return GetAbilityObject(11); } }
        public AIAbility LamiaMindControl { get { return GetAbilityObject(12); } }
        public AIAbility LamiaRage { get { return GetAbilityObject(13); } }
        public AIAbility SlimeKick { get { return GetAbilityObject(14); } }
        public AIAbility SlimeKickB { get { return GetAbilityObject(15); } }
        public AIAbility SlimeBite { get { return GetAbilityObject(16); } }
        public AIAbility SlimeBiteB { get { return GetAbilityObject(17); } }
        public AIAbility Slime_SummonSlime { get { return GetAbilityObject(18); } }
        public AIAbility SlimeSpit { get { return GetAbilityObject(19); } }
        public AIAbility SlimeSuperSpit { get { return GetAbilityObject(20); } }
        public AIAbility IceSlimeKick { get { return GetAbilityObject(21); } }
        public AIAbility IceSlimeKickB { get { return GetAbilityObject(22); } }
        public AIAbility IceSlimeBite { get { return GetAbilityObject(23); } }
        public AIAbility IceSlimeBiteB { get { return GetAbilityObject(24); } }
        public AIAbility BossSlimeKick { get { return GetAbilityObject(25); } }
        public AIAbility BossSlimeKickB { get { return GetAbilityObject(26); } }
        public AIAbility BossSlime_SummonSlime1 { get { return GetAbilityObject(27); } }
        public AIAbility BossSlimeKick2 { get { return GetAbilityObject(28); } }
        public AIAbility BossSlimeKick2B { get { return GetAbilityObject(29); } }
        public AIAbility BossSlime_SummonSlime4Elite { get { return GetAbilityObject(30); } }
        public AIAbility AnimalHeal { get { return GetAbilityObject(31); } }
        public AIAbility AnimalHeal2 { get { return GetAbilityObject(32); } }
        public AIAbility AnimalHeal3 { get { return GetAbilityObject(33); } }
        public AIAbility IceCockPeck { get { return GetAbilityObject(34); } }
        public AIAbility IceCockFreeze { get { return GetAbilityObject(35); } }
        public AIAbility NightmareHoof { get { return GetAbilityObject(36); } }
        public AIAbility NightmareDarknessBomb { get { return GetAbilityObject(37); } }
        public AIAbility CiervosNightmareHoof { get { return GetAbilityObject(38); } }
        public AIAbility CiervosDarknessBomb { get { return GetAbilityObject(39); } }
        public AIAbility Myconian_Bash { get { return GetAbilityObject(40); } }
        public AIAbility Myconian_Mindspores { get { return GetAbilityObject(41); } }
        public AIAbility Myconian_Drain { get { return GetAbilityObject(42); } }
        public AIAbility Myconian_BossBash { get { return GetAbilityObject(43); } }
        public AIAbility Myconian_Mindspores_Permanent { get { return GetAbilityObject(44); } }
        public AIAbility Myconian_TidalCurse { get { return GetAbilityObject(45); } }
        public AIAbility Myconian_Shock { get { return GetAbilityObject(46); } }
        public AIAbility AlienDog_Punch { get { return GetAbilityObject(47); } }
        public AIAbility AlienDog_Punch2 { get { return GetAbilityObject(48); } }
        public AIAbility AlienDog_RagePunch { get { return GetAbilityObject(49); } }
        public AIAbility MushroomMonster_Bite { get { return GetAbilityObject(50); } }
        public AIAbility MushroomMonster_Spit1 { get { return GetAbilityObject(51); } }
        public AIAbility MushroomMonster_Spit2 { get { return GetAbilityObject(52); } }
        public AIAbility MushroomMonster_SummonMushroomSpawn1 { get { return GetAbilityObject(53); } }
        public AIAbility MushroomMonster_SummonMushroomSpawn2 { get { return GetAbilityObject(54); } }
        public AIAbility MushroomMonster_SummonMushroomSpawn3 { get { return GetAbilityObject(55); } }
        public AIAbility MushroomMonster_SpawnSpit1 { get { return GetAbilityObject(56); } }
        public AIAbility MushroomMonster_SpawnSpit2 { get { return GetAbilityObject(57); } }
        public AIAbility MushroomMonster_SpawnSuperSpit1 { get { return GetAbilityObject(58); } }
        public AIAbility MushroomMonster_SpawnSuperSpit2 { get { return GetAbilityObject(59); } }
        public AIAbility MaronesaStomp { get { return GetAbilityObject(60); } }
        public AIAbility MaronesaInfect { get { return GetAbilityObject(61); } }
        public AIAbility WormBite1 { get { return GetAbilityObject(62); } }
        public AIAbility WormSpit1 { get { return GetAbilityObject(63); } }
        public AIAbility WormShove1 { get { return GetAbilityObject(64); } }
        public AIAbility WormInfect1 { get { return GetAbilityObject(65); } }
        public AIAbility WormSpit2 { get { return GetAbilityObject(66); } }
        public AIAbility WormBossSpit { get { return GetAbilityObject(67); } }
        public AIAbility WormBossAcidBurst { get { return GetAbilityObject(68); } }
        public AIAbility GnasherBite { get { return GetAbilityObject(69); } }
        public AIAbility GnasherRend { get { return GetAbilityObject(70); } }
        public AIAbility Dinoslash { get { return GetAbilityObject(71); } }
        public AIAbility Dinoslash2 { get { return GetAbilityObject(72); } }
        public AIAbility Dinobite { get { return GetAbilityObject(73); } }
        public AIAbility Dinobite2 { get { return GetAbilityObject(74); } }
        public AIAbility Dinowhap { get { return GetAbilityObject(75); } }
        public AIAbility Peck { get { return GetAbilityObject(76); } }
        public AIAbility AnimalFlee { get { return GetAbilityObject(77); } }
        public AIAbility HippogriffPeck { get { return GetAbilityObject(78); } }
        public AIAbility HippogriffSlashes { get { return GetAbilityObject(79); } }
        public AIAbility HippogriffBossSlashes { get { return GetAbilityObject(80); } }
        public AIAbility RatBite { get { return GetAbilityObject(81); } }
        public AIAbility RatClaw { get { return GetAbilityObject(82); } }
        public AIAbility FireRatBite { get { return GetAbilityObject(83); } }
        public AIAbility FireRatClaw { get { return GetAbilityObject(84); } }
        public AIAbility GoblinZapBall { get { return GetAbilityObject(85); } }
        public AIAbility GoblinHateZapBall { get { return GetAbilityObject(86); } }
        public AIAbility GoblinHateZapBall2 { get { return GetAbilityObject(87); } }
        public AIAbility RhinoHorn { get { return GetAbilityObject(88); } }
        public AIAbility RhinoRage { get { return GetAbilityObject(89); } }
        public AIAbility RhinoFireball { get { return GetAbilityObject(90); } }
        public AIAbility RhinoBossRage { get { return GetAbilityObject(91); } }
        public AIAbility YetiPunch { get { return GetAbilityObject(92); } }
        public AIAbility YetiEncase { get { return GetAbilityObject(93); } }
        public AIAbility YetiDebuff { get { return GetAbilityObject(94); } }
        public AIAbility YetiBoulderThrow { get { return GetAbilityObject(95); } }
        public AIAbility YetiBarrage { get { return GetAbilityObject(96); } }
        public AIAbility YetiRoarStun { get { return GetAbilityObject(97); } }
        public AIAbility YetiFlingAway { get { return GetAbilityObject(98); } }
        public AIAbility YetiIceBallThrow { get { return GetAbilityObject(99); } }
        public AIAbility YetiIceSpear { get { return GetAbilityObject(100); } }
        public AIAbility YetiColdOrb { get { return GetAbilityObject(101); } }
        public AIAbility YetiFrostRing { get { return GetAbilityObject(102); } }
        public AIAbility WorgBite { get { return GetAbilityObject(103); } }
        public AIAbility WorgOmegaBite { get { return GetAbilityObject(104); } }
        public AIAbility BearBite { get { return GetAbilityObject(105); } }
        public AIAbility BearCrush { get { return GetAbilityObject(106); } }
        public AIAbility BrainBite { get { return GetAbilityObject(107); } }
        public AIAbility BrainDrain { get { return GetAbilityObject(108); } }
        public AIAbility BrainDrain2 { get { return GetAbilityObject(109); } }
        public AIAbility BigCatClaw { get { return GetAbilityObject(110); } }
        public AIAbility BigCatPounce { get { return GetAbilityObject(111); } }
        public AIAbility BigCatRagePounce { get { return GetAbilityObject(112); } }
        public AIAbility BigCatDebuff { get { return GetAbilityObject(113); } }
        public AIAbility SpiderBite { get { return GetAbilityObject(114); } }
        public AIAbility SpiderFireball { get { return GetAbilityObject(115); } }
        public AIAbility SpiderBossFreePin { get { return GetAbilityObject(116); } }
        public AIAbility SpiderKill2 { get { return GetAbilityObject(117); } }
        public AIAbility SpiderInject { get { return GetAbilityObject(118); } }
        public AIAbility SpiderKill { get { return GetAbilityObject(119); } }
        public AIAbility AcidBall1 { get { return GetAbilityObject(120); } }
        public AIAbility SpiderPin { get { return GetAbilityObject(121); } }
        public AIAbility SpiderKill3 { get { return GetAbilityObject(122); } }
        public AIAbility AcidBall2 { get { return GetAbilityObject(123); } }
        public AIAbility AcidSpew1 { get { return GetAbilityObject(124); } }
        public AIAbility AcidExplosion1 { get { return GetAbilityObject(125); } }
        public AIAbility AcidExplosion2 { get { return GetAbilityObject(126); } }
        public AIAbility SpiderIncubate { get { return GetAbilityObject(127); } }
        public AIAbility MantisClaw { get { return GetAbilityObject(128); } }
        public AIAbility MantisRage { get { return GetAbilityObject(129); } }
        public AIAbility MantisAcidBurst { get { return GetAbilityObject(130); } }
        public AIAbility SherzatClaw { get { return GetAbilityObject(131); } }
        public AIAbility SherzatAcidSpit { get { return GetAbilityObject(132); } }
        public AIAbility SherzatDisintegrate { get { return GetAbilityObject(133); } }
        public AIAbility MantisSwipe { get { return GetAbilityObject(134); } }
        public AIAbility MantisBlast { get { return GetAbilityObject(135); } }
        public AIAbility SnailStrike { get { return GetAbilityObject(136); } }
        public AIAbility SnailRage { get { return GetAbilityObject(137); } }
        public AIAbility SnailRageB { get { return GetAbilityObject(138); } }
        public AIAbility SnailRageC { get { return GetAbilityObject(139); } }
        public AIAbility HookClaw { get { return GetAbilityObject(140); } }
        public AIAbility HookAcid { get { return GetAbilityObject(141); } }
        public AIAbility HookRage { get { return GetAbilityObject(142); } }
        public AIAbility UndeadSword1 { get { return GetAbilityObject(143); } }
        public AIAbility UndeadSword2 { get { return GetAbilityObject(144); } }
        public AIAbility UndeadSwordAngry { get { return GetAbilityObject(145); } }
        public AIAbility UndeadMegaSword1 { get { return GetAbilityObject(146); } }
        public AIAbility UndeadMegaSword2 { get { return GetAbilityObject(147); } }
        public AIAbility UndeadMegaSwordAngry { get { return GetAbilityObject(148); } }
        public AIAbility UndeadLightningSmite { get { return GetAbilityObject(149); } }
        public AIAbility UndeadPhysicalShield { get { return GetAbilityObject(150); } }
        public AIAbility UndeadSword1B { get { return GetAbilityObject(151); } }
        public AIAbility UndeadFireballA { get { return GetAbilityObject(152); } }
        public AIAbility UndeadFireballB { get { return GetAbilityObject(153); } }
        public AIAbility UndeadFireballB2 { get { return GetAbilityObject(154); } }
        public AIAbility UndeadIceBall1 { get { return GetAbilityObject(155); } }
        public AIAbility UndeadFreezeBall { get { return GetAbilityObject(156); } }
        public AIAbility UndeadFireballLongA { get { return GetAbilityObject(157); } }
        public AIAbility UndeadFireballLongB { get { return GetAbilityObject(158); } }
        public AIAbility UndeadFireballLongB2 { get { return GetAbilityObject(159); } }
        public AIAbility KhyrulekCurseBall { get { return GetAbilityObject(160); } }
        public AIAbility UrsulaFireball1 { get { return GetAbilityObject(161); } }
        public AIAbility UrsulaFireball1B { get { return GetAbilityObject(162); } }
        public AIAbility UrsulaFireball2 { get { return GetAbilityObject(163); } }
        public AIAbility UrsulaIceball1 { get { return GetAbilityObject(164); } }
        public AIAbility UrsulaIceball1B { get { return GetAbilityObject(165); } }
        public AIAbility UrsulaIceball2 { get { return GetAbilityObject(166); } }
        public AIAbility UrsulaSummon { get { return GetAbilityObject(167); } }
        public AIAbility UrsulaRage { get { return GetAbilityObject(168); } }
        public AIAbility UndeadFireballA2 { get { return GetAbilityObject(169); } }
        public AIAbility BigHeadCurseball { get { return GetAbilityObject(170); } }
        public AIAbility UndeadArrow1 { get { return GetAbilityObject(171); } }
        public AIAbility UndeadArrow2 { get { return GetAbilityObject(172); } }
        public AIAbility UndeadOmegaArrow { get { return GetAbilityObject(173); } }
        public AIAbility PetUndeadArrow1 { get { return GetAbilityObject(174); } }
        public AIAbility PetUndeadArrow2 { get { return GetAbilityObject(175); } }
        public AIAbility PetUndeadOmegaArrow { get { return GetAbilityObject(176); } }
        public AIAbility UndeadGrappleArrow1 { get { return GetAbilityObject(177); } }
        public AIAbility UndeadSelfDestruct { get { return GetAbilityObject(178); } }
        public AIAbility UndeadDarknessBall { get { return GetAbilityObject(179); } }
        public AIAbility UndeadBoneWhirlwind { get { return GetAbilityObject(180); } }
        public AIAbility PetUndeadSword1 { get { return GetAbilityObject(181); } }
        public AIAbility PetUndeadSword2 { get { return GetAbilityObject(182); } }
        public AIAbility PetUndeadSwordAngry { get { return GetAbilityObject(183); } }
        public AIAbility PetUndeadFireballA { get { return GetAbilityObject(184); } }
        public AIAbility PetUndeadFireballB { get { return GetAbilityObject(185); } }
        public AIAbility PetUndeadDefensiveBurst { get { return GetAbilityObject(186); } }
        public AIAbility PetUndeadPunch1 { get { return GetAbilityObject(187); } }
        public AIAbility ZombiePunch { get { return GetAbilityObject(188); } }
        public AIAbility ZombieBite { get { return GetAbilityObject(189); } }
        public AIAbility GoblinSpear1 { get { return GetAbilityObject(190); } }
        public AIAbility GoblinSpear2 { get { return GetAbilityObject(191); } }
        public AIAbility GoblinRageSpear1 { get { return GetAbilityObject(192); } }
        public AIAbility GoblinRageSpear2 { get { return GetAbilityObject(193); } }
        public AIAbility GoblinHeal1 { get { return GetAbilityObject(194); } }
        public AIAbility GoblinHeal2 { get { return GetAbilityObject(195); } }
        public AIAbility GoblinPunch { get { return GetAbilityObject(196); } }
        public AIAbility GoblinArrow1 { get { return GetAbilityObject(197); } }
        public AIAbility GoblinArrow2 { get { return GetAbilityObject(198); } }
        public AIAbility GoblinRageArrow1 { get { return GetAbilityObject(199); } }
        public AIAbility GoblinRageArrow2 { get { return GetAbilityObject(200); } }
        public AIAbility GoblinSpreadZapBall { get { return GetAbilityObject(201); } }
        public AIAbility GoblinBossLightning { get { return GetAbilityObject(202); } }
        public AIAbility GoblinArmorBuff { get { return GetAbilityObject(203); } }
        public AIAbility MummySlamA { get { return GetAbilityObject(204); } }
        public AIAbility MummySlamB { get { return GetAbilityObject(205); } }
        public AIAbility MummySlamCombo { get { return GetAbilityObject(206); } }
        public AIAbility MummyWrapA { get { return GetAbilityObject(207); } }
        public AIAbility MummyWrapB { get { return GetAbilityObject(208); } }
        public AIAbility MummyWrapRage { get { return GetAbilityObject(209); } }
        public AIAbility BarutiWrapA { get { return GetAbilityObject(210); } }
        public AIAbility BarutiWrapB { get { return GetAbilityObject(211); } }
        public AIAbility BarutiWrapRage { get { return GetAbilityObject(212); } }
        public AIAbility FireWallAttack1 { get { return GetAbilityObject(213); } }
        public AIAbility FireWallDotAttack1 { get { return GetAbilityObject(214); } }
        public AIAbility FireSnakeExplosion1 { get { return GetAbilityObject(215); } }
        public AIAbility FireTrapAttack1 { get { return GetAbilityObject(216); } }
        public AIAbility HealingAura1 { get { return GetAbilityObject(217); } }
        public AIAbility HealingAura2 { get { return GetAbilityObject(218); } }
        public AIAbility HealingAura3 { get { return GetAbilityObject(219); } }
        public AIAbility HealingAura4 { get { return GetAbilityObject(220); } }
        public AIAbility DruidHealingSanctuaryHeal { get { return GetAbilityObject(221); } }
        public AIAbility AcidAuraBall1 { get { return GetAbilityObject(222); } }
        public AIAbility AcidAuraBall2 { get { return GetAbilityObject(223); } }
        public AIAbility AcidAuraBall3 { get { return GetAbilityObject(224); } }
        public AIAbility AcidAuraBall4 { get { return GetAbilityObject(225); } }
        public AIAbility ElectricityAura1 { get { return GetAbilityObject(226); } }
        public AIAbility ElectricityAuraBolt1 { get { return GetAbilityObject(227); } }
        public AIAbility ReboundAura1 { get { return GetAbilityObject(228); } }
        public AIAbility ColdAuraBurst { get { return GetAbilityObject(229); } }
        public AIAbility WebStick { get { return GetAbilityObject(230); } }
        public AIAbility IcySlam { get { return GetAbilityObject(231); } }
        public AIAbility IcyCocoon { get { return GetAbilityObject(232); } }
        public AIAbility IcyCocoon2 { get { return GetAbilityObject(233); } }
        public AIAbility ElementalSlam { get { return GetAbilityObject(234); } }
        public AIAbility ElementalBees { get { return GetAbilityObject(235); } }
        public AIAbility ElementalBees2 { get { return GetAbilityObject(236); } }
        public AIAbility FaeLightningSmite { get { return GetAbilityObject(237); } }
        public AIAbility TotalHorrorAttack { get { return GetAbilityObject(238); } }
        public AIAbility TotalHorrorStretch { get { return GetAbilityObject(239); } }
        public AIAbility TotalHorrorHeal { get { return GetAbilityObject(240); } }
        public AIAbility TotalHorrorHeal2 { get { return GetAbilityObject(241); } }
        public AIAbility SheepBomb1 { get { return GetAbilityObject(242); } }
        public AIAbility SlugPoisonBite { get { return GetAbilityObject(243); } }
        public AIAbility SlugPoisonRage { get { return GetAbilityObject(244); } }
        public AIAbility SlugPoisonBite2 { get { return GetAbilityObject(245); } }
        public AIAbility SlugPoisonRage2 { get { return GetAbilityObject(246); } }
        public AIAbility SlugPoisonBite3 { get { return GetAbilityObject(247); } }
        public AIAbility SlugPoisonRage3 { get { return GetAbilityObject(248); } }
        public AIAbility TornadoJolt1 { get { return GetAbilityObject(249); } }
        public AIAbility TornadoFling { get { return GetAbilityObject(250); } }
        public AIAbility TornadoToss { get { return GetAbilityObject(251); } }
        public AIAbility TheFogCurse { get { return GetAbilityObject(252); } }
        public AIAbility MonsterWerewolfPouncingRake { get { return GetAbilityObject(253); } }
        public AIAbility MonsterWerewolfPackAttack { get { return GetAbilityObject(254); } }
        public AIAbility MonsterWerewolfHowl { get { return GetAbilityObject(255); } }
        public AIAbility Werewolf_Summon_Rage { get { return GetAbilityObject(256); } }
        public AIAbility Werewolf_Summon_Opener { get { return GetAbilityObject(257); } }
        public AIAbility BleddynHowl { get { return GetAbilityObject(258); } }
        public AIAbility OrcSwordSlash { get { return GetAbilityObject(259); } }
        public AIAbility OrcParry { get { return GetAbilityObject(260); } }
        public AIAbility OrcFinishingBlow { get { return GetAbilityObject(261); } }
        public AIAbility OrcHipThrow { get { return GetAbilityObject(262); } }
        public AIAbility OrcKneeKick { get { return GetAbilityObject(263); } }
        public AIAbility OrcPunch { get { return GetAbilityObject(264); } }
        public AIAbility OrcArrow1 { get { return GetAbilityObject(265); } }
        public AIAbility OrcArrow2 { get { return GetAbilityObject(266); } }
        public AIAbility OrcStaffSmash { get { return GetAbilityObject(267); } }
        public AIAbility OrcFireball { get { return GetAbilityObject(268); } }
        public AIAbility OrcHeal1 { get { return GetAbilityObject(269); } }
        public AIAbility OrcHeal2 { get { return GetAbilityObject(270); } }
        public AIAbility OrcEvasionBubble { get { return GetAbilityObject(271); } }
        public AIAbility OrcElectricStun { get { return GetAbilityObject(272); } }
        public AIAbility OrcFireBolts { get { return GetAbilityObject(273); } }
        public AIAbility OrcKnockbackBolt { get { return GetAbilityObject(274); } }
        public AIAbility OrcSummonUrak2 { get { return GetAbilityObject(275); } }
        public AIAbility OrcSwordSlashFire { get { return GetAbilityObject(276); } }
        public AIAbility OrcParryFire { get { return GetAbilityObject(277); } }
        public AIAbility OrcFinishingBlowFire { get { return GetAbilityObject(278); } }
        public AIAbility OrcSummonSigil1 { get { return GetAbilityObject(279); } }
        public AIAbility OrcSpearAttack { get { return GetAbilityObject(280); } }
        public AIAbility OrcHalberdAttack { get { return GetAbilityObject(281); } }
        public AIAbility OrcAreaHalberdAttack { get { return GetAbilityObject(282); } }
        public AIAbility OrcDebuffArrow { get { return GetAbilityObject(283); } }
        public AIAbility OrcSlice { get { return GetAbilityObject(284); } }
        public AIAbility OrcVenomstrike1 { get { return GetAbilityObject(285); } }
        public AIAbility OrcVenomstrike0 { get { return GetAbilityObject(286); } }
        public AIAbility OrcLieutenantDebuffTaunt { get { return GetAbilityObject(287); } }
        public AIAbility OrcAreaHalberdBoss { get { return GetAbilityObject(288); } }
        public AIAbility OrcDeathsHold { get { return GetAbilityObject(289); } }
        public AIAbility GazlukPriest1Special { get { return GetAbilityObject(290); } }
        public AIAbility GazlukPriest2Special { get { return GetAbilityObject(291); } }
        public AIAbility GazlukPriest3Special { get { return GetAbilityObject(292); } }
        public AIAbility OrcExtinguishLife { get { return GetAbilityObject(293); } }
        public AIAbility OrcDarknessBall { get { return GetAbilityObject(294); } }
        public AIAbility OrcWaveOfDarkness { get { return GetAbilityObject(295); } }
        public AIAbility EnemyMinigolemPunch { get { return GetAbilityObject(296); } }
        public AIAbility EnemyMinigolemHeal { get { return GetAbilityObject(297); } }
        public AIAbility EnemyMinigolemExplode { get { return GetAbilityObject(298); } }
        public AIAbility MinigolemBombToss { get { return GetAbilityObject(299); } }
        public AIAbility MinigolemBombToss2 { get { return GetAbilityObject(300); } }
        public AIAbility MinigolemBombToss3 { get { return GetAbilityObject(301); } }
        public AIAbility MinigolemBombToss4 { get { return GetAbilityObject(302); } }
        public AIAbility MinigolemBombToss5 { get { return GetAbilityObject(303); } }
        public AIAbility MinigolemAoEHeal { get { return GetAbilityObject(304); } }
        public AIAbility MinigolemAoEHeal2 { get { return GetAbilityObject(305); } }
        public AIAbility MinigolemAoEHeal3 { get { return GetAbilityObject(306); } }
        public AIAbility MinigolemAoEHeal4 { get { return GetAbilityObject(307); } }
        public AIAbility MinigolemAoEHeal5 { get { return GetAbilityObject(308); } }
        public AIAbility MinigolemSelfDestruct { get { return GetAbilityObject(309); } }
        public AIAbility MinigolemSelfDestruct2 { get { return GetAbilityObject(310); } }
        public AIAbility MinigolemSelfDestruct3 { get { return GetAbilityObject(311); } }
        public AIAbility MinigolemSelfDestruct4 { get { return GetAbilityObject(312); } }
        public AIAbility MinigolemSelfDestruct5 { get { return GetAbilityObject(313); } }
        public AIAbility MinigolemAoEPower { get { return GetAbilityObject(314); } }
        public AIAbility MinigolemAoEPower2 { get { return GetAbilityObject(315); } }
        public AIAbility MinigolemAoEPower3 { get { return GetAbilityObject(316); } }
        public AIAbility MinigolemAoEPower4 { get { return GetAbilityObject(317); } }
        public AIAbility MinigolemAoEPower5 { get { return GetAbilityObject(318); } }
        public AIAbility MinigolemHeal { get { return GetAbilityObject(319); } }
        public AIAbility MinigolemHeal2 { get { return GetAbilityObject(320); } }
        public AIAbility MinigolemHeal3 { get { return GetAbilityObject(321); } }
        public AIAbility MinigolemHeal4 { get { return GetAbilityObject(322); } }
        public AIAbility MinigolemHeal5 { get { return GetAbilityObject(323); } }
        public AIAbility MinigolemDoomAdmixture { get { return GetAbilityObject(324); } }
        public AIAbility MinigolemDoomAdmixture2 { get { return GetAbilityObject(325); } }
        public AIAbility MinigolemDoomAdmixture3 { get { return GetAbilityObject(326); } }
        public AIAbility MinigolemDoomAdmixture4 { get { return GetAbilityObject(327); } }
        public AIAbility MinigolemDoomAdmixture5 { get { return GetAbilityObject(328); } }
        public AIAbility MinigolemSelfSacrifice { get { return GetAbilityObject(329); } }
        public AIAbility MinigolemSelfSacrifice2 { get { return GetAbilityObject(330); } }
        public AIAbility MinigolemSelfSacrifice3 { get { return GetAbilityObject(331); } }
        public AIAbility MinigolemSelfSacrifice4 { get { return GetAbilityObject(332); } }
        public AIAbility MinigolemSelfSacrifice5 { get { return GetAbilityObject(333); } }
        public AIAbility MinigolemPunch { get { return GetAbilityObject(334); } }
        public AIAbility MinigolemPunch2 { get { return GetAbilityObject(335); } }
        public AIAbility MinigolemPunch3 { get { return GetAbilityObject(336); } }
        public AIAbility MinigolemPunch4 { get { return GetAbilityObject(337); } }
        public AIAbility MinigolemPunch5 { get { return GetAbilityObject(338); } }
        public AIAbility MinigolemHasteConcoction1 { get { return GetAbilityObject(339); } }
        public AIAbility MinigolemHasteConcoction2 { get { return GetAbilityObject(340); } }
        public AIAbility MinigolemHasteConcoction3 { get { return GetAbilityObject(341); } }
        public AIAbility MinigolemFireBalm1 { get { return GetAbilityObject(342); } }
        public AIAbility MinigolemFireBalm2 { get { return GetAbilityObject(343); } }
        public AIAbility MinigolemFireBalm3 { get { return GetAbilityObject(344); } }
        public AIAbility MinigolemFireBalm4 { get { return GetAbilityObject(345); } }
        public AIAbility MinigolemFireBalm5 { get { return GetAbilityObject(346); } }
        public AIAbility MinigolemRageAoEHeal1 { get { return GetAbilityObject(347); } }
        public AIAbility MinigolemRageAoEHeal2 { get { return GetAbilityObject(348); } }
        public AIAbility MinigolemRageAoEHeal3 { get { return GetAbilityObject(349); } }
        public AIAbility MinigolemRageAoEHeal4 { get { return GetAbilityObject(350); } }
        public AIAbility MinigolemRageAoEHeal5 { get { return GetAbilityObject(351); } }
        public AIAbility MinigolemRageAcidToss1 { get { return GetAbilityObject(352); } }
        public AIAbility MinigolemRageAcidToss2 { get { return GetAbilityObject(353); } }
        public AIAbility MinigolemRageAcidToss3 { get { return GetAbilityObject(354); } }
        public AIAbility MinigolemRageAcidToss4 { get { return GetAbilityObject(355); } }
        public AIAbility MinigolemRageAcidToss5 { get { return GetAbilityObject(356); } }
        public AIAbility TrainingGolemPunch { get { return GetAbilityObject(357); } }
        public AIAbility TrainingGolemStun { get { return GetAbilityObject(358); } }
        public AIAbility TrainingGolemHeal { get { return GetAbilityObject(359); } }
        public AIAbility TrainingGolemHealB { get { return GetAbilityObject(360); } }
        public AIAbility TrainingGolemFireBreath { get { return GetAbilityObject(361); } }
        public AIAbility TrainingGolemFireBurst { get { return GetAbilityObject(362); } }
        public AIAbility GrimalkinClaw { get { return GetAbilityObject(363); } }
        public AIAbility GrimalkinBite { get { return GetAbilityObject(364); } }
        public AIAbility GrimalkinPuncture { get { return GetAbilityObject(365); } }
        public AIAbility WerewolfSword1 { get { return GetAbilityObject(366); } }
        public AIAbility WerewolfSword2 { get { return GetAbilityObject(367); } }
        public AIAbility WerewolfSwordStun { get { return GetAbilityObject(368); } }
        public AIAbility WerewolfArrow1 { get { return GetAbilityObject(369); } }
        public AIAbility WerewolfArrow2 { get { return GetAbilityObject(370); } }
        public AIAbility WerewolfOmegaArrow { get { return GetAbilityObject(371); } }
        public AIAbility NpcSmash { get { return GetAbilityObject(372); } }
        public AIAbility NpcDoubleHitCurse { get { return GetAbilityObject(373); } }
        public AIAbility NpcBlockingStance { get { return GetAbilityObject(374); } }
        public AIAbility NpcHeadcracker { get { return GetAbilityObject(375); } }
        public AIAbility StrigaClawA { get { return GetAbilityObject(376); } }
        public AIAbility StrigaClawB { get { return GetAbilityObject(377); } }
        public AIAbility StrigaReap { get { return GetAbilityObject(378); } }
        public AIAbility StrigaReap2 { get { return GetAbilityObject(379); } }
        public AIAbility StrigaFireBreath { get { return GetAbilityObject(380); } }
        public AIAbility StrigaBuff { get { return GetAbilityObject(381); } }
        public AIAbility GhostlyPunchA { get { return GetAbilityObject(382); } }
        public AIAbility GhostlyPunchB { get { return GetAbilityObject(383); } }
        public AIAbility GhostlyBurst { get { return GetAbilityObject(384); } }
        public AIAbility GhostlyBossPunchA { get { return GetAbilityObject(385); } }
        public AIAbility GhostlyBossPunchB { get { return GetAbilityObject(386); } }
        public AIAbility GhostlyBossBurst { get { return GetAbilityObject(387); } }
        public AIAbility GhostlyBolt { get { return GetAbilityObject(388); } }
        public AIAbility InjectorBugBite { get { return GetAbilityObject(389); } }
        public AIAbility InjectorBugInject { get { return GetAbilityObject(390); } }
        public AIAbility InjectorBugInject2 { get { return GetAbilityObject(391); } }
        public AIAbility FaceOfDeathKill { get { return GetAbilityObject(392); } }
        public AIAbility WatcherFireball { get { return GetAbilityObject(393); } }
        public AIAbility WatcherSlap { get { return GetAbilityObject(394); } }
        public AIAbility WatcherAcidball { get { return GetAbilityObject(395); } }
        public AIAbility RedCrystalBlast { get { return GetAbilityObject(396); } }
        public AIAbility RedCrystalBurst { get { return GetAbilityObject(397); } }
        public AIAbility TurretCrystalZap { get { return GetAbilityObject(398); } }
        public AIAbility TurretCrystalZap2 { get { return GetAbilityObject(399); } }
        public AIAbility TurretCrystalZapLongRange { get { return GetAbilityObject(400); } }
        public AIAbility TurretCrystalZapLongRange2 { get { return GetAbilityObject(401); } }
        public AIAbility DeathRay { get { return GetAbilityObject(402); } }
        public AIAbility SpyPortalZap { get { return GetAbilityObject(403); } }
        public AIAbility SpyPortalZap2 { get { return GetAbilityObject(404); } }
        public AIAbility BitingVineBite { get { return GetAbilityObject(405); } }
        public AIAbility BitingVineSpit { get { return GetAbilityObject(406); } }
        public AIAbility BitingVineSpitB { get { return GetAbilityObject(407); } }
        public AIAbility BitingVineCast { get { return GetAbilityObject(408); } }
        public AIAbility BitingVineAppear { get { return GetAbilityObject(409); } }
        public AIAbility BitingVineDisappear { get { return GetAbilityObject(410); } }
        public AIAbility TrollClubA { get { return GetAbilityObject(411); } }
        public AIAbility TrollClubB { get { return GetAbilityObject(412); } }
        public AIAbility TrollKnockdown { get { return GetAbilityObject(413); } }
        public AIAbility OgreClubA { get { return GetAbilityObject(414); } }
        public AIAbility OgreClubB { get { return GetAbilityObject(415); } }
        public AIAbility OgreThrow { get { return GetAbilityObject(416); } }
        public AIAbility OgreStun { get { return GetAbilityObject(417); } }
        public AIAbility FaeSwordA { get { return GetAbilityObject(418); } }
        public AIAbility FaeSwordB { get { return GetAbilityObject(419); } }
        public AIAbility FaeSwordKill { get { return GetAbilityObject(420); } }
        public AIAbility DementiaPuckCurse { get { return GetAbilityObject(421); } }
        public AIAbility FaeLightningSmiteHidden { get { return GetAbilityObject(422); } }
        public AIAbility NecroSpark { get { return GetAbilityObject(423); } }
        public AIAbility NecroDarknessWave { get { return GetAbilityObject(424); } }
        public AIAbility NecroPainBubble { get { return GetAbilityObject(425); } }
        public AIAbility NecroSparkPerching { get { return GetAbilityObject(426); } }
        public AIAbility NecroDeathsHold { get { return GetAbilityObject(427); } }
        public AIAbility DroachBiteA { get { return GetAbilityObject(428); } }
        public AIAbility DroachBiteB { get { return GetAbilityObject(429); } }
        public AIAbility DroachFireball { get { return GetAbilityObject(430); } }
        public AIAbility DroachFireballPerching { get { return GetAbilityObject(431); } }
        public AIAbility DroachBreatheFire { get { return GetAbilityObject(432); } }
        public AIAbility DroachLightning { get { return GetAbilityObject(433); } }
        public AIAbility DroachLightningPerching { get { return GetAbilityObject(434); } }
        public AIAbility DroachShockingKnockback { get { return GetAbilityObject(435); } }
        public AIAbility BasiliskClawA { get { return GetAbilityObject(436); } }
        public AIAbility BasiliskClawB { get { return GetAbilityObject(437); } }
        public AIAbility BasiliskToxicBite { get { return GetAbilityObject(438); } }
        public AIAbility BasiliskDebuff { get { return GetAbilityObject(439); } }
        public AIAbility BasiliskCastPerching { get { return GetAbilityObject(440); } }
        public AIAbility CultistArrow1 { get { return GetAbilityObject(441); } }
        public AIAbility CultistArrow2 { get { return GetAbilityObject(442); } }
        public AIAbility CultistOmegaArrow { get { return GetAbilityObject(443); } }
        public AIAbility CultistSword1 { get { return GetAbilityObject(444); } }
        public AIAbility CultistSword2 { get { return GetAbilityObject(445); } }
        public AIAbility CultistSwordStun { get { return GetAbilityObject(446); } }
        public AIAbility BossMegaSword1 { get { return GetAbilityObject(447); } }
        public AIAbility BossMegaSword2 { get { return GetAbilityObject(448); } }
        public AIAbility SedgewickMegaSwordAngry { get { return GetAbilityObject(449); } }
        public AIAbility BossMegaHammer { get { return GetAbilityObject(450); } }
        public AIAbility BossMegaHammer2 { get { return GetAbilityObject(451); } }
        public AIAbility BossMegaRageHammer { get { return GetAbilityObject(452); } }
        public AIAbility ClaudiaTundraSpikes { get { return GetAbilityObject(453); } }
        public AIAbility ClaudiaIceSpear { get { return GetAbilityObject(454); } }
        public AIAbility ClaudiaBlizzard { get { return GetAbilityObject(455); } }
        public AIAbility BigGolemHitA { get { return GetAbilityObject(456); } }
        public AIAbility BigGolemHitB { get { return GetAbilityObject(457); } }
        public AIAbility BigGolemFlingBoss { get { return GetAbilityObject(458); } }
        public AIAbility BigGolemPerchFix { get { return GetAbilityObject(459); } }
        public AIAbility BigGolemFlingBoss2 { get { return GetAbilityObject(460); } }
        public AIAbility BigGolemSummonFireSnake { get { return GetAbilityObject(461); } }
        public AIAbility BigGolemHitB_NoDisable { get { return GetAbilityObject(462); } }
        public AIAbility BigGolemHitA_NoDisable { get { return GetAbilityObject(463); } }
        public AIAbility BigGolemFling { get { return GetAbilityObject(464); } }
        public AIAbility GhoulClawA { get { return GetAbilityObject(465); } }
        public AIAbility GhoulClawB { get { return GetAbilityObject(466); } }
        public AIAbility GhoulSelfBuff { get { return GetAbilityObject(467); } }
        public AIAbility GhoulHammerA { get { return GetAbilityObject(468); } }
        public AIAbility GhoulHammerB { get { return GetAbilityObject(469); } }
        public AIAbility DragonWormSpitElectricity { get { return GetAbilityObject(470); } }
        public AIAbility DragonWormBite { get { return GetAbilityObject(471); } }
        public AIAbility DragonWormSmack { get { return GetAbilityObject(472); } }
        public AIAbility DragonWormRage { get { return GetAbilityObject(473); } }
        public AIAbility DragonWormEscape { get { return GetAbilityObject(474); } }
        public AIAbility DragonWormSpitFire { get { return GetAbilityObject(475); } }
        public AIAbility ColdSphereBurst { get { return GetAbilityObject(476); } }
        public AIAbility ColdSphereFreezeBurst { get { return GetAbilityObject(477); } }
        public AIAbility ManticoreBite { get { return GetAbilityObject(478); } }
        public AIAbility ManticoreClaw { get { return GetAbilityObject(479); } }
        public AIAbility ManticoreSting1 { get { return GetAbilityObject(480); } }
        public AIAbility Manticoresting2 { get { return GetAbilityObject(481); } }
        public AIAbility RakStaffHit { get { return GetAbilityObject(482); } }
        public AIAbility RakStaffPin { get { return GetAbilityObject(483); } }
        public AIAbility RakStaffBlock { get { return GetAbilityObject(484); } }
        public AIAbility RakStaffHeavy { get { return GetAbilityObject(485); } }
        public AIAbility RakSlash { get { return GetAbilityObject(486); } }
        public AIAbility RakKnee { get { return GetAbilityObject(487); } }
        public AIAbility RakKick { get { return GetAbilityObject(488); } }
        public AIAbility RakBarrage { get { return GetAbilityObject(489); } }
        public AIAbility RakSwordSlash { get { return GetAbilityObject(490); } }
        public AIAbility RakHackingBlade { get { return GetAbilityObject(491); } }
        public AIAbility RakDecapitate { get { return GetAbilityObject(492); } }
        public AIAbility RakFireball { get { return GetAbilityObject(493); } }
        public AIAbility RakBreatheFire { get { return GetAbilityObject(494); } }
        public AIAbility RakRingOfFire { get { return GetAbilityObject(495); } }
        public AIAbility RakToxinBomb { get { return GetAbilityObject(496); } }
        public AIAbility RakAcidBomb { get { return GetAbilityObject(497); } }
        public AIAbility RakHealingMist { get { return GetAbilityObject(498); } }
        public AIAbility RakBasicShot { get { return GetAbilityObject(499); } }
        public AIAbility RakHookShot { get { return GetAbilityObject(500); } }
        public AIAbility RakBowBash { get { return GetAbilityObject(501); } }
        public AIAbility RakAimedShot { get { return GetAbilityObject(502); } }
        public AIAbility RakPoisonArrow { get { return GetAbilityObject(503); } }
        public AIAbility RakMindreave { get { return GetAbilityObject(504); } }
        public AIAbility RakPainBubble { get { return GetAbilityObject(505); } }
        public AIAbility RakPanicCharge { get { return GetAbilityObject(506); } }
        public AIAbility RakRevitalize { get { return GetAbilityObject(507); } }
        public AIAbility RakReconstruct { get { return GetAbilityObject(508); } }
        public AIAbility RakBossSlow { get { return GetAbilityObject(509); } }
        public AIAbility RakBossPerchSlow { get { return GetAbilityObject(510); } }
        public AIAbility FlapSkullBite { get { return GetAbilityObject(511); } }
        public AIAbility FlapSkullBigBite { get { return GetAbilityObject(512); } }
        public AIAbility MinotaurClub { get { return GetAbilityObject(513); } }
        public AIAbility MinotaurRageClub { get { return GetAbilityObject(514); } }
        public AIAbility MinotaurBoulder { get { return GetAbilityObject(515); } }
        public AIAbility MinotaurBossRageClub { get { return GetAbilityObject(516); } }
        public AIAbility CockatricePeck { get { return GetAbilityObject(517); } }
        public AIAbility CockatriceTailWhip { get { return GetAbilityObject(518); } }
        public AIAbility CockatriceParalyze { get { return GetAbilityObject(519); } }
        public AIAbility GiantBeetleBite { get { return GetAbilityObject(520); } }
        public AIAbility GiantBeetleInject { get { return GetAbilityObject(521); } }
        public AIAbility GiantBeetleBoulderSpit { get { return GetAbilityObject(522); } }
        public AIAbility BatIllusionSlashA { get { return GetAbilityObject(523); } }
        public AIAbility BatIllusionSlashB { get { return GetAbilityObject(524); } }
        public AIAbility BatIllusionBite { get { return GetAbilityObject(525); } }
        public AIAbility GiantBatSlashA { get { return GetAbilityObject(526); } }
        public AIAbility GiantBatSlashB { get { return GetAbilityObject(527); } }
        public AIAbility GiantBatBite { get { return GetAbilityObject(528); } }
        public AIAbility HagAgingTouch { get { return GetAbilityObject(529); } }
        public AIAbility HagAgingScream { get { return GetAbilityObject(530); } }
        public AIAbility TriffidClawA { get { return GetAbilityObject(531); } }
        public AIAbility TriffidClawB { get { return GetAbilityObject(532); } }
        public AIAbility TriffidTongue { get { return GetAbilityObject(533); } }
        public AIAbility TriffidSpore { get { return GetAbilityObject(534); } }
        public AIAbility TriffidShot { get { return GetAbilityObject(535); } }
        public AIAbility TriffidTongueElite { get { return GetAbilityObject(536); } }
        public AIAbility GiantScorpionClawA { get { return GetAbilityObject(537); } }
        public AIAbility GiantScorpionClawB { get { return GetAbilityObject(538); } }
        public AIAbility GiantScorpionSting { get { return GetAbilityObject(539); } }
        public AIAbility KrakenBeak { get { return GetAbilityObject(540); } }
        public AIAbility KrakenSlam { get { return GetAbilityObject(541); } }
        public AIAbility KrakenRage { get { return GetAbilityObject(542); } }
        public AIAbility KrakenBabyBeak { get { return GetAbilityObject(543); } }
        public AIAbility KrakenBabySlam { get { return GetAbilityObject(544); } }
        public AIAbility KrakenBabyRage { get { return GetAbilityObject(545); } }
        public AIAbility RanalonHit { get { return GetAbilityObject(546); } }
        public AIAbility RanalonHitB { get { return GetAbilityObject(547); } }
        public AIAbility RanalonKick { get { return GetAbilityObject(548); } }
        public AIAbility RanalonTongue { get { return GetAbilityObject(549); } }
        public AIAbility RanalonZap { get { return GetAbilityObject(550); } }
        public AIAbility RanalonZapB { get { return GetAbilityObject(551); } }
        public AIAbility RanalonHeal { get { return GetAbilityObject(552); } }
        public AIAbility RanalonRoot { get { return GetAbilityObject(553); } }
        public AIAbility RanalonSelfBuff { get { return GetAbilityObject(554); } }
        public AIAbility RanalonSelfBuffElite { get { return GetAbilityObject(555); } }
        public AIAbility RanalonGuardianStab { get { return GetAbilityObject(556); } }
        public AIAbility RanalonGuardianStabB { get { return GetAbilityObject(557); } }
        public AIAbility RanalonGuardianBite { get { return GetAbilityObject(558); } }
        public AIAbility RanalonGuardianBlind { get { return GetAbilityObject(559); } }
        public AIAbility RanalonDoctrineKeeperStab { get { return GetAbilityObject(560); } }
        public AIAbility RanalonDoctrineKeeperBlind { get { return GetAbilityObject(561); } }
        public AIAbility BarghestBiteA { get { return GetAbilityObject(562); } }
        public AIAbility BarghestBiteB { get { return GetAbilityObject(563); } }
        public AIAbility BarghestDebuff { get { return GetAbilityObject(564); } }
        public AIAbility WorghestDebuff { get { return GetAbilityObject(565); } }
        public AIAbility BallistaFire { get { return GetAbilityObject(566); } }
        public AIAbility BallistaFire_Long { get { return GetAbilityObject(567); } }
        public AIAbility GargoyleSlamA { get { return GetAbilityObject(568); } }
        public AIAbility GargoyleSlamB { get { return GetAbilityObject(569); } }
        public AIAbility GargoyleStun { get { return GetAbilityObject(570); } }
        public AIAbility GargoyleBossStun { get { return GetAbilityObject(571); } }
        public AIAbility ScrayBite { get { return GetAbilityObject(572); } }
        public AIAbility ScrayStab { get { return GetAbilityObject(573); } }
        public AIAbility HippoBite { get { return GetAbilityObject(574); } }
        public AIAbility HippoBiteAndHeal1 { get { return GetAbilityObject(575); } }
        public AIAbility BigCatClaw_Pet { get { return GetAbilityObject(576); } }
        public AIAbility BigCatPounce_Pet { get { return GetAbilityObject(577); } }
        public AIAbility BigCatKill_Pet1 { get { return GetAbilityObject(578); } }
        public AIAbility BigCatKill_Pet2 { get { return GetAbilityObject(579); } }
        public AIAbility BigCatKill_Pet3 { get { return GetAbilityObject(580); } }
        public AIAbility BigCatKill_Pet4 { get { return GetAbilityObject(581); } }
        public AIAbility BigCatKill_Pet5 { get { return GetAbilityObject(582); } }
        public AIAbility BigCatKill_Pet6 { get { return GetAbilityObject(583); } }
        public AIAbility BigCatUltraKill_Pet1 { get { return GetAbilityObject(584); } }
        public AIAbility BigCatUltraKill_Pet2 { get { return GetAbilityObject(585); } }
        public AIAbility BigCatUltraKill_Pet3 { get { return GetAbilityObject(586); } }
        public AIAbility BigCatUltraKill_Pet4 { get { return GetAbilityObject(587); } }
        public AIAbility BigCatUltraKill_Pet5 { get { return GetAbilityObject(588); } }
        public AIAbility BigCatUltraKill_Pet6 { get { return GetAbilityObject(589); } }
        public AIAbility BigCatRoot_Pet1 { get { return GetAbilityObject(590); } }
        public AIAbility BigCatRoot_Pet2 { get { return GetAbilityObject(591); } }
        public AIAbility BigCatRoot_Pet3 { get { return GetAbilityObject(592); } }
        public AIAbility BigCatRoot_Pet4 { get { return GetAbilityObject(593); } }
        public AIAbility BigCatVuln_Pet1 { get { return GetAbilityObject(594); } }
        public AIAbility BigCatVuln_Pet2 { get { return GetAbilityObject(595); } }
        public AIAbility BigCatVuln_Pet3 { get { return GetAbilityObject(596); } }
        public AIAbility BigCatVuln_Pet4 { get { return GetAbilityObject(597); } }
        public AIAbility BigCatHeal_Pet1 { get { return GetAbilityObject(598); } }
        public AIAbility BigCatHeal_Pet2 { get { return GetAbilityObject(599); } }
        public AIAbility BigCatHeal_Pet3 { get { return GetAbilityObject(600); } }
        public AIAbility BigCatHeal_Pet4 { get { return GetAbilityObject(601); } }
        public AIAbility BigCatHeal_Pet5 { get { return GetAbilityObject(602); } }
        public AIAbility BigCatHeal_Pet6 { get { return GetAbilityObject(603); } }
        public AIAbility GrimalkinPuncture_Pet1 { get { return GetAbilityObject(604); } }
        public AIAbility GrimalkinPuncture_Pet2 { get { return GetAbilityObject(605); } }
        public AIAbility GrimalkinPuncture_Pet3 { get { return GetAbilityObject(606); } }
        public AIAbility GrimalkinPuncture_Pet4 { get { return GetAbilityObject(607); } }
        public AIAbility GrimalkinPuncture_Pet5 { get { return GetAbilityObject(608); } }
        public AIAbility GrimalkinPuncture_Pet6 { get { return GetAbilityObject(609); } }
        public AIAbility GrimalkinFlee_Pet1 { get { return GetAbilityObject(610); } }
        public AIAbility GrimalkinFlee_Pet2 { get { return GetAbilityObject(611); } }
        public AIAbility GrimalkinFlee_Pet3 { get { return GetAbilityObject(612); } }
        public AIAbility RatBite_Pet { get { return GetAbilityObject(613); } }
        public AIAbility RatClaw_Pet { get { return GetAbilityObject(614); } }
        public AIAbility RatDeRage_Pet1 { get { return GetAbilityObject(615); } }
        public AIAbility RatDeRage_Pet2 { get { return GetAbilityObject(616); } }
        public AIAbility RatDeRage_Pet3 { get { return GetAbilityObject(617); } }
        public AIAbility RatDeRage_Pet4 { get { return GetAbilityObject(618); } }
        public AIAbility RatDeRage_Pet5 { get { return GetAbilityObject(619); } }
        public AIAbility RatDeRage_Pet6 { get { return GetAbilityObject(620); } }
        public AIAbility RatHeal_Pet1 { get { return GetAbilityObject(621); } }
        public AIAbility RatHeal_Pet2 { get { return GetAbilityObject(622); } }
        public AIAbility RatHeal_Pet3 { get { return GetAbilityObject(623); } }
        public AIAbility RatHeal_Pet4 { get { return GetAbilityObject(624); } }
        public AIAbility RatHeal_Pet5 { get { return GetAbilityObject(625); } }
        public AIAbility RatHeal_Pet6 { get { return GetAbilityObject(626); } }
        public AIAbility RatVuln_Pet1 { get { return GetAbilityObject(627); } }
        public AIAbility RatVuln_Pet2 { get { return GetAbilityObject(628); } }
        public AIAbility RatVuln_Pet3 { get { return GetAbilityObject(629); } }
        public AIAbility RatVuln_Pet4 { get { return GetAbilityObject(630); } }
        public AIAbility FireRatBite_Pet { get { return GetAbilityObject(631); } }
        public AIAbility FireRatClaw_Pet { get { return GetAbilityObject(632); } }
        public AIAbility RatBurn_Pet1 { get { return GetAbilityObject(633); } }
        public AIAbility RatBurn_Pet2 { get { return GetAbilityObject(634); } }
        public AIAbility RatBurn_Pet3 { get { return GetAbilityObject(635); } }
        public AIAbility RatBurn_Pet4 { get { return GetAbilityObject(636); } }
        public AIAbility RatBurn_Pet5 { get { return GetAbilityObject(637); } }
        public AIAbility RatBurn_Pet6 { get { return GetAbilityObject(638); } }
        public AIAbility BearBite_Pet { get { return GetAbilityObject(639); } }
        public AIAbility BearClaw_Pet { get { return GetAbilityObject(640); } }
        public AIAbility BearTaunt_Pet1 { get { return GetAbilityObject(641); } }
        public AIAbility BearTaunt_Pet2 { get { return GetAbilityObject(642); } }
        public AIAbility BearTaunt_Pet3 { get { return GetAbilityObject(643); } }
        public AIAbility BearTaunt_Pet4 { get { return GetAbilityObject(644); } }
        public AIAbility BearTaunt_Pet5 { get { return GetAbilityObject(645); } }
        public AIAbility BearTaunt_Pet6 { get { return GetAbilityObject(646); } }
        public AIAbility BearStun_Pet1 { get { return GetAbilityObject(647); } }
        public AIAbility BearStun_Pet2 { get { return GetAbilityObject(648); } }
        public AIAbility BearStun_Pet3 { get { return GetAbilityObject(649); } }
        public AIAbility BearStun_Pet4 { get { return GetAbilityObject(650); } }
        public AIAbility BearWarmth_Pet1 { get { return GetAbilityObject(651); } }
        public AIAbility BearWarmth_Pet2 { get { return GetAbilityObject(652); } }
        public AIAbility BearWarmth_Pet3 { get { return GetAbilityObject(653); } }
        public AIAbility BearWarmth_Pet4 { get { return GetAbilityObject(654); } }
        public AIAbility BearWarmth_Pet5 { get { return GetAbilityObject(655); } }
        public AIAbility BearWarmth_Pet6 { get { return GetAbilityObject(656); } }
        public AIAbility BearSelfHeal_Pet1 { get { return GetAbilityObject(657); } }
        public AIAbility BearSelfHeal_Pet2 { get { return GetAbilityObject(658); } }
        public AIAbility BearSelfHeal_Pet3 { get { return GetAbilityObject(659); } }
        public AIAbility BearSelfHeal_Pet4 { get { return GetAbilityObject(660); } }
        public AIAbility BearSelfHeal_Pet5 { get { return GetAbilityObject(661); } }
        public AIAbility BearSelfHeal_Pet6 { get { return GetAbilityObject(662); } }
        public AIAbility BearUltra_Pet1 { get { return GetAbilityObject(663); } }
        public AIAbility BearUltra_Pet2 { get { return GetAbilityObject(664); } }
        public AIAbility BearUltra_Pet3 { get { return GetAbilityObject(665); } }
        public AIAbility BearUltra_Pet4 { get { return GetAbilityObject(666); } }
        public AIAbility BearUltra_Pet5 { get { return GetAbilityObject(667); } }
        public AIAbility BearUltra_Pet6 { get { return GetAbilityObject(668); } }
    }
}
