namespace PgJsonObjects
{
    public class PgAIAbilitySet : GenericPgObject<PgAIAbilitySet>, IPgAIAbilitySet
    {
        public PgAIAbilitySet(byte[] data, ref int offset)
            : base(data, offset)
        {
        }

        protected override PgAIAbilitySet CreateItem(byte[] data, ref int offset)
        {
            return CreateNew(data, ref offset);
        }

        public static PgAIAbilitySet CreateNew(byte[] data, ref int offset)
        {
            return new PgAIAbilitySet(data, ref offset);
        }

        private IPgAIAbility[] Abilities = new AIAbility[669];
        private IPgAIAbility GetAbilityObject(int index) { return GetObject(4 + (index * 4), ref Abilities[index], PgAIAbility.CreateNew); }

        public override string Key { get { return GetString(0); } }
        public IPgAIAbility AnimalBite { get { return GetAbilityObject(0); } }
        public IPgAIAbility AnimalClaw { get { return GetAbilityObject(1); } }
        public IPgAIAbility AnimalOmegaBite { get { return GetAbilityObject(2); } }
        public IPgAIAbility AnimalOmegaBite2 { get { return GetAbilityObject(3); } }
        public IPgAIAbility AnimalHoofFrontKick { get { return GetAbilityObject(4); } }
        public IPgAIAbility AnimalHoofRageKick { get { return GetAbilityObject(5); } }
        public IPgAIAbility AnimalHoofRageKick2 { get { return GetAbilityObject(6); } }
        public IPgAIAbility AnimalHoofFieryFrontKick { get { return GetAbilityObject(7); } }
        public IPgAIAbility AnimalHoofFieryFrontKick2 { get { return GetAbilityObject(8); } }
        public IPgAIAbility ElectricPigHitAndRun { get { return GetAbilityObject(9); } }
        public IPgAIAbility ElectricPigStun { get { return GetAbilityObject(10); } }
        public IPgAIAbility ElectricPigAoEStun { get { return GetAbilityObject(11); } }
        public IPgAIAbility LamiaMindControl { get { return GetAbilityObject(12); } }
        public IPgAIAbility LamiaRage { get { return GetAbilityObject(13); } }
        public IPgAIAbility SlimeKick { get { return GetAbilityObject(14); } }
        public IPgAIAbility SlimeKickB { get { return GetAbilityObject(15); } }
        public IPgAIAbility SlimeBite { get { return GetAbilityObject(16); } }
        public IPgAIAbility SlimeBiteB { get { return GetAbilityObject(17); } }
        public IPgAIAbility Slime_SummonSlime { get { return GetAbilityObject(18); } }
        public IPgAIAbility SlimeSpit { get { return GetAbilityObject(19); } }
        public IPgAIAbility SlimeSuperSpit { get { return GetAbilityObject(20); } }
        public IPgAIAbility IceSlimeKick { get { return GetAbilityObject(21); } }
        public IPgAIAbility IceSlimeKickB { get { return GetAbilityObject(22); } }
        public IPgAIAbility IceSlimeBite { get { return GetAbilityObject(23); } }
        public IPgAIAbility IceSlimeBiteB { get { return GetAbilityObject(24); } }
        public IPgAIAbility BossSlimeKick { get { return GetAbilityObject(25); } }
        public IPgAIAbility BossSlimeKickB { get { return GetAbilityObject(26); } }
        public IPgAIAbility BossSlime_SummonSlime1 { get { return GetAbilityObject(27); } }
        public IPgAIAbility BossSlimeKick2 { get { return GetAbilityObject(28); } }
        public IPgAIAbility BossSlimeKick2B { get { return GetAbilityObject(29); } }
        public IPgAIAbility BossSlime_SummonSlime4Elite { get { return GetAbilityObject(30); } }
        public IPgAIAbility AnimalHeal { get { return GetAbilityObject(31); } }
        public IPgAIAbility AnimalHeal2 { get { return GetAbilityObject(32); } }
        public IPgAIAbility AnimalHeal3 { get { return GetAbilityObject(33); } }
        public IPgAIAbility IceCockPeck { get { return GetAbilityObject(34); } }
        public IPgAIAbility IceCockFreeze { get { return GetAbilityObject(35); } }
        public IPgAIAbility NightmareHoof { get { return GetAbilityObject(36); } }
        public IPgAIAbility NightmareDarknessBomb { get { return GetAbilityObject(37); } }
        public IPgAIAbility CiervosNightmareHoof { get { return GetAbilityObject(38); } }
        public IPgAIAbility CiervosDarknessBomb { get { return GetAbilityObject(39); } }
        public IPgAIAbility Myconian_Bash { get { return GetAbilityObject(40); } }
        public IPgAIAbility Myconian_Mindspores { get { return GetAbilityObject(41); } }
        public IPgAIAbility Myconian_Drain { get { return GetAbilityObject(42); } }
        public IPgAIAbility Myconian_BossBash { get { return GetAbilityObject(43); } }
        public IPgAIAbility Myconian_Mindspores_Permanent { get { return GetAbilityObject(44); } }
        public IPgAIAbility Myconian_TidalCurse { get { return GetAbilityObject(45); } }
        public IPgAIAbility Myconian_Shock { get { return GetAbilityObject(46); } }
        public IPgAIAbility AlienDog_Punch { get { return GetAbilityObject(47); } }
        public IPgAIAbility AlienDog_Punch2 { get { return GetAbilityObject(48); } }
        public IPgAIAbility AlienDog_RagePunch { get { return GetAbilityObject(49); } }
        public IPgAIAbility MushroomMonster_Bite { get { return GetAbilityObject(50); } }
        public IPgAIAbility MushroomMonster_Spit1 { get { return GetAbilityObject(51); } }
        public IPgAIAbility MushroomMonster_Spit2 { get { return GetAbilityObject(52); } }
        public IPgAIAbility MushroomMonster_SummonMushroomSpawn1 { get { return GetAbilityObject(53); } }
        public IPgAIAbility MushroomMonster_SummonMushroomSpawn2 { get { return GetAbilityObject(54); } }
        public IPgAIAbility MushroomMonster_SummonMushroomSpawn3 { get { return GetAbilityObject(55); } }
        public IPgAIAbility MushroomMonster_SpawnSpit1 { get { return GetAbilityObject(56); } }
        public IPgAIAbility MushroomMonster_SpawnSpit2 { get { return GetAbilityObject(57); } }
        public IPgAIAbility MushroomMonster_SpawnSuperSpit1 { get { return GetAbilityObject(58); } }
        public IPgAIAbility MushroomMonster_SpawnSuperSpit2 { get { return GetAbilityObject(59); } }
        public IPgAIAbility MaronesaStomp { get { return GetAbilityObject(60); } }
        public IPgAIAbility MaronesaInfect { get { return GetAbilityObject(61); } }
        public IPgAIAbility WormBite1 { get { return GetAbilityObject(62); } }
        public IPgAIAbility WormSpit1 { get { return GetAbilityObject(63); } }
        public IPgAIAbility WormShove1 { get { return GetAbilityObject(64); } }
        public IPgAIAbility WormInfect1 { get { return GetAbilityObject(65); } }
        public IPgAIAbility WormSpit2 { get { return GetAbilityObject(66); } }
        public IPgAIAbility WormBossSpit { get { return GetAbilityObject(67); } }
        public IPgAIAbility WormBossAcidBurst { get { return GetAbilityObject(68); } }
        public IPgAIAbility GnasherBite { get { return GetAbilityObject(69); } }
        public IPgAIAbility GnasherRend { get { return GetAbilityObject(70); } }
        public IPgAIAbility Dinoslash { get { return GetAbilityObject(71); } }
        public IPgAIAbility Dinoslash2 { get { return GetAbilityObject(72); } }
        public IPgAIAbility Dinobite { get { return GetAbilityObject(73); } }
        public IPgAIAbility Dinobite2 { get { return GetAbilityObject(74); } }
        public IPgAIAbility Dinowhap { get { return GetAbilityObject(75); } }
        public IPgAIAbility Peck { get { return GetAbilityObject(76); } }
        public IPgAIAbility AnimalFlee { get { return GetAbilityObject(77); } }
        public IPgAIAbility HippogriffPeck { get { return GetAbilityObject(78); } }
        public IPgAIAbility HippogriffSlashes { get { return GetAbilityObject(79); } }
        public IPgAIAbility HippogriffBossSlashes { get { return GetAbilityObject(80); } }
        public IPgAIAbility RatBite { get { return GetAbilityObject(81); } }
        public IPgAIAbility RatClaw { get { return GetAbilityObject(82); } }
        public IPgAIAbility FireRatBite { get { return GetAbilityObject(83); } }
        public IPgAIAbility FireRatClaw { get { return GetAbilityObject(84); } }
        public IPgAIAbility GoblinZapBall { get { return GetAbilityObject(85); } }
        public IPgAIAbility GoblinHateZapBall { get { return GetAbilityObject(86); } }
        public IPgAIAbility GoblinHateZapBall2 { get { return GetAbilityObject(87); } }
        public IPgAIAbility RhinoHorn { get { return GetAbilityObject(88); } }
        public IPgAIAbility RhinoRage { get { return GetAbilityObject(89); } }
        public IPgAIAbility RhinoFireball { get { return GetAbilityObject(90); } }
        public IPgAIAbility RhinoBossRage { get { return GetAbilityObject(91); } }
        public IPgAIAbility YetiPunch { get { return GetAbilityObject(92); } }
        public IPgAIAbility YetiEncase { get { return GetAbilityObject(93); } }
        public IPgAIAbility YetiDebuff { get { return GetAbilityObject(94); } }
        public IPgAIAbility YetiBoulderThrow { get { return GetAbilityObject(95); } }
        public IPgAIAbility YetiBarrage { get { return GetAbilityObject(96); } }
        public IPgAIAbility YetiRoarStun { get { return GetAbilityObject(97); } }
        public IPgAIAbility YetiFlingAway { get { return GetAbilityObject(98); } }
        public IPgAIAbility YetiIceBallThrow { get { return GetAbilityObject(99); } }
        public IPgAIAbility YetiIceSpear { get { return GetAbilityObject(100); } }
        public IPgAIAbility YetiColdOrb { get { return GetAbilityObject(101); } }
        public IPgAIAbility YetiFrostRing { get { return GetAbilityObject(102); } }
        public IPgAIAbility WorgBite { get { return GetAbilityObject(103); } }
        public IPgAIAbility WorgOmegaBite { get { return GetAbilityObject(104); } }
        public IPgAIAbility BearBite { get { return GetAbilityObject(105); } }
        public IPgAIAbility BearCrush { get { return GetAbilityObject(106); } }
        public IPgAIAbility BrainBite { get { return GetAbilityObject(107); } }
        public IPgAIAbility BrainDrain { get { return GetAbilityObject(108); } }
        public IPgAIAbility BrainDrain2 { get { return GetAbilityObject(109); } }
        public IPgAIAbility BigCatClaw { get { return GetAbilityObject(110); } }
        public IPgAIAbility BigCatPounce { get { return GetAbilityObject(111); } }
        public IPgAIAbility BigCatRagePounce { get { return GetAbilityObject(112); } }
        public IPgAIAbility BigCatDebuff { get { return GetAbilityObject(113); } }
        public IPgAIAbility SpiderBite { get { return GetAbilityObject(114); } }
        public IPgAIAbility SpiderFireball { get { return GetAbilityObject(115); } }
        public IPgAIAbility SpiderBossFreePin { get { return GetAbilityObject(116); } }
        public IPgAIAbility SpiderKill2 { get { return GetAbilityObject(117); } }
        public IPgAIAbility SpiderInject { get { return GetAbilityObject(118); } }
        public IPgAIAbility SpiderKill { get { return GetAbilityObject(119); } }
        public IPgAIAbility AcidBall1 { get { return GetAbilityObject(120); } }
        public IPgAIAbility SpiderPin { get { return GetAbilityObject(121); } }
        public IPgAIAbility SpiderKill3 { get { return GetAbilityObject(122); } }
        public IPgAIAbility AcidBall2 { get { return GetAbilityObject(123); } }
        public IPgAIAbility AcidSpew1 { get { return GetAbilityObject(124); } }
        public IPgAIAbility AcidExplosion1 { get { return GetAbilityObject(125); } }
        public IPgAIAbility AcidExplosion2 { get { return GetAbilityObject(126); } }
        public IPgAIAbility SpiderIncubate { get { return GetAbilityObject(127); } }
        public IPgAIAbility MantisClaw { get { return GetAbilityObject(128); } }
        public IPgAIAbility MantisRage { get { return GetAbilityObject(129); } }
        public IPgAIAbility MantisAcidBurst { get { return GetAbilityObject(130); } }
        public IPgAIAbility SherzatClaw { get { return GetAbilityObject(131); } }
        public IPgAIAbility SherzatAcidSpit { get { return GetAbilityObject(132); } }
        public IPgAIAbility SherzatDisintegrate { get { return GetAbilityObject(133); } }
        public IPgAIAbility MantisSwipe { get { return GetAbilityObject(134); } }
        public IPgAIAbility MantisBlast { get { return GetAbilityObject(135); } }
        public IPgAIAbility SnailStrike { get { return GetAbilityObject(136); } }
        public IPgAIAbility SnailRage { get { return GetAbilityObject(137); } }
        public IPgAIAbility SnailRageB { get { return GetAbilityObject(138); } }
        public IPgAIAbility SnailRageC { get { return GetAbilityObject(139); } }
        public IPgAIAbility HookClaw { get { return GetAbilityObject(140); } }
        public IPgAIAbility HookAcid { get { return GetAbilityObject(141); } }
        public IPgAIAbility HookRage { get { return GetAbilityObject(142); } }
        public IPgAIAbility UndeadSword1 { get { return GetAbilityObject(143); } }
        public IPgAIAbility UndeadSword2 { get { return GetAbilityObject(144); } }
        public IPgAIAbility UndeadSwordAngry { get { return GetAbilityObject(145); } }
        public IPgAIAbility UndeadMegaSword1 { get { return GetAbilityObject(146); } }
        public IPgAIAbility UndeadMegaSword2 { get { return GetAbilityObject(147); } }
        public IPgAIAbility UndeadMegaSwordAngry { get { return GetAbilityObject(148); } }
        public IPgAIAbility UndeadLightningSmite { get { return GetAbilityObject(149); } }
        public IPgAIAbility UndeadPhysicalShield { get { return GetAbilityObject(150); } }
        public IPgAIAbility UndeadSword1B { get { return GetAbilityObject(151); } }
        public IPgAIAbility UndeadFireballA { get { return GetAbilityObject(152); } }
        public IPgAIAbility UndeadFireballB { get { return GetAbilityObject(153); } }
        public IPgAIAbility UndeadFireballB2 { get { return GetAbilityObject(154); } }
        public IPgAIAbility UndeadIceBall1 { get { return GetAbilityObject(155); } }
        public IPgAIAbility UndeadFreezeBall { get { return GetAbilityObject(156); } }
        public IPgAIAbility UndeadFireballLongA { get { return GetAbilityObject(157); } }
        public IPgAIAbility UndeadFireballLongB { get { return GetAbilityObject(158); } }
        public IPgAIAbility UndeadFireballLongB2 { get { return GetAbilityObject(159); } }
        public IPgAIAbility KhyrulekCurseBall { get { return GetAbilityObject(160); } }
        public IPgAIAbility UrsulaFireball1 { get { return GetAbilityObject(161); } }
        public IPgAIAbility UrsulaFireball1B { get { return GetAbilityObject(162); } }
        public IPgAIAbility UrsulaFireball2 { get { return GetAbilityObject(163); } }
        public IPgAIAbility UrsulaIceball1 { get { return GetAbilityObject(164); } }
        public IPgAIAbility UrsulaIceball1B { get { return GetAbilityObject(165); } }
        public IPgAIAbility UrsulaIceball2 { get { return GetAbilityObject(166); } }
        public IPgAIAbility UrsulaSummon { get { return GetAbilityObject(167); } }
        public IPgAIAbility UrsulaRage { get { return GetAbilityObject(168); } }
        public IPgAIAbility UndeadFireballA2 { get { return GetAbilityObject(169); } }
        public IPgAIAbility BigHeadCurseball { get { return GetAbilityObject(170); } }
        public IPgAIAbility UndeadArrow1 { get { return GetAbilityObject(171); } }
        public IPgAIAbility UndeadArrow2 { get { return GetAbilityObject(172); } }
        public IPgAIAbility UndeadOmegaArrow { get { return GetAbilityObject(173); } }
        public IPgAIAbility PetUndeadArrow1 { get { return GetAbilityObject(174); } }
        public IPgAIAbility PetUndeadArrow2 { get { return GetAbilityObject(175); } }
        public IPgAIAbility PetUndeadOmegaArrow { get { return GetAbilityObject(176); } }
        public IPgAIAbility UndeadGrappleArrow1 { get { return GetAbilityObject(177); } }
        public IPgAIAbility UndeadSelfDestruct { get { return GetAbilityObject(178); } }
        public IPgAIAbility UndeadDarknessBall { get { return GetAbilityObject(179); } }
        public IPgAIAbility UndeadBoneWhirlwind { get { return GetAbilityObject(180); } }
        public IPgAIAbility PetUndeadSword1 { get { return GetAbilityObject(181); } }
        public IPgAIAbility PetUndeadSword2 { get { return GetAbilityObject(182); } }
        public IPgAIAbility PetUndeadSwordAngry { get { return GetAbilityObject(183); } }
        public IPgAIAbility PetUndeadFireballA { get { return GetAbilityObject(184); } }
        public IPgAIAbility PetUndeadFireballB { get { return GetAbilityObject(185); } }
        public IPgAIAbility PetUndeadDefensiveBurst { get { return GetAbilityObject(186); } }
        public IPgAIAbility PetUndeadPunch1 { get { return GetAbilityObject(187); } }
        public IPgAIAbility ZombiePunch { get { return GetAbilityObject(188); } }
        public IPgAIAbility ZombieBite { get { return GetAbilityObject(189); } }
        public IPgAIAbility GoblinSpear1 { get { return GetAbilityObject(190); } }
        public IPgAIAbility GoblinSpear2 { get { return GetAbilityObject(191); } }
        public IPgAIAbility GoblinRageSpear1 { get { return GetAbilityObject(192); } }
        public IPgAIAbility GoblinRageSpear2 { get { return GetAbilityObject(193); } }
        public IPgAIAbility GoblinHeal1 { get { return GetAbilityObject(194); } }
        public IPgAIAbility GoblinHeal2 { get { return GetAbilityObject(195); } }
        public IPgAIAbility GoblinPunch { get { return GetAbilityObject(196); } }
        public IPgAIAbility GoblinArrow1 { get { return GetAbilityObject(197); } }
        public IPgAIAbility GoblinArrow2 { get { return GetAbilityObject(198); } }
        public IPgAIAbility GoblinRageArrow1 { get { return GetAbilityObject(199); } }
        public IPgAIAbility GoblinRageArrow2 { get { return GetAbilityObject(200); } }
        public IPgAIAbility GoblinSpreadZapBall { get { return GetAbilityObject(201); } }
        public IPgAIAbility GoblinBossLightning { get { return GetAbilityObject(202); } }
        public IPgAIAbility GoblinArmorBuff { get { return GetAbilityObject(203); } }
        public IPgAIAbility MummySlamA { get { return GetAbilityObject(204); } }
        public IPgAIAbility MummySlamB { get { return GetAbilityObject(205); } }
        public IPgAIAbility MummySlamCombo { get { return GetAbilityObject(206); } }
        public IPgAIAbility MummyWrapA { get { return GetAbilityObject(207); } }
        public IPgAIAbility MummyWrapB { get { return GetAbilityObject(208); } }
        public IPgAIAbility MummyWrapRage { get { return GetAbilityObject(209); } }
        public IPgAIAbility BarutiWrapA { get { return GetAbilityObject(210); } }
        public IPgAIAbility BarutiWrapB { get { return GetAbilityObject(211); } }
        public IPgAIAbility BarutiWrapRage { get { return GetAbilityObject(212); } }
        public IPgAIAbility FireWallAttack1 { get { return GetAbilityObject(213); } }
        public IPgAIAbility FireWallDotAttack1 { get { return GetAbilityObject(214); } }
        public IPgAIAbility FireSnakeExplosion1 { get { return GetAbilityObject(215); } }
        public IPgAIAbility FireTrapAttack1 { get { return GetAbilityObject(216); } }
        public IPgAIAbility HealingAura1 { get { return GetAbilityObject(217); } }
        public IPgAIAbility HealingAura2 { get { return GetAbilityObject(218); } }
        public IPgAIAbility HealingAura3 { get { return GetAbilityObject(219); } }
        public IPgAIAbility HealingAura4 { get { return GetAbilityObject(220); } }
        public IPgAIAbility DruidHealingSanctuaryHeal { get { return GetAbilityObject(221); } }
        public IPgAIAbility AcidAuraBall1 { get { return GetAbilityObject(222); } }
        public IPgAIAbility AcidAuraBall2 { get { return GetAbilityObject(223); } }
        public IPgAIAbility AcidAuraBall3 { get { return GetAbilityObject(224); } }
        public IPgAIAbility AcidAuraBall4 { get { return GetAbilityObject(225); } }
        public IPgAIAbility ElectricityAura1 { get { return GetAbilityObject(226); } }
        public IPgAIAbility ElectricityAuraBolt1 { get { return GetAbilityObject(227); } }
        public IPgAIAbility ReboundAura1 { get { return GetAbilityObject(228); } }
        public IPgAIAbility ColdAuraBurst { get { return GetAbilityObject(229); } }
        public IPgAIAbility WebStick { get { return GetAbilityObject(230); } }
        public IPgAIAbility IcySlam { get { return GetAbilityObject(231); } }
        public IPgAIAbility IcyCocoon { get { return GetAbilityObject(232); } }
        public IPgAIAbility IcyCocoon2 { get { return GetAbilityObject(233); } }
        public IPgAIAbility ElementalSlam { get { return GetAbilityObject(234); } }
        public IPgAIAbility ElementalBees { get { return GetAbilityObject(235); } }
        public IPgAIAbility ElementalBees2 { get { return GetAbilityObject(236); } }
        public IPgAIAbility FaeLightningSmite { get { return GetAbilityObject(237); } }
        public IPgAIAbility TotalHorrorAttack { get { return GetAbilityObject(238); } }
        public IPgAIAbility TotalHorrorStretch { get { return GetAbilityObject(239); } }
        public IPgAIAbility TotalHorrorHeal { get { return GetAbilityObject(240); } }
        public IPgAIAbility TotalHorrorHeal2 { get { return GetAbilityObject(241); } }
        public IPgAIAbility SheepBomb1 { get { return GetAbilityObject(242); } }
        public IPgAIAbility SlugPoisonBite { get { return GetAbilityObject(243); } }
        public IPgAIAbility SlugPoisonRage { get { return GetAbilityObject(244); } }
        public IPgAIAbility SlugPoisonBite2 { get { return GetAbilityObject(245); } }
        public IPgAIAbility SlugPoisonRage2 { get { return GetAbilityObject(246); } }
        public IPgAIAbility SlugPoisonBite3 { get { return GetAbilityObject(247); } }
        public IPgAIAbility SlugPoisonRage3 { get { return GetAbilityObject(248); } }
        public IPgAIAbility TornadoJolt1 { get { return GetAbilityObject(249); } }
        public IPgAIAbility TornadoFling { get { return GetAbilityObject(250); } }
        public IPgAIAbility TornadoToss { get { return GetAbilityObject(251); } }
        public IPgAIAbility TheFogCurse { get { return GetAbilityObject(252); } }
        public IPgAIAbility MonsterWerewolfPouncingRake { get { return GetAbilityObject(253); } }
        public IPgAIAbility MonsterWerewolfPackAttack { get { return GetAbilityObject(254); } }
        public IPgAIAbility MonsterWerewolfHowl { get { return GetAbilityObject(255); } }
        public IPgAIAbility Werewolf_Summon_Rage { get { return GetAbilityObject(256); } }
        public IPgAIAbility Werewolf_Summon_Opener { get { return GetAbilityObject(257); } }
        public IPgAIAbility BleddynHowl { get { return GetAbilityObject(258); } }
        public IPgAIAbility OrcSwordSlash { get { return GetAbilityObject(259); } }
        public IPgAIAbility OrcParry { get { return GetAbilityObject(260); } }
        public IPgAIAbility OrcFinishingBlow { get { return GetAbilityObject(261); } }
        public IPgAIAbility OrcHipThrow { get { return GetAbilityObject(262); } }
        public IPgAIAbility OrcKneeKick { get { return GetAbilityObject(263); } }
        public IPgAIAbility OrcPunch { get { return GetAbilityObject(264); } }
        public IPgAIAbility OrcArrow1 { get { return GetAbilityObject(265); } }
        public IPgAIAbility OrcArrow2 { get { return GetAbilityObject(266); } }
        public IPgAIAbility OrcStaffSmash { get { return GetAbilityObject(267); } }
        public IPgAIAbility OrcFireball { get { return GetAbilityObject(268); } }
        public IPgAIAbility OrcHeal1 { get { return GetAbilityObject(269); } }
        public IPgAIAbility OrcHeal2 { get { return GetAbilityObject(270); } }
        public IPgAIAbility OrcEvasionBubble { get { return GetAbilityObject(271); } }
        public IPgAIAbility OrcElectricStun { get { return GetAbilityObject(272); } }
        public IPgAIAbility OrcFireBolts { get { return GetAbilityObject(273); } }
        public IPgAIAbility OrcKnockbackBolt { get { return GetAbilityObject(274); } }
        public IPgAIAbility OrcSummonUrak2 { get { return GetAbilityObject(275); } }
        public IPgAIAbility OrcSwordSlashFire { get { return GetAbilityObject(276); } }
        public IPgAIAbility OrcParryFire { get { return GetAbilityObject(277); } }
        public IPgAIAbility OrcFinishingBlowFire { get { return GetAbilityObject(278); } }
        public IPgAIAbility OrcSummonSigil1 { get { return GetAbilityObject(279); } }
        public IPgAIAbility OrcSpearAttack { get { return GetAbilityObject(280); } }
        public IPgAIAbility OrcHalberdAttack { get { return GetAbilityObject(281); } }
        public IPgAIAbility OrcAreaHalberdAttack { get { return GetAbilityObject(282); } }
        public IPgAIAbility OrcDebuffArrow { get { return GetAbilityObject(283); } }
        public IPgAIAbility OrcSlice { get { return GetAbilityObject(284); } }
        public IPgAIAbility OrcVenomstrike1 { get { return GetAbilityObject(285); } }
        public IPgAIAbility OrcVenomstrike0 { get { return GetAbilityObject(286); } }
        public IPgAIAbility OrcLieutenantDebuffTaunt { get { return GetAbilityObject(287); } }
        public IPgAIAbility OrcAreaHalberdBoss { get { return GetAbilityObject(288); } }
        public IPgAIAbility OrcDeathsHold { get { return GetAbilityObject(289); } }
        public IPgAIAbility GazlukPriest1Special { get { return GetAbilityObject(290); } }
        public IPgAIAbility GazlukPriest2Special { get { return GetAbilityObject(291); } }
        public IPgAIAbility GazlukPriest3Special { get { return GetAbilityObject(292); } }
        public IPgAIAbility OrcExtinguishLife { get { return GetAbilityObject(293); } }
        public IPgAIAbility OrcDarknessBall { get { return GetAbilityObject(294); } }
        public IPgAIAbility OrcWaveOfDarkness { get { return GetAbilityObject(295); } }
        public IPgAIAbility EnemyMinigolemPunch { get { return GetAbilityObject(296); } }
        public IPgAIAbility EnemyMinigolemHeal { get { return GetAbilityObject(297); } }
        public IPgAIAbility EnemyMinigolemExplode { get { return GetAbilityObject(298); } }
        public IPgAIAbility MinigolemBombToss { get { return GetAbilityObject(299); } }
        public IPgAIAbility MinigolemBombToss2 { get { return GetAbilityObject(300); } }
        public IPgAIAbility MinigolemBombToss3 { get { return GetAbilityObject(301); } }
        public IPgAIAbility MinigolemBombToss4 { get { return GetAbilityObject(302); } }
        public IPgAIAbility MinigolemBombToss5 { get { return GetAbilityObject(303); } }
        public IPgAIAbility MinigolemAoEHeal { get { return GetAbilityObject(304); } }
        public IPgAIAbility MinigolemAoEHeal2 { get { return GetAbilityObject(305); } }
        public IPgAIAbility MinigolemAoEHeal3 { get { return GetAbilityObject(306); } }
        public IPgAIAbility MinigolemAoEHeal4 { get { return GetAbilityObject(307); } }
        public IPgAIAbility MinigolemAoEHeal5 { get { return GetAbilityObject(308); } }
        public IPgAIAbility MinigolemSelfDestruct { get { return GetAbilityObject(309); } }
        public IPgAIAbility MinigolemSelfDestruct2 { get { return GetAbilityObject(310); } }
        public IPgAIAbility MinigolemSelfDestruct3 { get { return GetAbilityObject(311); } }
        public IPgAIAbility MinigolemSelfDestruct4 { get { return GetAbilityObject(312); } }
        public IPgAIAbility MinigolemSelfDestruct5 { get { return GetAbilityObject(313); } }
        public IPgAIAbility MinigolemAoEPower { get { return GetAbilityObject(314); } }
        public IPgAIAbility MinigolemAoEPower2 { get { return GetAbilityObject(315); } }
        public IPgAIAbility MinigolemAoEPower3 { get { return GetAbilityObject(316); } }
        public IPgAIAbility MinigolemAoEPower4 { get { return GetAbilityObject(317); } }
        public IPgAIAbility MinigolemAoEPower5 { get { return GetAbilityObject(318); } }
        public IPgAIAbility MinigolemHeal { get { return GetAbilityObject(319); } }
        public IPgAIAbility MinigolemHeal2 { get { return GetAbilityObject(320); } }
        public IPgAIAbility MinigolemHeal3 { get { return GetAbilityObject(321); } }
        public IPgAIAbility MinigolemHeal4 { get { return GetAbilityObject(322); } }
        public IPgAIAbility MinigolemHeal5 { get { return GetAbilityObject(323); } }
        public IPgAIAbility MinigolemDoomAdmixture { get { return GetAbilityObject(324); } }
        public IPgAIAbility MinigolemDoomAdmixture2 { get { return GetAbilityObject(325); } }
        public IPgAIAbility MinigolemDoomAdmixture3 { get { return GetAbilityObject(326); } }
        public IPgAIAbility MinigolemDoomAdmixture4 { get { return GetAbilityObject(327); } }
        public IPgAIAbility MinigolemDoomAdmixture5 { get { return GetAbilityObject(328); } }
        public IPgAIAbility MinigolemSelfSacrifice { get { return GetAbilityObject(329); } }
        public IPgAIAbility MinigolemSelfSacrifice2 { get { return GetAbilityObject(330); } }
        public IPgAIAbility MinigolemSelfSacrifice3 { get { return GetAbilityObject(331); } }
        public IPgAIAbility MinigolemSelfSacrifice4 { get { return GetAbilityObject(332); } }
        public IPgAIAbility MinigolemSelfSacrifice5 { get { return GetAbilityObject(333); } }
        public IPgAIAbility MinigolemPunch { get { return GetAbilityObject(334); } }
        public IPgAIAbility MinigolemPunch2 { get { return GetAbilityObject(335); } }
        public IPgAIAbility MinigolemPunch3 { get { return GetAbilityObject(336); } }
        public IPgAIAbility MinigolemPunch4 { get { return GetAbilityObject(337); } }
        public IPgAIAbility MinigolemPunch5 { get { return GetAbilityObject(338); } }
        public IPgAIAbility MinigolemHasteConcoction1 { get { return GetAbilityObject(339); } }
        public IPgAIAbility MinigolemHasteConcoction2 { get { return GetAbilityObject(340); } }
        public IPgAIAbility MinigolemHasteConcoction3 { get { return GetAbilityObject(341); } }
        public IPgAIAbility MinigolemFireBalm1 { get { return GetAbilityObject(342); } }
        public IPgAIAbility MinigolemFireBalm2 { get { return GetAbilityObject(343); } }
        public IPgAIAbility MinigolemFireBalm3 { get { return GetAbilityObject(344); } }
        public IPgAIAbility MinigolemFireBalm4 { get { return GetAbilityObject(345); } }
        public IPgAIAbility MinigolemFireBalm5 { get { return GetAbilityObject(346); } }
        public IPgAIAbility MinigolemRageAoEHeal1 { get { return GetAbilityObject(347); } }
        public IPgAIAbility MinigolemRageAoEHeal2 { get { return GetAbilityObject(348); } }
        public IPgAIAbility MinigolemRageAoEHeal3 { get { return GetAbilityObject(349); } }
        public IPgAIAbility MinigolemRageAoEHeal4 { get { return GetAbilityObject(350); } }
        public IPgAIAbility MinigolemRageAoEHeal5 { get { return GetAbilityObject(351); } }
        public IPgAIAbility MinigolemRageAcidToss1 { get { return GetAbilityObject(352); } }
        public IPgAIAbility MinigolemRageAcidToss2 { get { return GetAbilityObject(353); } }
        public IPgAIAbility MinigolemRageAcidToss3 { get { return GetAbilityObject(354); } }
        public IPgAIAbility MinigolemRageAcidToss4 { get { return GetAbilityObject(355); } }
        public IPgAIAbility MinigolemRageAcidToss5 { get { return GetAbilityObject(356); } }
        public IPgAIAbility TrainingGolemPunch { get { return GetAbilityObject(357); } }
        public IPgAIAbility TrainingGolemStun { get { return GetAbilityObject(358); } }
        public IPgAIAbility TrainingGolemHeal { get { return GetAbilityObject(359); } }
        public IPgAIAbility TrainingGolemHealB { get { return GetAbilityObject(360); } }
        public IPgAIAbility TrainingGolemFireBreath { get { return GetAbilityObject(361); } }
        public IPgAIAbility TrainingGolemFireBurst { get { return GetAbilityObject(362); } }
        public IPgAIAbility GrimalkinClaw { get { return GetAbilityObject(363); } }
        public IPgAIAbility GrimalkinBite { get { return GetAbilityObject(364); } }
        public IPgAIAbility GrimalkinPuncture { get { return GetAbilityObject(365); } }
        public IPgAIAbility WerewolfSword1 { get { return GetAbilityObject(366); } }
        public IPgAIAbility WerewolfSword2 { get { return GetAbilityObject(367); } }
        public IPgAIAbility WerewolfSwordStun { get { return GetAbilityObject(368); } }
        public IPgAIAbility WerewolfArrow1 { get { return GetAbilityObject(369); } }
        public IPgAIAbility WerewolfArrow2 { get { return GetAbilityObject(370); } }
        public IPgAIAbility WerewolfOmegaArrow { get { return GetAbilityObject(371); } }
        public IPgAIAbility NpcSmash { get { return GetAbilityObject(372); } }
        public IPgAIAbility NpcDoubleHitCurse { get { return GetAbilityObject(373); } }
        public IPgAIAbility NpcBlockingStance { get { return GetAbilityObject(374); } }
        public IPgAIAbility NpcHeadcracker { get { return GetAbilityObject(375); } }
        public IPgAIAbility StrigaClawA { get { return GetAbilityObject(376); } }
        public IPgAIAbility StrigaClawB { get { return GetAbilityObject(377); } }
        public IPgAIAbility StrigaReap { get { return GetAbilityObject(378); } }
        public IPgAIAbility StrigaReap2 { get { return GetAbilityObject(379); } }
        public IPgAIAbility StrigaFireBreath { get { return GetAbilityObject(380); } }
        public IPgAIAbility StrigaBuff { get { return GetAbilityObject(381); } }
        public IPgAIAbility GhostlyPunchA { get { return GetAbilityObject(382); } }
        public IPgAIAbility GhostlyPunchB { get { return GetAbilityObject(383); } }
        public IPgAIAbility GhostlyBurst { get { return GetAbilityObject(384); } }
        public IPgAIAbility GhostlyBossPunchA { get { return GetAbilityObject(385); } }
        public IPgAIAbility GhostlyBossPunchB { get { return GetAbilityObject(386); } }
        public IPgAIAbility GhostlyBossBurst { get { return GetAbilityObject(387); } }
        public IPgAIAbility GhostlyBolt { get { return GetAbilityObject(388); } }
        public IPgAIAbility InjectorBugBite { get { return GetAbilityObject(389); } }
        public IPgAIAbility InjectorBugInject { get { return GetAbilityObject(390); } }
        public IPgAIAbility InjectorBugInject2 { get { return GetAbilityObject(391); } }
        public IPgAIAbility FaceOfDeathKill { get { return GetAbilityObject(392); } }
        public IPgAIAbility WatcherFireball { get { return GetAbilityObject(393); } }
        public IPgAIAbility WatcherSlap { get { return GetAbilityObject(394); } }
        public IPgAIAbility WatcherAcidball { get { return GetAbilityObject(395); } }
        public IPgAIAbility RedCrystalBlast { get { return GetAbilityObject(396); } }
        public IPgAIAbility RedCrystalBurst { get { return GetAbilityObject(397); } }
        public IPgAIAbility TurretCrystalZap { get { return GetAbilityObject(398); } }
        public IPgAIAbility TurretCrystalZap2 { get { return GetAbilityObject(399); } }
        public IPgAIAbility TurretCrystalZapLongRange { get { return GetAbilityObject(400); } }
        public IPgAIAbility TurretCrystalZapLongRange2 { get { return GetAbilityObject(401); } }
        public IPgAIAbility DeathRay { get { return GetAbilityObject(402); } }
        public IPgAIAbility SpyPortalZap { get { return GetAbilityObject(403); } }
        public IPgAIAbility SpyPortalZap2 { get { return GetAbilityObject(404); } }
        public IPgAIAbility BitingVineBite { get { return GetAbilityObject(405); } }
        public IPgAIAbility BitingVineSpit { get { return GetAbilityObject(406); } }
        public IPgAIAbility BitingVineSpitB { get { return GetAbilityObject(407); } }
        public IPgAIAbility BitingVineCast { get { return GetAbilityObject(408); } }
        public IPgAIAbility BitingVineAppear { get { return GetAbilityObject(409); } }
        public IPgAIAbility BitingVineDisappear { get { return GetAbilityObject(410); } }
        public IPgAIAbility TrollClubA { get { return GetAbilityObject(411); } }
        public IPgAIAbility TrollClubB { get { return GetAbilityObject(412); } }
        public IPgAIAbility TrollKnockdown { get { return GetAbilityObject(413); } }
        public IPgAIAbility OgreClubA { get { return GetAbilityObject(414); } }
        public IPgAIAbility OgreClubB { get { return GetAbilityObject(415); } }
        public IPgAIAbility OgreThrow { get { return GetAbilityObject(416); } }
        public IPgAIAbility OgreStun { get { return GetAbilityObject(417); } }
        public IPgAIAbility FaeSwordA { get { return GetAbilityObject(418); } }
        public IPgAIAbility FaeSwordB { get { return GetAbilityObject(419); } }
        public IPgAIAbility FaeSwordKill { get { return GetAbilityObject(420); } }
        public IPgAIAbility DementiaPuckCurse { get { return GetAbilityObject(421); } }
        public IPgAIAbility FaeLightningSmiteHidden { get { return GetAbilityObject(422); } }
        public IPgAIAbility NecroSpark { get { return GetAbilityObject(423); } }
        public IPgAIAbility NecroDarknessWave { get { return GetAbilityObject(424); } }
        public IPgAIAbility NecroPainBubble { get { return GetAbilityObject(425); } }
        public IPgAIAbility NecroSparkPerching { get { return GetAbilityObject(426); } }
        public IPgAIAbility NecroDeathsHold { get { return GetAbilityObject(427); } }
        public IPgAIAbility DroachBiteA { get { return GetAbilityObject(428); } }
        public IPgAIAbility DroachBiteB { get { return GetAbilityObject(429); } }
        public IPgAIAbility DroachFireball { get { return GetAbilityObject(430); } }
        public IPgAIAbility DroachFireballPerching { get { return GetAbilityObject(431); } }
        public IPgAIAbility DroachBreatheFire { get { return GetAbilityObject(432); } }
        public IPgAIAbility DroachLightning { get { return GetAbilityObject(433); } }
        public IPgAIAbility DroachLightningPerching { get { return GetAbilityObject(434); } }
        public IPgAIAbility DroachShockingKnockback { get { return GetAbilityObject(435); } }
        public IPgAIAbility BasiliskClawA { get { return GetAbilityObject(436); } }
        public IPgAIAbility BasiliskClawB { get { return GetAbilityObject(437); } }
        public IPgAIAbility BasiliskToxicBite { get { return GetAbilityObject(438); } }
        public IPgAIAbility BasiliskDebuff { get { return GetAbilityObject(439); } }
        public IPgAIAbility BasiliskCastPerching { get { return GetAbilityObject(440); } }
        public IPgAIAbility CultistArrow1 { get { return GetAbilityObject(441); } }
        public IPgAIAbility CultistArrow2 { get { return GetAbilityObject(442); } }
        public IPgAIAbility CultistOmegaArrow { get { return GetAbilityObject(443); } }
        public IPgAIAbility CultistSword1 { get { return GetAbilityObject(444); } }
        public IPgAIAbility CultistSword2 { get { return GetAbilityObject(445); } }
        public IPgAIAbility CultistSwordStun { get { return GetAbilityObject(446); } }
        public IPgAIAbility BossMegaSword1 { get { return GetAbilityObject(447); } }
        public IPgAIAbility BossMegaSword2 { get { return GetAbilityObject(448); } }
        public IPgAIAbility SedgewickMegaSwordAngry { get { return GetAbilityObject(449); } }
        public IPgAIAbility BossMegaHammer { get { return GetAbilityObject(450); } }
        public IPgAIAbility BossMegaHammer2 { get { return GetAbilityObject(451); } }
        public IPgAIAbility BossMegaRageHammer { get { return GetAbilityObject(452); } }
        public IPgAIAbility ClaudiaTundraSpikes { get { return GetAbilityObject(453); } }
        public IPgAIAbility ClaudiaIceSpear { get { return GetAbilityObject(454); } }
        public IPgAIAbility ClaudiaBlizzard { get { return GetAbilityObject(455); } }
        public IPgAIAbility BigGolemHitA { get { return GetAbilityObject(456); } }
        public IPgAIAbility BigGolemHitB { get { return GetAbilityObject(457); } }
        public IPgAIAbility BigGolemFlingBoss { get { return GetAbilityObject(458); } }
        public IPgAIAbility BigGolemPerchFix { get { return GetAbilityObject(459); } }
        public IPgAIAbility BigGolemFlingBoss2 { get { return GetAbilityObject(460); } }
        public IPgAIAbility BigGolemSummonFireSnake { get { return GetAbilityObject(461); } }
        public IPgAIAbility BigGolemHitB_NoDisable { get { return GetAbilityObject(462); } }
        public IPgAIAbility BigGolemHitA_NoDisable { get { return GetAbilityObject(463); } }
        public IPgAIAbility BigGolemFling { get { return GetAbilityObject(464); } }
        public IPgAIAbility GhoulClawA { get { return GetAbilityObject(465); } }
        public IPgAIAbility GhoulClawB { get { return GetAbilityObject(466); } }
        public IPgAIAbility GhoulSelfBuff { get { return GetAbilityObject(467); } }
        public IPgAIAbility GhoulHammerA { get { return GetAbilityObject(468); } }
        public IPgAIAbility GhoulHammerB { get { return GetAbilityObject(469); } }
        public IPgAIAbility DragonWormSpitElectricity { get { return GetAbilityObject(470); } }
        public IPgAIAbility DragonWormBite { get { return GetAbilityObject(471); } }
        public IPgAIAbility DragonWormSmack { get { return GetAbilityObject(472); } }
        public IPgAIAbility DragonWormRage { get { return GetAbilityObject(473); } }
        public IPgAIAbility DragonWormEscape { get { return GetAbilityObject(474); } }
        public IPgAIAbility DragonWormSpitFire { get { return GetAbilityObject(475); } }
        public IPgAIAbility ColdSphereBurst { get { return GetAbilityObject(476); } }
        public IPgAIAbility ColdSphereFreezeBurst { get { return GetAbilityObject(477); } }
        public IPgAIAbility ManticoreBite { get { return GetAbilityObject(478); } }
        public IPgAIAbility ManticoreClaw { get { return GetAbilityObject(479); } }
        public IPgAIAbility ManticoreSting1 { get { return GetAbilityObject(480); } }
        public IPgAIAbility Manticoresting2 { get { return GetAbilityObject(481); } }
        public IPgAIAbility RakStaffHit { get { return GetAbilityObject(482); } }
        public IPgAIAbility RakStaffPin { get { return GetAbilityObject(483); } }
        public IPgAIAbility RakStaffBlock { get { return GetAbilityObject(484); } }
        public IPgAIAbility RakStaffHeavy { get { return GetAbilityObject(485); } }
        public IPgAIAbility RakSlash { get { return GetAbilityObject(486); } }
        public IPgAIAbility RakKnee { get { return GetAbilityObject(487); } }
        public IPgAIAbility RakKick { get { return GetAbilityObject(488); } }
        public IPgAIAbility RakBarrage { get { return GetAbilityObject(489); } }
        public IPgAIAbility RakSwordSlash { get { return GetAbilityObject(490); } }
        public IPgAIAbility RakHackingBlade { get { return GetAbilityObject(491); } }
        public IPgAIAbility RakDecapitate { get { return GetAbilityObject(492); } }
        public IPgAIAbility RakFireball { get { return GetAbilityObject(493); } }
        public IPgAIAbility RakBreatheFire { get { return GetAbilityObject(494); } }
        public IPgAIAbility RakRingOfFire { get { return GetAbilityObject(495); } }
        public IPgAIAbility RakToxinBomb { get { return GetAbilityObject(496); } }
        public IPgAIAbility RakAcidBomb { get { return GetAbilityObject(497); } }
        public IPgAIAbility RakHealingMist { get { return GetAbilityObject(498); } }
        public IPgAIAbility RakBasicShot { get { return GetAbilityObject(499); } }
        public IPgAIAbility RakHookShot { get { return GetAbilityObject(500); } }
        public IPgAIAbility RakBowBash { get { return GetAbilityObject(501); } }
        public IPgAIAbility RakAimedShot { get { return GetAbilityObject(502); } }
        public IPgAIAbility RakPoisonArrow { get { return GetAbilityObject(503); } }
        public IPgAIAbility RakMindreave { get { return GetAbilityObject(504); } }
        public IPgAIAbility RakPainBubble { get { return GetAbilityObject(505); } }
        public IPgAIAbility RakPanicCharge { get { return GetAbilityObject(506); } }
        public IPgAIAbility RakRevitalize { get { return GetAbilityObject(507); } }
        public IPgAIAbility RakReconstruct { get { return GetAbilityObject(508); } }
        public IPgAIAbility RakBossSlow { get { return GetAbilityObject(509); } }
        public IPgAIAbility RakBossPerchSlow { get { return GetAbilityObject(510); } }
        public IPgAIAbility FlapSkullBite { get { return GetAbilityObject(511); } }
        public IPgAIAbility FlapSkullBigBite { get { return GetAbilityObject(512); } }
        public IPgAIAbility MinotaurClub { get { return GetAbilityObject(513); } }
        public IPgAIAbility MinotaurRageClub { get { return GetAbilityObject(514); } }
        public IPgAIAbility MinotaurBoulder { get { return GetAbilityObject(515); } }
        public IPgAIAbility MinotaurBossRageClub { get { return GetAbilityObject(516); } }
        public IPgAIAbility CockatricePeck { get { return GetAbilityObject(517); } }
        public IPgAIAbility CockatriceTailWhip { get { return GetAbilityObject(518); } }
        public IPgAIAbility CockatriceParalyze { get { return GetAbilityObject(519); } }
        public IPgAIAbility GiantBeetleBite { get { return GetAbilityObject(520); } }
        public IPgAIAbility GiantBeetleInject { get { return GetAbilityObject(521); } }
        public IPgAIAbility GiantBeetleBoulderSpit { get { return GetAbilityObject(522); } }
        public IPgAIAbility BatIllusionSlashA { get { return GetAbilityObject(523); } }
        public IPgAIAbility BatIllusionSlashB { get { return GetAbilityObject(524); } }
        public IPgAIAbility BatIllusionBite { get { return GetAbilityObject(525); } }
        public IPgAIAbility GiantBatSlashA { get { return GetAbilityObject(526); } }
        public IPgAIAbility GiantBatSlashB { get { return GetAbilityObject(527); } }
        public IPgAIAbility GiantBatBite { get { return GetAbilityObject(528); } }
        public IPgAIAbility HagAgingTouch { get { return GetAbilityObject(529); } }
        public IPgAIAbility HagAgingScream { get { return GetAbilityObject(530); } }
        public IPgAIAbility TriffidClawA { get { return GetAbilityObject(531); } }
        public IPgAIAbility TriffidClawB { get { return GetAbilityObject(532); } }
        public IPgAIAbility TriffidTongue { get { return GetAbilityObject(533); } }
        public IPgAIAbility TriffidSpore { get { return GetAbilityObject(534); } }
        public IPgAIAbility TriffidShot { get { return GetAbilityObject(535); } }
        public IPgAIAbility TriffidTongueElite { get { return GetAbilityObject(536); } }
        public IPgAIAbility GiantScorpionClawA { get { return GetAbilityObject(537); } }
        public IPgAIAbility GiantScorpionClawB { get { return GetAbilityObject(538); } }
        public IPgAIAbility GiantScorpionSting { get { return GetAbilityObject(539); } }
        public IPgAIAbility KrakenBeak { get { return GetAbilityObject(540); } }
        public IPgAIAbility KrakenSlam { get { return GetAbilityObject(541); } }
        public IPgAIAbility KrakenRage { get { return GetAbilityObject(542); } }
        public IPgAIAbility KrakenBabyBeak { get { return GetAbilityObject(543); } }
        public IPgAIAbility KrakenBabySlam { get { return GetAbilityObject(544); } }
        public IPgAIAbility KrakenBabyRage { get { return GetAbilityObject(545); } }
        public IPgAIAbility RanalonHit { get { return GetAbilityObject(546); } }
        public IPgAIAbility RanalonHitB { get { return GetAbilityObject(547); } }
        public IPgAIAbility RanalonKick { get { return GetAbilityObject(548); } }
        public IPgAIAbility RanalonTongue { get { return GetAbilityObject(549); } }
        public IPgAIAbility RanalonZap { get { return GetAbilityObject(550); } }
        public IPgAIAbility RanalonZapB { get { return GetAbilityObject(551); } }
        public IPgAIAbility RanalonHeal { get { return GetAbilityObject(552); } }
        public IPgAIAbility RanalonRoot { get { return GetAbilityObject(553); } }
        public IPgAIAbility RanalonSelfBuff { get { return GetAbilityObject(554); } }
        public IPgAIAbility RanalonSelfBuffElite { get { return GetAbilityObject(555); } }
        public IPgAIAbility RanalonGuardianStab { get { return GetAbilityObject(556); } }
        public IPgAIAbility RanalonGuardianStabB { get { return GetAbilityObject(557); } }
        public IPgAIAbility RanalonGuardianBite { get { return GetAbilityObject(558); } }
        public IPgAIAbility RanalonGuardianBlind { get { return GetAbilityObject(559); } }
        public IPgAIAbility RanalonDoctrineKeeperStab { get { return GetAbilityObject(560); } }
        public IPgAIAbility RanalonDoctrineKeeperBlind { get { return GetAbilityObject(561); } }
        public IPgAIAbility BarghestBiteA { get { return GetAbilityObject(562); } }
        public IPgAIAbility BarghestBiteB { get { return GetAbilityObject(563); } }
        public IPgAIAbility BarghestDebuff { get { return GetAbilityObject(564); } }
        public IPgAIAbility WorghestDebuff { get { return GetAbilityObject(565); } }
        public IPgAIAbility BallistaFire { get { return GetAbilityObject(566); } }
        public IPgAIAbility BallistaFire_Long { get { return GetAbilityObject(567); } }
        public IPgAIAbility GargoyleSlamA { get { return GetAbilityObject(568); } }
        public IPgAIAbility GargoyleSlamB { get { return GetAbilityObject(569); } }
        public IPgAIAbility GargoyleStun { get { return GetAbilityObject(570); } }
        public IPgAIAbility GargoyleBossStun { get { return GetAbilityObject(571); } }
        public IPgAIAbility ScrayBite { get { return GetAbilityObject(572); } }
        public IPgAIAbility ScrayStab { get { return GetAbilityObject(573); } }
        public IPgAIAbility HippoBite { get { return GetAbilityObject(574); } }
        public IPgAIAbility HippoBiteAndHeal1 { get { return GetAbilityObject(575); } }
        public IPgAIAbility BigCatClaw_Pet { get { return GetAbilityObject(576); } }
        public IPgAIAbility BigCatPounce_Pet { get { return GetAbilityObject(577); } }
        public IPgAIAbility BigCatKill_Pet1 { get { return GetAbilityObject(578); } }
        public IPgAIAbility BigCatKill_Pet2 { get { return GetAbilityObject(579); } }
        public IPgAIAbility BigCatKill_Pet3 { get { return GetAbilityObject(580); } }
        public IPgAIAbility BigCatKill_Pet4 { get { return GetAbilityObject(581); } }
        public IPgAIAbility BigCatKill_Pet5 { get { return GetAbilityObject(582); } }
        public IPgAIAbility BigCatKill_Pet6 { get { return GetAbilityObject(583); } }
        public IPgAIAbility BigCatUltraKill_Pet1 { get { return GetAbilityObject(584); } }
        public IPgAIAbility BigCatUltraKill_Pet2 { get { return GetAbilityObject(585); } }
        public IPgAIAbility BigCatUltraKill_Pet3 { get { return GetAbilityObject(586); } }
        public IPgAIAbility BigCatUltraKill_Pet4 { get { return GetAbilityObject(587); } }
        public IPgAIAbility BigCatUltraKill_Pet5 { get { return GetAbilityObject(588); } }
        public IPgAIAbility BigCatUltraKill_Pet6 { get { return GetAbilityObject(589); } }
        public IPgAIAbility BigCatRoot_Pet1 { get { return GetAbilityObject(590); } }
        public IPgAIAbility BigCatRoot_Pet2 { get { return GetAbilityObject(591); } }
        public IPgAIAbility BigCatRoot_Pet3 { get { return GetAbilityObject(592); } }
        public IPgAIAbility BigCatRoot_Pet4 { get { return GetAbilityObject(593); } }
        public IPgAIAbility BigCatVuln_Pet1 { get { return GetAbilityObject(594); } }
        public IPgAIAbility BigCatVuln_Pet2 { get { return GetAbilityObject(595); } }
        public IPgAIAbility BigCatVuln_Pet3 { get { return GetAbilityObject(596); } }
        public IPgAIAbility BigCatVuln_Pet4 { get { return GetAbilityObject(597); } }
        public IPgAIAbility BigCatHeal_Pet1 { get { return GetAbilityObject(598); } }
        public IPgAIAbility BigCatHeal_Pet2 { get { return GetAbilityObject(599); } }
        public IPgAIAbility BigCatHeal_Pet3 { get { return GetAbilityObject(600); } }
        public IPgAIAbility BigCatHeal_Pet4 { get { return GetAbilityObject(601); } }
        public IPgAIAbility BigCatHeal_Pet5 { get { return GetAbilityObject(602); } }
        public IPgAIAbility BigCatHeal_Pet6 { get { return GetAbilityObject(603); } }
        public IPgAIAbility GrimalkinPuncture_Pet1 { get { return GetAbilityObject(604); } }
        public IPgAIAbility GrimalkinPuncture_Pet2 { get { return GetAbilityObject(605); } }
        public IPgAIAbility GrimalkinPuncture_Pet3 { get { return GetAbilityObject(606); } }
        public IPgAIAbility GrimalkinPuncture_Pet4 { get { return GetAbilityObject(607); } }
        public IPgAIAbility GrimalkinPuncture_Pet5 { get { return GetAbilityObject(608); } }
        public IPgAIAbility GrimalkinPuncture_Pet6 { get { return GetAbilityObject(609); } }
        public IPgAIAbility GrimalkinFlee_Pet1 { get { return GetAbilityObject(610); } }
        public IPgAIAbility GrimalkinFlee_Pet2 { get { return GetAbilityObject(611); } }
        public IPgAIAbility GrimalkinFlee_Pet3 { get { return GetAbilityObject(612); } }
        public IPgAIAbility RatBite_Pet { get { return GetAbilityObject(613); } }
        public IPgAIAbility RatClaw_Pet { get { return GetAbilityObject(614); } }
        public IPgAIAbility RatDeRage_Pet1 { get { return GetAbilityObject(615); } }
        public IPgAIAbility RatDeRage_Pet2 { get { return GetAbilityObject(616); } }
        public IPgAIAbility RatDeRage_Pet3 { get { return GetAbilityObject(617); } }
        public IPgAIAbility RatDeRage_Pet4 { get { return GetAbilityObject(618); } }
        public IPgAIAbility RatDeRage_Pet5 { get { return GetAbilityObject(619); } }
        public IPgAIAbility RatDeRage_Pet6 { get { return GetAbilityObject(620); } }
        public IPgAIAbility RatHeal_Pet1 { get { return GetAbilityObject(621); } }
        public IPgAIAbility RatHeal_Pet2 { get { return GetAbilityObject(622); } }
        public IPgAIAbility RatHeal_Pet3 { get { return GetAbilityObject(623); } }
        public IPgAIAbility RatHeal_Pet4 { get { return GetAbilityObject(624); } }
        public IPgAIAbility RatHeal_Pet5 { get { return GetAbilityObject(625); } }
        public IPgAIAbility RatHeal_Pet6 { get { return GetAbilityObject(626); } }
        public IPgAIAbility RatVuln_Pet1 { get { return GetAbilityObject(627); } }
        public IPgAIAbility RatVuln_Pet2 { get { return GetAbilityObject(628); } }
        public IPgAIAbility RatVuln_Pet3 { get { return GetAbilityObject(629); } }
        public IPgAIAbility RatVuln_Pet4 { get { return GetAbilityObject(630); } }
        public IPgAIAbility FireRatBite_Pet { get { return GetAbilityObject(631); } }
        public IPgAIAbility FireRatClaw_Pet { get { return GetAbilityObject(632); } }
        public IPgAIAbility RatBurn_Pet1 { get { return GetAbilityObject(633); } }
        public IPgAIAbility RatBurn_Pet2 { get { return GetAbilityObject(634); } }
        public IPgAIAbility RatBurn_Pet3 { get { return GetAbilityObject(635); } }
        public IPgAIAbility RatBurn_Pet4 { get { return GetAbilityObject(636); } }
        public IPgAIAbility RatBurn_Pet5 { get { return GetAbilityObject(637); } }
        public IPgAIAbility RatBurn_Pet6 { get { return GetAbilityObject(638); } }
        public IPgAIAbility BearBite_Pet { get { return GetAbilityObject(639); } }
        public IPgAIAbility BearClaw_Pet { get { return GetAbilityObject(640); } }
        public IPgAIAbility BearTaunt_Pet1 { get { return GetAbilityObject(641); } }
        public IPgAIAbility BearTaunt_Pet2 { get { return GetAbilityObject(642); } }
        public IPgAIAbility BearTaunt_Pet3 { get { return GetAbilityObject(643); } }
        public IPgAIAbility BearTaunt_Pet4 { get { return GetAbilityObject(644); } }
        public IPgAIAbility BearTaunt_Pet5 { get { return GetAbilityObject(645); } }
        public IPgAIAbility BearTaunt_Pet6 { get { return GetAbilityObject(646); } }
        public IPgAIAbility BearStun_Pet1 { get { return GetAbilityObject(647); } }
        public IPgAIAbility BearStun_Pet2 { get { return GetAbilityObject(648); } }
        public IPgAIAbility BearStun_Pet3 { get { return GetAbilityObject(649); } }
        public IPgAIAbility BearStun_Pet4 { get { return GetAbilityObject(650); } }
        public IPgAIAbility BearWarmth_Pet1 { get { return GetAbilityObject(651); } }
        public IPgAIAbility BearWarmth_Pet2 { get { return GetAbilityObject(652); } }
        public IPgAIAbility BearWarmth_Pet3 { get { return GetAbilityObject(653); } }
        public IPgAIAbility BearWarmth_Pet4 { get { return GetAbilityObject(654); } }
        public IPgAIAbility BearWarmth_Pet5 { get { return GetAbilityObject(655); } }
        public IPgAIAbility BearWarmth_Pet6 { get { return GetAbilityObject(656); } }
        public IPgAIAbility BearSelfHeal_Pet1 { get { return GetAbilityObject(657); } }
        public IPgAIAbility BearSelfHeal_Pet2 { get { return GetAbilityObject(658); } }
        public IPgAIAbility BearSelfHeal_Pet3 { get { return GetAbilityObject(659); } }
        public IPgAIAbility BearSelfHeal_Pet4 { get { return GetAbilityObject(660); } }
        public IPgAIAbility BearSelfHeal_Pet5 { get { return GetAbilityObject(661); } }
        public IPgAIAbility BearSelfHeal_Pet6 { get { return GetAbilityObject(662); } }
        public IPgAIAbility BearUltra_Pet1 { get { return GetAbilityObject(663); } }
        public IPgAIAbility BearUltra_Pet2 { get { return GetAbilityObject(664); } }
        public IPgAIAbility BearUltra_Pet3 { get { return GetAbilityObject(665); } }
        public IPgAIAbility BearUltra_Pet4 { get { return GetAbilityObject(666); } }
        public IPgAIAbility BearUltra_Pet5 { get { return GetAbilityObject(667); } }
        public IPgAIAbility BearUltra_Pet6 { get { return GetAbilityObject(668); } }
    }
}
