namespace PgJsonObjects
{
    public class PgAIAbilitySet
    {
        public PgAIAbility AnimalBite { get; set; }
        public PgAIAbility AnimalClaw { get; set; }
        public PgAIAbility AnimalOmegaBite { get; set; }
        public PgAIAbility AnimalOmegaBite2 { get; set; }
        public PgAIAbility AnimalHoofFrontKick { get; set; }
        public PgAIAbility AnimalHoofRageKick { get; set; }
        public PgAIAbility AnimalHoofRageKick2 { get; set; }
        public PgAIAbility AnimalHoofFieryFrontKick { get; set; }
        public PgAIAbility AnimalHoofFieryFrontKick2 { get; set; }
        public PgAIAbility ElectricPigHitAndRun { get; set; }
        public PgAIAbility ElectricPigStun { get; set; }
        public PgAIAbility ElectricPigAoEStun { get; set; }
        public PgAIAbility LamiaMindControl { get; set; }
        public PgAIAbility LamiaRage { get; set; }
        public PgAIAbility SlimeKick { get; set; }
        public PgAIAbility SlimeKickB { get; set; }
        public PgAIAbility SlimeBite { get; set; }
        public PgAIAbility SlimeBiteB { get; set; }
        public PgAIAbility Slime_SummonSlime { get; set; }
        public PgAIAbility SlimeSpit { get; set; }
        public PgAIAbility SlimeSuperSpit { get; set; }
        public PgAIAbility IceSlimeKick { get; set; }
        public PgAIAbility IceSlimeKickB { get; set; }
        public PgAIAbility IceSlimeBite { get; set; }
        public PgAIAbility IceSlimeBiteB { get; set; }
        public PgAIAbility BossSlimeKick { get; set; }
        public PgAIAbility BossSlimeKickB { get; set; }
        public PgAIAbility BossSlime_SummonSlime1 { get; set; }
        public PgAIAbility BossSlimeKick2 { get; set; }
        public PgAIAbility BossSlimeKick2B { get; set; }
        public PgAIAbility BossSlime_SummonSlime4Elite { get; set; }
        public PgAIAbility AnimalHeal { get; set; }
        public PgAIAbility AnimalHeal2 { get; set; }
        public PgAIAbility AnimalHeal3 { get; set; }
        public PgAIAbility IceCockPeck { get; set; }
        public PgAIAbility IceCockFreeze { get; set; }
        public PgAIAbility NightmareHoof { get; set; }
        public PgAIAbility NightmareDarknessBomb { get; set; }
        public PgAIAbility CiervosNightmareHoof { get; set; }
        public PgAIAbility CiervosDarknessBomb { get; set; }
        public PgAIAbility Myconian_Bash { get; set; }
        public PgAIAbility Myconian_Mindspores { get; set; }
        public PgAIAbility Myconian_Drain { get; set; }
        public PgAIAbility Myconian_BossBash { get; set; }
        public PgAIAbility Myconian_Mindspores_Permanent { get; set; }
        public PgAIAbility Myconian_TidalCurse { get; set; }
        public PgAIAbility Myconian_Shock { get; set; }
        public PgAIAbility AlienDog_Punch { get; set; }
        public PgAIAbility AlienDog_Punch2 { get; set; }
        public PgAIAbility AlienDog_RagePunch { get; set; }
        public PgAIAbility MushroomMonster_Bite { get; set; }
        public PgAIAbility MushroomMonster_Spit1 { get; set; }
        public PgAIAbility MushroomMonster_Spit2 { get; set; }
        public PgAIAbility MushroomMonster_SummonMushroomSpawn1 { get; set; }
        public PgAIAbility MushroomMonster_SummonMushroomSpawn2 { get; set; }
        public PgAIAbility MushroomMonster_SummonMushroomSpawn3 { get; set; }
        public PgAIAbility MushroomMonster_SpawnSpit1 { get; set; }
        public PgAIAbility MushroomMonster_SpawnSpit2 { get; set; }
        public PgAIAbility MushroomMonster_SpawnSuperSpit1 { get; set; }
        public PgAIAbility MushroomMonster_SpawnSuperSpit2 { get; set; }
        public PgAIAbility MaronesaStomp { get; set; }
        public PgAIAbility MaronesaInfect { get; set; }
        public PgAIAbility WormBite1 { get; set; }
        public PgAIAbility WormSpit1 { get; set; }
        public PgAIAbility WormShove1 { get; set; }
        public PgAIAbility WormInfect1 { get; set; }
        public PgAIAbility WormSpit2 { get; set; }
        public PgAIAbility WormBossSpit { get; set; }
        public PgAIAbility WormBossAcidBurst { get; set; }
        public PgAIAbility GnasherBite { get; set; }
        public PgAIAbility GnasherRend { get; set; }
        public PgAIAbility Dinoslash { get; set; }
        public PgAIAbility Dinoslash2 { get; set; }
        public PgAIAbility Dinobite { get; set; }
        public PgAIAbility Dinobite2 { get; set; }
        public PgAIAbility Dinowhap { get; set; }
        public PgAIAbility Peck { get; set; }
        public PgAIAbility AnimalFlee { get; set; }
        public PgAIAbility HippogriffPeck { get; set; }
        public PgAIAbility HippogriffSlashes { get; set; }
        public PgAIAbility HippogriffBossSlashes { get; set; }
        public PgAIAbility RatBite { get; set; }
        public PgAIAbility RatClaw { get; set; }
        public PgAIAbility FireRatBite { get; set; }
        public PgAIAbility FireRatClaw { get; set; }
        public PgAIAbility GoblinZapBall { get; set; }
        public PgAIAbility GoblinHateZapBall { get; set; }
        public PgAIAbility GoblinHateZapBall2 { get; set; }
        public PgAIAbility RhinoHorn { get; set; }
        public PgAIAbility RhinoRage { get; set; }
        public PgAIAbility RhinoFireball { get; set; }
        public PgAIAbility RhinoBossRage { get; set; }
        public PgAIAbility YetiPunch { get; set; }
        public PgAIAbility YetiEncase { get; set; }
        public PgAIAbility YetiDebuff { get; set; }
        public PgAIAbility YetiBoulderThrow { get; set; }
        public PgAIAbility YetiBarrage { get; set; }
        public PgAIAbility YetiRoarStun { get; set; }
        public PgAIAbility YetiFlingAway { get; set; }
        public PgAIAbility YetiIceBallThrow { get; set; }
        public PgAIAbility YetiIceSpear { get; set; }
        public PgAIAbility YetiColdOrb { get; set; }
        public PgAIAbility YetiFrostRing { get; set; }
        public PgAIAbility WorgBite { get; set; }
        public PgAIAbility WorgOmegaBite { get; set; }
        public PgAIAbility BearBite { get; set; }
        public PgAIAbility BearCrush { get; set; }
        public PgAIAbility BrainBite { get; set; }
        public PgAIAbility BrainDrain { get; set; }
        public PgAIAbility BrainDrain2 { get; set; }
        public PgAIAbility BigCatClaw { get; set; }
        public PgAIAbility BigCatPounce { get; set; }
        public PgAIAbility BigCatRagePounce { get; set; }
        public PgAIAbility BigCatDebuff { get; set; }
        public PgAIAbility SpiderBite { get; set; }
        public PgAIAbility SpiderFireball { get; set; }
        public PgAIAbility SpiderBossFreePin { get; set; }
        public PgAIAbility SpiderKill2 { get; set; }
        public PgAIAbility SpiderInject { get; set; }
        public PgAIAbility SpiderKill { get; set; }
        public PgAIAbility AcidBall1 { get; set; }
        public PgAIAbility SpiderPin { get; set; }
        public PgAIAbility SpiderKill3 { get; set; }
        public PgAIAbility AcidBall2 { get; set; }
        public PgAIAbility AcidSpew1 { get; set; }
        public PgAIAbility AcidExplosion1 { get; set; }
        public PgAIAbility AcidExplosion2 { get; set; }
        public PgAIAbility SpiderIncubate { get; set; }
        public PgAIAbility MantisClaw { get; set; }
        public PgAIAbility MantisRage { get; set; }
        public PgAIAbility MantisAcidBurst { get; set; }
        public PgAIAbility SherzatClaw { get; set; }
        public PgAIAbility SherzatAcidSpit { get; set; }
        public PgAIAbility SherzatDisintegrate { get; set; }
        public PgAIAbility MantisSwipe { get; set; }
        public PgAIAbility MantisBlast { get; set; }
        public PgAIAbility SnailStrike { get; set; }
        public PgAIAbility SnailRage { get; set; }
        public PgAIAbility SnailRageB { get; set; }
        public PgAIAbility SnailRageC { get; set; }
        public PgAIAbility HookClaw { get; set; }
        public PgAIAbility HookAcid { get; set; }
        public PgAIAbility HookRage { get; set; }
        public PgAIAbility UndeadSword1 { get; set; }
        public PgAIAbility UndeadSword2 { get; set; }
        public PgAIAbility UndeadSwordAngry { get; set; }
        public PgAIAbility UndeadMegaSword1 { get; set; }
        public PgAIAbility UndeadMegaSword2 { get; set; }
        public PgAIAbility UndeadMegaSwordAngry { get; set; }
        public PgAIAbility UndeadLightningSmite { get; set; }
        public PgAIAbility UndeadPhysicalShield { get; set; }
        public PgAIAbility UndeadSword1B { get; set; }
        public PgAIAbility UndeadFireballA { get; set; }
        public PgAIAbility UndeadFireballB { get; set; }
        public PgAIAbility UndeadFireballB2 { get; set; }
        public PgAIAbility UndeadIceBall1 { get; set; }
        public PgAIAbility UndeadFreezeBall { get; set; }
        public PgAIAbility UndeadFireballLongA { get; set; }
        public PgAIAbility UndeadFireballLongB { get; set; }
        public PgAIAbility UndeadFireballLongB2 { get; set; }
        public PgAIAbility KhyrulekCurseBall { get; set; }
        public PgAIAbility UrsulaFireball1 { get; set; }
        public PgAIAbility UrsulaFireball1B { get; set; }
        public PgAIAbility UrsulaFireball2 { get; set; }
        public PgAIAbility UrsulaIceball1 { get; set; }
        public PgAIAbility UrsulaIceball1B { get; set; }
        public PgAIAbility UrsulaIceball2 { get; set; }
        public PgAIAbility UrsulaSummon { get; set; }
        public PgAIAbility UrsulaRage { get; set; }
        public PgAIAbility UndeadFireballA2 { get; set; }
        public PgAIAbility BigHeadCurseball { get; set; }
        public PgAIAbility UndeadArrow1 { get; set; }
        public PgAIAbility UndeadArrow2 { get; set; }
        public PgAIAbility UndeadOmegaArrow { get; set; }
        public PgAIAbility PetUndeadArrow1 { get; set; }
        public PgAIAbility PetUndeadArrow2 { get; set; }
        public PgAIAbility PetUndeadOmegaArrow { get; set; }
        public PgAIAbility UndeadGrappleArrow1 { get; set; }
        public PgAIAbility UndeadSelfDestruct { get; set; }
        public PgAIAbility UndeadDarknessBall { get; set; }
        public PgAIAbility UndeadBoneWhirlwind { get; set; }
        public PgAIAbility PetUndeadSword1 { get; set; }
        public PgAIAbility PetUndeadSword2 { get; set; }
        public PgAIAbility PetUndeadSwordAngry { get; set; }
        public PgAIAbility PetUndeadFireballA { get; set; }
        public PgAIAbility PetUndeadFireballB { get; set; }
        public PgAIAbility PetUndeadDefensiveBurst { get; set; }
        public PgAIAbility PetUndeadPunch1 { get; set; }
        public PgAIAbility ZombiePunch { get; set; }
        public PgAIAbility ZombieBite { get; set; }
        public PgAIAbility GoblinSpear1 { get; set; }
        public PgAIAbility GoblinSpear2 { get; set; }
        public PgAIAbility GoblinRageSpear1 { get; set; }
        public PgAIAbility GoblinRageSpear2 { get; set; }
        public PgAIAbility GoblinHeal1 { get; set; }
        public PgAIAbility GoblinHeal2 { get; set; }
        public PgAIAbility GoblinPunch { get; set; }
        public PgAIAbility GoblinArrow1 { get; set; }
        public PgAIAbility GoblinArrow2 { get; set; }
        public PgAIAbility GoblinRageArrow1 { get; set; }
        public PgAIAbility GoblinRageArrow2 { get; set; }
        public PgAIAbility GoblinSpreadZapBall { get; set; }
        public PgAIAbility GoblinBossLightning { get; set; }
        public PgAIAbility GoblinArmorBuff { get; set; }
        public PgAIAbility MummySlamA { get; set; }
        public PgAIAbility MummySlamB { get; set; }
        public PgAIAbility MummySlamCombo { get; set; }
        public PgAIAbility MummyWrapA { get; set; }
        public PgAIAbility MummyWrapB { get; set; }
        public PgAIAbility MummyWrapRage { get; set; }
        public PgAIAbility BarutiWrapA { get; set; }
        public PgAIAbility BarutiWrapB { get; set; }
        public PgAIAbility BarutiWrapRage { get; set; }
        public PgAIAbility FireWallAttack1 { get; set; }
        public PgAIAbility FireWallDotAttack1 { get; set; }
        public PgAIAbility FireSnakeExplosion1 { get; set; }
        public PgAIAbility FireTrapAttack1 { get; set; }
        public PgAIAbility HealingAura1 { get; set; }
        public PgAIAbility HealingAura2 { get; set; }
        public PgAIAbility HealingAura3 { get; set; }
        public PgAIAbility HealingAura4 { get; set; }
        public PgAIAbility DruidHealingSanctuaryHeal { get; set; }
        public PgAIAbility AcidAuraBall1 { get; set; }
        public PgAIAbility AcidAuraBall2 { get; set; }
        public PgAIAbility AcidAuraBall3 { get; set; }
        public PgAIAbility AcidAuraBall4 { get; set; }
        public PgAIAbility ElectricityAura1 { get; set; }
        public PgAIAbility ElectricityAuraBolt1 { get; set; }
        public PgAIAbility ReboundAura1 { get; set; }
        public PgAIAbility ColdAuraBurst { get; set; }
        public PgAIAbility WebStick { get; set; }
        public PgAIAbility IcySlam { get; set; }
        public PgAIAbility IcyCocoon { get; set; }
        public PgAIAbility IcyCocoon2 { get; set; }
        public PgAIAbility ElementalSlam { get; set; }
        public PgAIAbility ElementalBees { get; set; }
        public PgAIAbility ElementalBees2 { get; set; }
        public PgAIAbility FaeLightningSmite { get; set; }
        public PgAIAbility TotalHorrorAttack { get; set; }
        public PgAIAbility TotalHorrorStretch { get; set; }
        public PgAIAbility TotalHorrorHeal { get; set; }
        public PgAIAbility TotalHorrorHeal2 { get; set; }
        public PgAIAbility SheepBomb1 { get; set; }
        public PgAIAbility SlugPoisonBite { get; set; }
        public PgAIAbility SlugPoisonRage { get; set; }
        public PgAIAbility SlugPoisonBite2 { get; set; }
        public PgAIAbility SlugPoisonRage2 { get; set; }
        public PgAIAbility SlugPoisonBite3 { get; set; }
        public PgAIAbility SlugPoisonRage3 { get; set; }
        public PgAIAbility TornadoJolt1 { get; set; }
        public PgAIAbility TornadoFling { get; set; }
        public PgAIAbility TornadoToss { get; set; }
        public PgAIAbility TheFogCurse { get; set; }
        public PgAIAbility MonsterWerewolfPouncingRake { get; set; }
        public PgAIAbility MonsterWerewolfPackAttack { get; set; }
        public PgAIAbility MonsterWerewolfHowl { get; set; }
        public PgAIAbility Werewolf_Summon_Rage { get; set; }
        public PgAIAbility Werewolf_Summon_Opener { get; set; }
        public PgAIAbility BleddynHowl { get; set; }
        public PgAIAbility OrcSwordSlash { get; set; }
        public PgAIAbility OrcParry { get; set; }
        public PgAIAbility OrcFinishingBlow { get; set; }
        public PgAIAbility OrcHipThrow { get; set; }
        public PgAIAbility OrcKneeKick { get; set; }
        public PgAIAbility OrcPunch { get; set; }
        public PgAIAbility OrcArrow1 { get; set; }
        public PgAIAbility OrcArrow2 { get; set; }
        public PgAIAbility OrcStaffSmash { get; set; }
        public PgAIAbility OrcFireball { get; set; }
        public PgAIAbility OrcHeal1 { get; set; }
        public PgAIAbility OrcHeal2 { get; set; }
        public PgAIAbility OrcEvasionBubble { get; set; }
        public PgAIAbility OrcElectricStun { get; set; }
        public PgAIAbility OrcFireBolts { get; set; }
        public PgAIAbility OrcKnockbackBolt { get; set; }
        public PgAIAbility OrcSummonUrak2 { get; set; }
        public PgAIAbility OrcSwordSlashFire { get; set; }
        public PgAIAbility OrcParryFire { get; set; }
        public PgAIAbility OrcFinishingBlowFire { get; set; }
        public PgAIAbility OrcSummonSigil1 { get; set; }
        public PgAIAbility OrcSpearAttack { get; set; }
        public PgAIAbility OrcHalberdAttack { get; set; }
        public PgAIAbility OrcAreaHalberdAttack { get; set; }
        public PgAIAbility OrcDebuffArrow { get; set; }
        public PgAIAbility OrcSlice { get; set; }
        public PgAIAbility OrcVenomstrike1 { get; set; }
        public PgAIAbility OrcVenomstrike0 { get; set; }
        public PgAIAbility OrcLieutenantDebuffTaunt { get; set; }
        public PgAIAbility OrcAreaHalberdBoss { get; set; }
        public PgAIAbility OrcDeathsHold { get; set; }
        public PgAIAbility GazlukPriest1Special { get; set; }
        public PgAIAbility GazlukPriest2Special { get; set; }
        public PgAIAbility GazlukPriest3Special { get; set; }
        public PgAIAbility OrcExtinguishLife { get; set; }
        public PgAIAbility OrcDarknessBall { get; set; }
        public PgAIAbility OrcWaveOfDarkness { get; set; }
        public PgAIAbility EnemyMinigolemPunch { get; set; }
        public PgAIAbility EnemyMinigolemHeal { get; set; }
        public PgAIAbility EnemyMinigolemExplode { get; set; }
        public PgAIAbility MinigolemBombToss { get; set; }
        public PgAIAbility MinigolemBombToss2 { get; set; }
        public PgAIAbility MinigolemBombToss3 { get; set; }
        public PgAIAbility MinigolemBombToss4 { get; set; }
        public PgAIAbility MinigolemBombToss5 { get; set; }
        public PgAIAbility MinigolemAoEHeal { get; set; }
        public PgAIAbility MinigolemAoEHeal2 { get; set; }
        public PgAIAbility MinigolemAoEHeal3 { get; set; }
        public PgAIAbility MinigolemAoEHeal4 { get; set; }
        public PgAIAbility MinigolemAoEHeal5 { get; set; }
        public PgAIAbility MinigolemSelfDestruct { get; set; }
        public PgAIAbility MinigolemSelfDestruct2 { get; set; }
        public PgAIAbility MinigolemSelfDestruct3 { get; set; }
        public PgAIAbility MinigolemSelfDestruct4 { get; set; }
        public PgAIAbility MinigolemSelfDestruct5 { get; set; }
        public PgAIAbility MinigolemAoEPower { get; set; }
        public PgAIAbility MinigolemAoEPower2 { get; set; }
        public PgAIAbility MinigolemAoEPower3 { get; set; }
        public PgAIAbility MinigolemAoEPower4 { get; set; }
        public PgAIAbility MinigolemAoEPower5 { get; set; }
        public PgAIAbility MinigolemHeal { get; set; }
        public PgAIAbility MinigolemHeal2 { get; set; }
        public PgAIAbility MinigolemHeal3 { get; set; }
        public PgAIAbility MinigolemHeal4 { get; set; }
        public PgAIAbility MinigolemHeal5 { get; set; }
        public PgAIAbility MinigolemDoomAdmixture { get; set; }
        public PgAIAbility MinigolemDoomAdmixture2 { get; set; }
        public PgAIAbility MinigolemDoomAdmixture3 { get; set; }
        public PgAIAbility MinigolemDoomAdmixture4 { get; set; }
        public PgAIAbility MinigolemDoomAdmixture5 { get; set; }
        public PgAIAbility MinigolemSelfSacrifice { get; set; }
        public PgAIAbility MinigolemSelfSacrifice2 { get; set; }
        public PgAIAbility MinigolemSelfSacrifice3 { get; set; }
        public PgAIAbility MinigolemSelfSacrifice4 { get; set; }
        public PgAIAbility MinigolemSelfSacrifice5 { get; set; }
        public PgAIAbility MinigolemPunch { get; set; }
        public PgAIAbility MinigolemPunch2 { get; set; }
        public PgAIAbility MinigolemPunch3 { get; set; }
        public PgAIAbility MinigolemPunch4 { get; set; }
        public PgAIAbility MinigolemPunch5 { get; set; }
        public PgAIAbility MinigolemHasteConcoction1 { get; set; }
        public PgAIAbility MinigolemHasteConcoction2 { get; set; }
        public PgAIAbility MinigolemHasteConcoction3 { get; set; }
        public PgAIAbility MinigolemFireBalm1 { get; set; }
        public PgAIAbility MinigolemFireBalm2 { get; set; }
        public PgAIAbility MinigolemFireBalm3 { get; set; }
        public PgAIAbility MinigolemFireBalm4 { get; set; }
        public PgAIAbility MinigolemFireBalm5 { get; set; }
        public PgAIAbility MinigolemRageAoEHeal1 { get; set; }
        public PgAIAbility MinigolemRageAoEHeal2 { get; set; }
        public PgAIAbility MinigolemRageAoEHeal3 { get; set; }
        public PgAIAbility MinigolemRageAoEHeal4 { get; set; }
        public PgAIAbility MinigolemRageAoEHeal5 { get; set; }
        public PgAIAbility MinigolemRageAcidToss1 { get; set; }
        public PgAIAbility MinigolemRageAcidToss2 { get; set; }
        public PgAIAbility MinigolemRageAcidToss3 { get; set; }
        public PgAIAbility MinigolemRageAcidToss4 { get; set; }
        public PgAIAbility MinigolemRageAcidToss5 { get; set; }
        public PgAIAbility TrainingGolemPunch { get; set; }
        public PgAIAbility TrainingGolemStun { get; set; }
        public PgAIAbility TrainingGolemHeal { get; set; }
        public PgAIAbility TrainingGolemHealB { get; set; }
        public PgAIAbility TrainingGolemFireBreath { get; set; }
        public PgAIAbility TrainingGolemFireBurst { get; set; }
        public PgAIAbility GrimalkinClaw { get; set; }
        public PgAIAbility GrimalkinBite { get; set; }
        public PgAIAbility GrimalkinPuncture { get; set; }
        public PgAIAbility WerewolfSword1 { get; set; }
        public PgAIAbility WerewolfSword2 { get; set; }
        public PgAIAbility WerewolfSwordStun { get; set; }
        public PgAIAbility WerewolfArrow1 { get; set; }
        public PgAIAbility WerewolfArrow2 { get; set; }
        public PgAIAbility WerewolfOmegaArrow { get; set; }
        public PgAIAbility NpcSmash { get; set; }
        public PgAIAbility NpcDoubleHitCurse { get; set; }
        public PgAIAbility NpcBlockingStance { get; set; }
        public PgAIAbility NpcHeadcracker { get; set; }
        public PgAIAbility StrigaClawA { get; set; }
        public PgAIAbility StrigaClawB { get; set; }
        public PgAIAbility StrigaReap { get; set; }
        public PgAIAbility StrigaReap2 { get; set; }
        public PgAIAbility StrigaFireBreath { get; set; }
        public PgAIAbility StrigaBuff { get; set; }
        public PgAIAbility GhostlyPunchA { get; set; }
        public PgAIAbility GhostlyPunchB { get; set; }
        public PgAIAbility GhostlyBurst { get; set; }
        public PgAIAbility GhostlyBossPunchA { get; set; }
        public PgAIAbility GhostlyBossPunchB { get; set; }
        public PgAIAbility GhostlyBossBurst { get; set; }
        public PgAIAbility GhostlyBolt { get; set; }
        public PgAIAbility InjectorBugBite { get; set; }
        public PgAIAbility InjectorBugInject { get; set; }
        public PgAIAbility InjectorBugInject2 { get; set; }
        public PgAIAbility FaceOfDeathKill { get; set; }
        public PgAIAbility WatcherFireball { get; set; }
        public PgAIAbility WatcherSlap { get; set; }
        public PgAIAbility WatcherAcidball { get; set; }
        public PgAIAbility RedCrystalBlast { get; set; }
        public PgAIAbility RedCrystalBurst { get; set; }
        public PgAIAbility TurretCrystalZap { get; set; }
        public PgAIAbility TurretCrystalZap2 { get; set; }
        public PgAIAbility TurretCrystalZapLongRange { get; set; }
        public PgAIAbility TurretCrystalZapLongRange2 { get; set; }
        public PgAIAbility DeathRay { get; set; }
        public PgAIAbility SpyPortalZap { get; set; }
        public PgAIAbility SpyPortalZap2 { get; set; }
        public PgAIAbility BitingVineBite { get; set; }
        public PgAIAbility BitingVineSpit { get; set; }
        public PgAIAbility BitingVineSpitB { get; set; }
        public PgAIAbility BitingVineCast { get; set; }
        public PgAIAbility BitingVineAppear { get; set; }
        public PgAIAbility BitingVineDisappear { get; set; }
        public PgAIAbility TrollClubA { get; set; }
        public PgAIAbility TrollClubB { get; set; }
        public PgAIAbility TrollKnockdown { get; set; }
        public PgAIAbility OgreClubA { get; set; }
        public PgAIAbility OgreClubB { get; set; }
        public PgAIAbility OgreThrow { get; set; }
        public PgAIAbility OgreStun { get; set; }
        public PgAIAbility FaeSwordA { get; set; }
        public PgAIAbility FaeSwordB { get; set; }
        public PgAIAbility FaeSwordKill { get; set; }
        public PgAIAbility DementiaPuckCurse { get; set; }
        public PgAIAbility FaeLightningSmiteHidden { get; set; }
        public PgAIAbility NecroSpark { get; set; }
        public PgAIAbility NecroDarknessWave { get; set; }
        public PgAIAbility NecroPainBubble { get; set; }
        public PgAIAbility NecroSparkPerching { get; set; }
        public PgAIAbility NecroDeathsHold { get; set; }
        public PgAIAbility DroachBiteA { get; set; }
        public PgAIAbility DroachBiteB { get; set; }
        public PgAIAbility DroachFireball { get; set; }
        public PgAIAbility DroachFireballPerching { get; set; }
        public PgAIAbility DroachBreatheFire { get; set; }
        public PgAIAbility DroachLightning { get; set; }
        public PgAIAbility DroachLightningPerching { get; set; }
        public PgAIAbility DroachShockingKnockback { get; set; }
        public PgAIAbility BasiliskClawA { get; set; }
        public PgAIAbility BasiliskClawB { get; set; }
        public PgAIAbility BasiliskToxicBite { get; set; }
        public PgAIAbility BasiliskDebuff { get; set; }
        public PgAIAbility BasiliskCastPerching { get; set; }
        public PgAIAbility CultistArrow1 { get; set; }
        public PgAIAbility CultistArrow2 { get; set; }
        public PgAIAbility CultistOmegaArrow { get; set; }
        public PgAIAbility CultistSword1 { get; set; }
        public PgAIAbility CultistSword2 { get; set; }
        public PgAIAbility CultistSwordStun { get; set; }
        public PgAIAbility BossMegaSword1 { get; set; }
        public PgAIAbility BossMegaSword2 { get; set; }
        public PgAIAbility SedgewickMegaSwordAngry { get; set; }
        public PgAIAbility BossMegaHammer { get; set; }
        public PgAIAbility BossMegaHammer2 { get; set; }
        public PgAIAbility BossMegaRageHammer { get; set; }
        public PgAIAbility ClaudiaTundraSpikes { get; set; }
        public PgAIAbility ClaudiaIceSpear { get; set; }
        public PgAIAbility ClaudiaBlizzard { get; set; }
        public PgAIAbility BigGolemHitA { get; set; }
        public PgAIAbility BigGolemHitB { get; set; }
        public PgAIAbility BigGolemFlingBoss { get; set; }
        public PgAIAbility BigGolemPerchFix { get; set; }
        public PgAIAbility BigGolemFlingBoss2 { get; set; }
        public PgAIAbility BigGolemSummonFireSnake { get; set; }
        public PgAIAbility BigGolemHitB_NoDisable { get; set; }
        public PgAIAbility BigGolemHitA_NoDisable { get; set; }
        public PgAIAbility BigGolemFling { get; set; }
        public PgAIAbility GhoulClawA { get; set; }
        public PgAIAbility GhoulClawB { get; set; }
        public PgAIAbility GhoulSelfBuff { get; set; }
        public PgAIAbility GhoulHammerA { get; set; }
        public PgAIAbility GhoulHammerB { get; set; }
        public PgAIAbility DragonWormSpitElectricity { get; set; }
        public PgAIAbility DragonWormBite { get; set; }
        public PgAIAbility DragonWormSmack { get; set; }
        public PgAIAbility DragonWormRage { get; set; }
        public PgAIAbility DragonWormEscape { get; set; }
        public PgAIAbility DragonWormSpitFire { get; set; }
        public PgAIAbility ColdSphereBurst { get; set; }
        public PgAIAbility ColdSphereFreezeBurst { get; set; }
        public PgAIAbility ManticoreBite { get; set; }
        public PgAIAbility ManticoreClaw { get; set; }
        public PgAIAbility ManticoreSting1 { get; set; }
        public PgAIAbility Manticoresting2 { get; set; }
        public PgAIAbility RakStaffHit { get; set; }
        public PgAIAbility RakStaffPin { get; set; }
        public PgAIAbility RakStaffBlock { get; set; }
        public PgAIAbility RakStaffHeavy { get; set; }
        public PgAIAbility RakSlash { get; set; }
        public PgAIAbility RakKnee { get; set; }
        public PgAIAbility RakKick { get; set; }
        public PgAIAbility RakBarrage { get; set; }
        public PgAIAbility RakSwordSlash { get; set; }
        public PgAIAbility RakHackingBlade { get; set; }
        public PgAIAbility RakDecapitate { get; set; }
        public PgAIAbility RakFireball { get; set; }
        public PgAIAbility RakBreatheFire { get; set; }
        public PgAIAbility RakRingOfFire { get; set; }
        public PgAIAbility RakToxinBomb { get; set; }
        public PgAIAbility RakAcidBomb { get; set; }
        public PgAIAbility RakHealingMist { get; set; }
        public PgAIAbility RakBasicShot { get; set; }
        public PgAIAbility RakHookShot { get; set; }
        public PgAIAbility RakBowBash { get; set; }
        public PgAIAbility RakAimedShot { get; set; }
        public PgAIAbility RakPoisonArrow { get; set; }
        public PgAIAbility RakMindreave { get; set; }
        public PgAIAbility RakPainBubble { get; set; }
        public PgAIAbility RakPanicCharge { get; set; }
        public PgAIAbility RakRevitalize { get; set; }
        public PgAIAbility RakReconstruct { get; set; }
        public PgAIAbility RakBossSlow { get; set; }
        public PgAIAbility RakBossPerchSlow { get; set; }
        public PgAIAbility FlapSkullBite { get; set; }
        public PgAIAbility FlapSkullBigBite { get; set; }
        public PgAIAbility MinotaurClub { get; set; }
        public PgAIAbility MinotaurRageClub { get; set; }
        public PgAIAbility MinotaurBoulder { get; set; }
        public PgAIAbility MinotaurBossRageClub { get; set; }
        public PgAIAbility CockatricePeck { get; set; }
        public PgAIAbility CockatriceTailWhip { get; set; }
        public PgAIAbility CockatriceParalyze { get; set; }
        public PgAIAbility GiantBeetleBite { get; set; }
        public PgAIAbility GiantBeetleInject { get; set; }
        public PgAIAbility GiantBeetleBoulderSpit { get; set; }
        public PgAIAbility BatIllusionSlashA { get; set; }
        public PgAIAbility BatIllusionSlashB { get; set; }
        public PgAIAbility BatIllusionBite { get; set; }
        public PgAIAbility GiantBatSlashA { get; set; }
        public PgAIAbility GiantBatSlashB { get; set; }
        public PgAIAbility GiantBatBite { get; set; }
        public PgAIAbility HagAgingTouch { get; set; }
        public PgAIAbility HagAgingScream { get; set; }
        public PgAIAbility TriffidClawA { get; set; }
        public PgAIAbility TriffidClawB { get; set; }
        public PgAIAbility TriffidTongue { get; set; }
        public PgAIAbility TriffidSpore { get; set; }
        public PgAIAbility TriffidShot { get; set; }
        public PgAIAbility TriffidTongueElite { get; set; }
        public PgAIAbility GiantScorpionClawA { get; set; }
        public PgAIAbility GiantScorpionClawB { get; set; }
        public PgAIAbility GiantScorpionSting { get; set; }
        public PgAIAbility KrakenBeak { get; set; }
        public PgAIAbility KrakenSlam { get; set; }
        public PgAIAbility KrakenRage { get; set; }
        public PgAIAbility KrakenBabyBeak { get; set; }
        public PgAIAbility KrakenBabySlam { get; set; }
        public PgAIAbility KrakenBabyRage { get; set; }
        public PgAIAbility RanalonHit { get; set; }
        public PgAIAbility RanalonHitB { get; set; }
        public PgAIAbility RanalonKick { get; set; }
        public PgAIAbility RanalonTongue { get; set; }
        public PgAIAbility RanalonZap { get; set; }
        public PgAIAbility RanalonZapB { get; set; }
        public PgAIAbility RanalonHeal { get; set; }
        public PgAIAbility RanalonRoot { get; set; }
        public PgAIAbility RanalonSelfBuff { get; set; }
        public PgAIAbility RanalonSelfBuffElite { get; set; }
        public PgAIAbility RanalonGuardianStab { get; set; }
        public PgAIAbility RanalonGuardianStabB { get; set; }
        public PgAIAbility RanalonGuardianBite { get; set; }
        public PgAIAbility RanalonGuardianBlind { get; set; }
        public PgAIAbility RanalonDoctrineKeeperStab { get; set; }
        public PgAIAbility RanalonDoctrineKeeperBlind { get; set; }
        public PgAIAbility BarghestBiteA { get; set; }
        public PgAIAbility BarghestBiteB { get; set; }
        public PgAIAbility BarghestDebuff { get; set; }
        public PgAIAbility WorghestDebuff { get; set; }
        public PgAIAbility BallistaFire { get; set; }
        public PgAIAbility BallistaFire_Long { get; set; }
        public PgAIAbility GargoyleSlamA { get; set; }
        public PgAIAbility GargoyleSlamB { get; set; }
        public PgAIAbility GargoyleStun { get; set; }
        public PgAIAbility GargoyleBossStun { get; set; }
        public PgAIAbility ScrayBite { get; set; }
        public PgAIAbility ScrayStab { get; set; }
        public PgAIAbility HippoBite { get; set; }
        public PgAIAbility HippoBiteAndHeal1 { get; set; }
        public PgAIAbility BigCatClaw_Pet { get; set; }
        public PgAIAbility BigCatPounce_Pet { get; set; }
        public PgAIAbility BigCatKill_Pet1 { get; set; }
        public PgAIAbility BigCatKill_Pet2 { get; set; }
        public PgAIAbility BigCatKill_Pet3 { get; set; }
        public PgAIAbility BigCatKill_Pet4 { get; set; }
        public PgAIAbility BigCatKill_Pet5 { get; set; }
        public PgAIAbility BigCatKill_Pet6 { get; set; }
        public PgAIAbility BigCatUltraKill_Pet1 { get; set; }
        public PgAIAbility BigCatUltraKill_Pet2 { get; set; }
        public PgAIAbility BigCatUltraKill_Pet3 { get; set; }
        public PgAIAbility BigCatUltraKill_Pet4 { get; set; }
        public PgAIAbility BigCatUltraKill_Pet5 { get; set; }
        public PgAIAbility BigCatUltraKill_Pet6 { get; set; }
        public PgAIAbility BigCatRoot_Pet1 { get; set; }
        public PgAIAbility BigCatRoot_Pet2 { get; set; }
        public PgAIAbility BigCatRoot_Pet3 { get; set; }
        public PgAIAbility BigCatRoot_Pet4 { get; set; }
        public PgAIAbility BigCatVuln_Pet1 { get; set; }
        public PgAIAbility BigCatVuln_Pet2 { get; set; }
        public PgAIAbility BigCatVuln_Pet3 { get; set; }
        public PgAIAbility BigCatVuln_Pet4 { get; set; }
        public PgAIAbility BigCatHeal_Pet1 { get; set; }
        public PgAIAbility BigCatHeal_Pet2 { get; set; }
        public PgAIAbility BigCatHeal_Pet3 { get; set; }
        public PgAIAbility BigCatHeal_Pet4 { get; set; }
        public PgAIAbility BigCatHeal_Pet5 { get; set; }
        public PgAIAbility BigCatHeal_Pet6 { get; set; }
        public PgAIAbility GrimalkinPuncture_Pet1 { get; set; }
        public PgAIAbility GrimalkinPuncture_Pet2 { get; set; }
        public PgAIAbility GrimalkinPuncture_Pet3 { get; set; }
        public PgAIAbility GrimalkinPuncture_Pet4 { get; set; }
        public PgAIAbility GrimalkinPuncture_Pet5 { get; set; }
        public PgAIAbility GrimalkinPuncture_Pet6 { get; set; }
        public PgAIAbility GrimalkinFlee_Pet1 { get; set; }
        public PgAIAbility GrimalkinFlee_Pet2 { get; set; }
        public PgAIAbility GrimalkinFlee_Pet3 { get; set; }
        public PgAIAbility RatBite_Pet { get; set; }
        public PgAIAbility RatClaw_Pet { get; set; }
        public PgAIAbility RatDeRage_Pet1 { get; set; }
        public PgAIAbility RatDeRage_Pet2 { get; set; }
        public PgAIAbility RatDeRage_Pet3 { get; set; }
        public PgAIAbility RatDeRage_Pet4 { get; set; }
        public PgAIAbility RatDeRage_Pet5 { get; set; }
        public PgAIAbility RatDeRage_Pet6 { get; set; }
        public PgAIAbility RatHeal_Pet1 { get; set; }
        public PgAIAbility RatHeal_Pet2 { get; set; }
        public PgAIAbility RatHeal_Pet3 { get; set; }
        public PgAIAbility RatHeal_Pet4 { get; set; }
        public PgAIAbility RatHeal_Pet5 { get; set; }
        public PgAIAbility RatHeal_Pet6 { get; set; }
        public PgAIAbility RatVuln_Pet1 { get; set; }
        public PgAIAbility RatVuln_Pet2 { get; set; }
        public PgAIAbility RatVuln_Pet3 { get; set; }
        public PgAIAbility RatVuln_Pet4 { get; set; }
        public PgAIAbility FireRatBite_Pet { get; set; }
        public PgAIAbility FireRatClaw_Pet { get; set; }
        public PgAIAbility RatBurn_Pet1 { get; set; }
        public PgAIAbility RatBurn_Pet2 { get; set; }
        public PgAIAbility RatBurn_Pet3 { get; set; }
        public PgAIAbility RatBurn_Pet4 { get; set; }
        public PgAIAbility RatBurn_Pet5 { get; set; }
        public PgAIAbility RatBurn_Pet6 { get; set; }
        public PgAIAbility BearBite_Pet { get; set; }
        public PgAIAbility BearClaw_Pet { get; set; }
        public PgAIAbility BearTaunt_Pet1 { get; set; }
        public PgAIAbility BearTaunt_Pet2 { get; set; }
        public PgAIAbility BearTaunt_Pet3 { get; set; }
        public PgAIAbility BearTaunt_Pet4 { get; set; }
        public PgAIAbility BearTaunt_Pet5 { get; set; }
        public PgAIAbility BearTaunt_Pet6 { get; set; }
        public PgAIAbility BearStun_Pet1 { get; set; }
        public PgAIAbility BearStun_Pet2 { get; set; }
        public PgAIAbility BearStun_Pet3 { get; set; }
        public PgAIAbility BearStun_Pet4 { get; set; }
        public PgAIAbility BearWarmth_Pet1 { get; set; }
        public PgAIAbility BearWarmth_Pet2 { get; set; }
        public PgAIAbility BearWarmth_Pet3 { get; set; }
        public PgAIAbility BearWarmth_Pet4 { get; set; }
        public PgAIAbility BearWarmth_Pet5 { get; set; }
        public PgAIAbility BearWarmth_Pet6 { get; set; }
        public PgAIAbility BearSelfHeal_Pet1 { get; set; }
        public PgAIAbility BearSelfHeal_Pet2 { get; set; }
        public PgAIAbility BearSelfHeal_Pet3 { get; set; }
        public PgAIAbility BearSelfHeal_Pet4 { get; set; }
        public PgAIAbility BearSelfHeal_Pet5 { get; set; }
        public PgAIAbility BearSelfHeal_Pet6 { get; set; }
        public PgAIAbility BearUltra_Pet1 { get; set; }
        public PgAIAbility BearUltra_Pet2 { get; set; }
        public PgAIAbility BearUltra_Pet3 { get; set; }
        public PgAIAbility BearUltra_Pet4 { get; set; }
        public PgAIAbility BearUltra_Pet5 { get; set; }
        public PgAIAbility BearUltra_Pet6 { get; set; }
        public PgAIAbility PumpkinMimicBite { get; set; }
        public PgAIAbility PumpkinMimicRage { get; set; }
        public PgAIAbility WorldBossCiervosNightmareHoof { get; set; }
        public PgAIAbility PumpkinBomb { get; set; }
        public PgAIAbility PumpkinFire { get; set; }
        public PgAIAbility WorldBossKarnag_Opener { get; set; }
        public PgAIAbility WorldBossKarnag_Rage { get; set; }
        public PgAIAbility WorldBossClaudiaTundraSpikes { get; set; }
        public PgAIAbility WorldBossClaudiaIceSpear { get; set; }
        public PgAIAbility WorldBossClaudiaBlizzard { get; set; }
        public PgAIAbility DeerFrontKick { get; set; }
        public PgAIAbility DeerRageKick { get; set; }
        public PgAIAbility PetUndeadReapPunch { get; set; }
        public PgAIAbility PetUndeadRageReap { get; set; }
        public PgAIAbility ViperSpitPoison { get; set; }
        public PgAIAbility ViperBite { get; set; }
        public PgAIAbility Slime_SummonSlime6 { get; set; }
        public PgAIAbility BossSlime_SummonSlime7Elite { get; set; }
        public PgAIAbility SpiderBite_ProblemSpider { get; set; }
        public PgAIAbility PetRatkinUndeadElectricityA { get; set; }
        public PgAIAbility PetRatkinUndeadElectricityB { get; set; }
        public PgAIAbility PetRatkinUndeadElectricityBurst { get; set; }
        public PgAIAbility RakToxinBomb_Tolmar { get; set; }
        public PgAIAbility HippoBiteAndHeal { get; set; }
        public PgAIAbility TreantSlashA { get; set; }
        public PgAIAbility TreantSlashB { get; set; }
        public PgAIAbility TreantStomp { get; set; }
        public PgAIAbility TreantDoT1 { get; set; }
        public PgAIAbility RatTrapAttack { get; set; }
        public PgAIAbility RatkinSwordSlash { get; set; }
        public PgAIAbility RatkinSwordPierce { get; set; }
        public PgAIAbility RatkinSwordFinisher { get; set; }
        public PgAIAbility RatkinDeathsHold { get; set; }
        public PgAIAbility RatkinDarknessBolt { get; set; }
        public PgAIAbility RatkinLifeSteal { get; set; }
        public PgAIAbility RatkinBossWaveOfDarkness { get; set; }
        public PgAIAbility RatkinReverberatingStrike70 { get; set; }
        public PgAIAbility RatkinHammer { get; set; }
        public PgAIAbility RatkinHammerStun { get; set; }
        public PgAIAbility RatkinUndeadElectricityA { get; set; }
        public PgAIAbility RatkinUndeadElectricityB { get; set; }
        public PgAIAbility RatkinUndeadElectricityBurst { get; set; }
        public PgAIAbility RatBuffDarkness_Pet1 { get; set; }
        public PgAIAbility RatBuffDarkness_Pet2 { get; set; }
        public PgAIAbility RatBuffDarkness_Pet3 { get; set; }
        public PgAIAbility RatBuffDarkness_Pet4 { get; set; }
        public PgAIAbility RatBuffDarkness_Pet5 { get; set; }
        public PgAIAbility RatBuffDarkness_Pet6 { get; set; }
        public PgAIAbility ViperRageBite { get; set; }
        public PgAIAbility SlugBite { get; set; }
        public PgAIAbility SlugWebDebuff { get; set; }
        public PgAIAbility SmallishScorpionClawA { get; set; }
        public PgAIAbility SmallishScorpionClawB { get; set; }
        public PgAIAbility SmallishScorpionSting { get; set; }
        public PgAIAbility RootTrap { get; set; }
        public PgAIAbility ElementalFireSlam { get; set; }
        public PgAIAbility ElementalFireball { get; set; }
        public PgAIAbility ElementalHateFireball { get; set; }
        public PgAIAbility ElementalHateFireball2 { get; set; }
        public PgAIAbility ElementalHateFireball3 { get; set; }
        public PgAIAbility ElementalFireballB { get; set; }
        public PgAIAbility FaeIceSpearA { get; set; }
        public PgAIAbility FaeIceSpearB { get; set; }
        public PgAIAbility FaeColdSphere { get; set; }
        public PgAIAbility LethargyPuckFrostbite { get; set; }
        public PgAIAbility LethargyPuckRage { get; set; }
        public PgAIAbility BeeStab_Pet { get; set; }
        public PgAIAbility BeeInject_Pet1 { get; set; }
        public PgAIAbility BeeInject_Pet2 { get; set; }
        public PgAIAbility BeeInject_Pet3 { get; set; }
        public PgAIAbility BeeInject_Pet4 { get; set; }
        public PgAIAbility BeeInject_Pet5 { get; set; }
        public PgAIAbility BeeInject_Pet6 { get; set; }
        public PgAIAbility BeeVuln_Pet1 { get; set; }
        public PgAIAbility BeeVuln_Pet2 { get; set; }
        public PgAIAbility BeeVuln_Pet3 { get; set; }
        public PgAIAbility BeeVuln_Pet4 { get; set; }
        public PgAIAbility WaspShoot_Pet { get; set; }
        public PgAIAbility WaspBlast_Pet1 { get; set; }
        public PgAIAbility WaspBlast_Pet2 { get; set; }
        public PgAIAbility WaspBlast_Pet3 { get; set; }
        public PgAIAbility WaspBlast_Pet4 { get; set; }
        public PgAIAbility WaspBlast_Pet5 { get; set; }
        public PgAIAbility WaspBlast_Pet6 { get; set; }
        public PgAIAbility WaspSlow_Pet1 { get; set; }
        public PgAIAbility WaspSlow_Pet2 { get; set; }
        public PgAIAbility WaspSlow_Pet3 { get; set; }
        public PgAIAbility WaspSlow_Pet4 { get; set; }
        public PgAIAbility WaspStab_Pet { get; set; }
        public PgAIAbility WaspDebuff_Pet1 { get; set; }
        public PgAIAbility WaspDebuff_Pet2 { get; set; }
        public PgAIAbility WaspDebuff_Pet3 { get; set; }
        public PgAIAbility WaspDebuff_Pet4 { get; set; }
        public PgAIAbility WaspDebuff_Pet5 { get; set; }
        public PgAIAbility WaspDebuff_Pet6 { get; set; }
        public PgAIAbility WaspBurst_Pet1 { get; set; }
        public PgAIAbility WaspBurst_Pet2 { get; set; }
        public PgAIAbility WaspBurst_Pet3 { get; set; }
        public PgAIAbility WaspBurst_Pet4 { get; set; }
        public PgAIAbility PhoenixPeck { get; set; }
        public PgAIAbility PhoenixFireball { get; set; }
        public PgAIAbility PhoenixBlast { get; set; }
        public PgAIAbility BeeStab { get; set; }
        public PgAIAbility BeeInject { get; set; }
        public PgAIAbility BeeShoot { get; set; }
        public PgAIAbility BeeShootB { get; set; }
        public PgAIAbility WaspStab { get; set; }
        public PgAIAbility WaspRageStab { get; set; }
        public PgAIAbility WaspRangedDebuff { get; set; }
        public PgAIAbility WaspRangedDebuffB { get; set; }
        public PgAIAbility WaspRangedDebuffC { get; set; }
        public PgAIAbility WaspShoot { get; set; }
        public PgAIAbility WaspRageBurst { get; set; }
        public PgAIAbility WaspSlowA { get; set; }
        public PgAIAbility WaspSlowB { get; set; }
        public PgAIAbility PixieSlash { get; set; }
        public PgAIAbility PixieRageSlash { get; set; }
        public PgAIAbility StunTrapExplode { get; set; }
        public PgAIAbility SpiderIncubate1 { get; set; }
        public PgAIAbility SpiderIncubate2 { get; set; }
        public PgAIAbility RanalonHeal1 { get; set; }
        public PgAIAbility RanalonHeal2 { get; set; }
        public PgAIAbility RanalonSelfBuff1 { get; set; }
        public PgAIAbility RanalonSelfBuff2 { get; set; }
        public PgAIAbility ScrayStab1 { get; set; }
        public PgAIAbility ScrayStab2 { get; set; }
        public PgAIAbility WaspIceStab_Pet { get; set; }
        public PgAIAbility WaspIceSlow_Pet1 { get; set; }
        public PgAIAbility WaspIceSlow_Pet2 { get; set; }
        public PgAIAbility WaspIceSlow_Pet3 { get; set; }
        public PgAIAbility WaspIceSlow_Pet4 { get; set; }
        public PgAIAbility WaspIceStab { get; set; }
        public PgAIAbility WaspIceRageStab { get; set; }
        public PgAIAbility WaspIceSlowA { get; set; }
        public PgAIAbility WaspIceSlowB { get; set; }
        public PgAIAbility PhoenixFlash { get; set; }
        public PgAIAbility KrakenRageCurse { get; set; }
        public PgAIAbility HealingAura { get; set; }
        public PgAIAbility FaeConduitHeal { get; set; }
        public PgAIAbility BigCatRoot_Pet5 { get; set; }
        public PgAIAbility BigCatRoot_Pet6 { get; set; }
        public PgAIAbility BearStun_Pet5 { get; set; }
        public PgAIAbility BearStun_Pet6 { get; set; }
        public PgAIAbility PhoenixClaw { get; set; }
        public PgAIAbility GoatBite { get; set; }
        public PgAIAbility GoatKick { get; set; }
        public PgAIAbility GoatSmite { get; set; }
        public PgAIAbility TurretCrystalZapMediumRange2 { get; set; }
        public PgAIAbility TurretCrystalZapMediumRangeSlow { get; set; }
        public PgAIAbility RanalonGuardianPull { get; set; }
        public PgAIAbility ScrayStab3 { get; set; }
        public PgAIAbility SharkBite { get; set; }
        public PgAIAbility SharkMegaBite { get; set; }
        public PgAIAbility SharkOpener { get; set; }
        public PgAIAbility TrollHeal { get; set; }
        public PgAIAbility TrollSwordA { get; set; }
        public PgAIAbility TrollSwordB { get; set; }
    }
}
