namespace PgJsonObjects
{
    interface IPgAdvancement
    {
        double NonCombatRegenHealthMod { get; }
        double? RawNonCombatRegenHealthMod { get; }
        double CombatRegenHealthMod { get; }
        double? RawCombatRegenHealthMod { get; }
        double CombatRegenHealthDelta { get; }
        double? RawCombatRegenHealthDelta { get; }
        double NonCombatRegenArmorMod { get; }
        double? RawNonCombatRegenArmorMod { get; }
        double NonCombatRegenArmordelta { get; }
        double? RawNonCombatRegenArmordelta { get; }
        double CombatRegenArmorMod { get; }
        double? RawCombatRegenArmorMod { get; }
        double NonCombatRegenPowerMod { get; }
        double? RawNonCombatRegenPowerMod { get; }
        double CombatRegenPowerMod { get; }
        double? RawCombatRegenPowerMod { get; }
        double NonCombatRegenRageMod { get; }
        double? RawNonCombatRegenRageMod { get; }
        double CombatRegenRageMod { get; }
        double? RawCombatRegenRageMod { get; }
        double MentalDefenseRating { get; }
        double? RawMentalDefenseRating { get; }
        double SprintBoost { get; }
        double? RawSprintBoost { get; }
        double TauntMod { get; }
        double? RawTauntMod { get; }
        double IgnoreChanceFear { get; }
        double? RawIgnoreChanceFear { get; }
        double IgnoreChanceMezz { get; }
        double? RawIgnoreChanceMezz { get; }
        double IgnoreChanceKnockback { get; }
        double? RawIgnoreChanceKnockback { get; }
        double EvasionChance { get; }
        double? RawEvasionChance { get; }
        double LootBoostChanceUncommon { get; }
        double? RawLootBoostChanceUncommon { get; }
        double LootBoostChanceRare { get; }
        double? RawLootBoostChanceRare { get; }
        double LootBoostChanceExceptional { get; }
        double? RawLootBoostChanceExceptional { get; }
        double LootBoostChanceEpic { get; }
        double? RawLootBoostChanceEpic { get; }
        double LootBoostChanceLegendary { get; }
        double? RawLootBoostChanceLegendary { get; }
        double MaxHealth { get; }
        double? RawMaxHealth { get; }
        double MaxArmor { get; }
        double? RawMaxArmor { get; }
        double MaxRage { get; }
        double? RawMaxRage { get; }
        double MaxPower { get; }
        double? RawMaxPower { get; }
        double MaxBreath { get; }
        double? RawMaxBreath { get; }
        double BoostUniversalDirect { get; }
        double? RawBoostUniversalDirect { get; }
        double BoostAbilityRageAttack { get; }
        double? RawBoostAbilityRageAttack { get; }
        double ModAbilityRageAttack { get; }
        double? RawModAbilityRageAttack { get; }
        double MonsterCombatXpValue { get; }
        double? RawMonsterCombatXpValue { get; }
        double CombatRegenArmorDelta { get; }
        double? RawCombatRegenArmorDelta { get; }
        double CombatRegenDelta { get; }
        double? RawCombatRegenDelta { get; }
        double MaxInventorySize { get; }
        double? RawMaxInventorySize { get; }
        double MaxMetabolism { get; }
        double? RawMaxMetabolism { get; }
        double NpcModFavorFromGifts { get; }
        double? RawNpcModFavorFromGifts { get; }
        double NpcModFavorFromHangouts { get; }
        double? RawNpcModFavorFromHangouts { get; }
        double NpcModMaxSalesValue { get; }
        double? RawNpcModMaxSalesValue { get; }
        double NpcModTrainingCost { get; }
        double? RawNpcModTrainingCost { get; }
        int NumInventoryFolders { get; }
        int? RawNumInventoryFolders { get; }
        double HighCleanlinessXpEarnedMod { get; }
        double? RawHighCleanlinessXpEarnedMod { get; }
        double LowCleanlinessXpEarnedMod { get; }
        double? RawLowCleanlinessXpEarnedMod { get; }
        double MaxArmorMitigationRatio { get; }
        double? RawMaxArmorMitigationRatio { get; }
        double ShowCleanlinessIndicators { get; }
        double? RawShowCleanlinessIndicators { get; }
        double HighCommunityXpEarnedMod { get; }
        double? RawHighCommunityXpEarnedMod { get; }
        double LowCommunityXpEarnedMod { get; }
        double? RawLowCommunityXpEarnedMod { get; }
        double ShowCommunityIndicators { get; }
        double? RawShowCommunityIndicators { get; }
        double HighPeaceblenessXpEarnedMod { get; }
        double? RawHighPeaceblenessXpEarnedMod { get; }
        double LowPeaceblenessXpEarnedMod { get; }
        double? RawLowPeaceblenessXpEarnedMod { get; }
        double ShowPeaceblenessIndicators { get; }
        double? RawShowPeaceblenessIndicators { get; }
        double StaffArmorAutoHeal { get; }
        double? RawStaffArmorAutoHeal { get; }
        double MaxMapPinsPerArea { get; }
        double? RawMaxMapPinsPerArea { get; }
        double MaxMapPinIcons { get; }
        double? RawMaxMapPinIcons { get; }
        double WorkOrderCoinRewardMod { get; }
        double? RawWorkOrderCoinRewardMod { get; }
        double MaxActiveWorkOrders { get; }
        double? RawMaxActiveWorkOrders { get; }
        double PlayerOrdersMaxActive { get; }
        double? RawPlayerOrdersMaxActive { get; }
        double ShopInventorySizeDelta { get; }
        double? RawShopInventorySizeDelta { get; }
        double MailShopNumFree { get; }
        double? RawMailShopNumFree { get; }
        double ShopHiringMaxPrepDays { get; }
        double? RawShopHiringMaxPrepDays { get; }
        double ShopLogDaysKept { get; }
        double? RawShopLogDaysKept { get; }
        double ShopHiringNumFree { get; }
        double? RawShopHiringNumFree { get; }
        double CriticalHitDamage { get; }
        double? RawCriticalHitDamage { get; }
    }
}
