namespace PgJsonObjects
{
    public enum AbilityTargetParticle
    {
        Internal_None,
        WeaponHit,
        ComboHit,
        BigHit,
        FireHit,
        SlashHit,
        Bite,
        ClawMarks,
        ClawCombo,
        SmallBuff,
        SpeedUp,
        Agitate,
        DeathExplosion,
        LightningStrike,
        HitVoid,
        ElectricityBurst,
        SpiritBreak,
        HolyFireStrike,
        PsionicDebuff,
        AcidBomb,
        GroundImpact,
        ElectricityHit,
        CombatRefresh,
        ElectricityHit2,
        EnergyPillar,
    }
}
