namespace PgJsonObjects
{
    public enum SpecialNpc
    {
        Internal_None,
        WerewolfAltar,
        AdminTestNpc,
        CatCharmPedestal,
        BearCharmPedestal,
        GoblinFireResearchDesk1,
        Altar_Druid,
        AlchemyBook,
        UkorgasWelcomeSign,
        HoplologyBook,
        CorpseOfSerbule,
        BorghildLibrary,
        AlchemyBook2,
        GolemBook,
        AlchemyBook_SpiderEggs,
        DeathPenaltyAltar,
        NPC_Sphere,
        NPC_ChemistryPlaceholder,
        NPC_Oritania,
        NPC_Pennoc,
        NPC_Lakrea,
        NPC_DyePlaceholder,
        NPC_DyeMonster,
        NPC_Bahdba,
        NPC_Chirrra,
    }
}
