namespace PgJsonObjects
{
    public enum RecipeKeyword
    {
        Internal_None,
        Lint_NotLearnable,
        NoValueGeneration,
        HighValueGeneration,
        Teleport,
        EatsBottle,
        Lint_NotObtainable,
        Lint_NoXP,
        Dye,
        Lint_NoResult,
        StorageCrateDruid,
        ShamanicInfusion,
        ClownfishFillet,
        MushroomTeleport,
        CandiedApple,
        JackOLantern,
        PumpkinSpiceTea,
        NotIncludedInDynamicUsageListings,
        MealRecipe,
        InstantSnackRecipe,
        SnackRecipe,
        Lint_MealCategory,
        Lint_IconId,
        PixiePocket,
        Lint_LevelTooHigh,
        ShieldWax,
        PumpkinSoup,
        PumpkinSalad,
    }
}
